# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""A configuration class for controlling various aspects of the assembler's behavior."""


class GlobalConfig:
    """
    A configuration class for controlling various aspects of the assembler's behavior.

    Attributes:
        suppress_comments (bool):
            If True, no comments will be emitted in the output generated by the assembler.

        useHBMPlaceHolders (bool):
            Specifies whether to use placeholders (names) for variable locations in HBM
            or the actual variable locations.

        useXInstFetch (bool):
            Specifies whether `xinstfetch` instructions should be added into CInstQ or not.
            When no `xinstfetch` instructions are added, it is assumed that the HERACLES
            automated mechanism for `xinstfetch` will be activated.

        debugVerbose (int):
            If greater than 0, verbose prints will occur. Its value indicates how often to
            print within loops (every `debugVerbose` iterations). This is used for internal
            debugging purposes.
        hashHBM (bool): Specifies whether the target architecture has HBM or not.
    """

    suppress_comments = False
    useHBMPlaceHolders = True
    useXInstFetch = True
    debugVerbose: int = 0
    hasHBM = True
