Encrypted Computing SDK: AddOperation Class Reference
AddOperation Class Reference
#include <add.h>
Public Member Functions
AddOperation ()
void constructTest () override
Public Member Functions inherited from PisaKernelTest
PisaKernelTest ()
const std::shared_ptr< pisa::poly::PolyProgram > getProgramTrace ()
std::map< std::string, std::string > & getConfiguration ()
Static Public Member Functions
static std::string operationName ()
Additional Inherited Members
Protected Attributes inherited from PisaKernelTest
std::shared_ptr< pisa::poly::PolyProgram > program_trace
bool created = false
std::map< std::string, std::string > configuration
Detailed Description
Definition at line 10 of file add.h.
Constructor & Destructor Documentation
AddOperation()
AddOperation::AddOperation ()
Definition at line 15 of file add.h.
References PisaKernelTest::configuration, and operationName().
Member Function Documentation
constructTest()
void AddOperation::constructTest () override virtual
Reimplemented from PisaKernelTest.
Definition at line 24 of file add.h.
References he_as::config, PisaKernelTest::configuration, PisaKernelTest::created, pisa::poly::library::createPolyOperation(), and PisaKernelTest::program_trace.
operationName()
static std::string AddOperation::operationName () static
Definition at line 13 of file add.h.
Referenced by AddOperation().
The documentation for this class was generated from the following file:
p-isa_tools/program_mapper/p_isa/tests/pisa_kernel_tests/add.h