Encrypted Computing SDK: kerngen.pisa_generators.basic.Mul Class Reference
kerngen.pisa_generators.basic.Mul Class Reference
Class representing the high-level multiplication operation.
Public Member Functions
def generate_unit (self, int unit, int q, int out_idx, InIdxs in_idxs, *int|None digit=None)
Helper for a given unit and q generate the p-isa ops for a multiplication.
list[PIsaOp] to_pisa (self)
Return the p-isa equivalent of a Mul.
Public Member Functions inherited from kerngen.high_parser.types.HighOp
def from_string (cls, context, polys_map, str args_line)
Construct HighOp from a string args.
Private Member Functions
list[PIsaOp] _keypolys_to_pisa (self, list[InIdxs] all_idxs)
list[PIsaOp] _polys_to_pisa (self, list[InIdxs] all_idxs)
Detailed Description
Class representing the high-level multiplication operation.
Definition at line 132 of file basic.py.
Member Function Documentation
_keypolys_to_pisa()
list[PIsaOp] kerngen.pisa_generators.basic.Mul._keypolys_to_pisa (self, list[InIdxs] all_idxs) private
Definition at line 170 of file basic.py.
References kerngen.high_parser.parser.ParseResults.context, and kerngen.pisa_generators.basic.Mul.generate_unit().
Referenced by kerngen.pisa_generators.basic.Mul.to_pisa().
_polys_to_pisa()
list[PIsaOp] kerngen.pisa_generators.basic.Mul._polys_to_pisa (self, list[InIdxs] all_idxs) private
Definition at line 182 of file basic.py.
References kerngen.high_parser.parser.ParseResults.context, and kerngen.pisa_generators.basic.Mul.generate_unit().
Referenced by kerngen.pisa_generators.basic.Mul.to_pisa().
generate_unit()
def kerngen.pisa_generators.basic.Mul.generate_unit (self, int unit, int q, int out_idx, InIdxs in_idxs, *int | None digit = None)
Helper for a given unit and q generate the p-isa ops for a multiplication.
Definition at line 141 of file basic.py.
References kerngen.high_parser.parser.ParseResults.context.
Referenced by kerngen.pisa_generators.basic.Mul._keypolys_to_pisa(), and kerngen.pisa_generators.basic.Mul._polys_to_pisa().
to_pisa()
list[PIsaOp] kerngen.pisa_generators.basic.Mul.to_pisa (self)
Return the p-isa equivalent of a Mul.
Reimplemented from kerngen.high_parser.types.HighOp.
Definition at line 193 of file basic.py.
References kerngen.pisa_generators.basic.Mul._keypolys_to_pisa(), kerngen.pisa_generators.basic.Mul._polys_to_pisa(), and kerngen.pisa_generators.basic.convolution_indices().
The documentation for this class was generated from the following file:
p-isa_tools/kerngen/pisa_generators/basic.py