Encrypted Computing SDK: kerngen.pisa_generators.mod.Mod Class Reference
kerngen.pisa_generators.mod.Mod Class Reference
Class representing mod down operation.
Public Member Functions
list[PIsaOp] to_pisa (self)
Return the p-isa code to perform an mod switch down.
Public Member Functions inherited from kerngen.high_parser.types.HighOp
def from_string (cls, context, polys_map, str args_line)
Construct HighOp from a string args.
Public Attributes
pisa_ops
Stage hold a list of PISA ops, which are used by generate_mod_stages.
Static Public Attributes
string MOD_P = "_mod_p"
string MOD_QLAST = "_mod_qLast"
str
Detailed Description
Class representing mod down operation.
Definition at line 28 of file mod.py.
Member Function Documentation
to_pisa()
list[PIsaOp] kerngen.pisa_generators.mod.Mod.to_pisa (self)
Return the p-isa code to perform an mod switch down.
Reimplemented from kerngen.high_parser.types.HighOp.
Definition at line 39 of file mod.py.
References kerngen.pisa_generators.basic.common_immediates(), kerngen.high_parser.parser.ParseResults.context, kerngen.pisa_generators.basic.duplicate_polys(), and kerngen.pisa_generators.basic.split_last_rns_polys().
Member Data Documentation
MOD_P
string kerngen.pisa_generators.mod.Mod.MOD_P = "_mod_p" static
Definition at line 30 of file mod.py.
MOD_QLAST
string kerngen.pisa_generators.mod.Mod.MOD_QLAST = "_mod_qLast" static
Definition at line 31 of file mod.py.
pisa_ops
kerngen.pisa_generators.mod.Mod.pisa_ops
Stage hold a list of PISA ops, which are used by generate_mod_stages.
Definition at line 69 of file mod.py.
str
kerngen.pisa_generators.mod.Mod.str static
Definition at line 36 of file mod.py.
The documentation for this class was generated from the following file:
p-isa_tools/kerngen/pisa_generators/mod.py