Encrypted Computing SDK: instructions.minst.minstruction.MInstruction Class Reference
instructions.minst.minstruction.MInstruction Class Reference
Represents a memory-level instruction (MInstruction).
Public Member Functions
def __init__ (self, int id, int throughput, int latency, str comment="")
Constructs a new MInstruction.
Public Member Functions inherited from instructions.instruction.BaseInstruction
dict isa_spec_as_dict (cls)
Returns attributes as dictionary.
def SetNumDests (cls, val)
def SetNumSources (cls, val)
def SetDefaultThroughput (cls, val)
def SetDefaultLatency (cls, val)
str name (cls)
Name for the instruction.
str OP_NAME_PISA (cls)
P-ISA name for the instruction.
str OP_NAME_ASM (cls)
ASM-ISA name for instruction.
def __repr__ (self)
Returns a string representation of the BaseInstruction object.
def __eq__ (self, other)
Checks equality between two BaseInstruction objects.
def __hash__ (self)
Returns the hash of the BaseInstruction object.
def __str__ (self)
Returns a string representation of the BaseInstruction object.
def set_schedule_timing_index (self, int value)
Sets the schedule timing index.
def freeze (self)
Called immediately after _schedule() to freeze the instruction after scheduling to preserve the instruction string representation to output into the listing.
int schedule (self, CycleType cycle_count, int schedule_idx)
Schedules and freezes the instruction, simulating timings of executing this instruction.
str toStringFormat (self, preamble, str op_name, *extra_args)
Converts the instruction to a string format.
str toPISAFormat (self)
Converts the instruction to P-ISA kernel format.
str toXASMISAFormat (self)
Converts the instruction to ASM-ISA format.
str toCASMISAFormat (self)
Converts the instruction to CInst ASM-ISA format.
str toMASMISAFormat (self)
Converts the instruction to MInst ASM-ISA format.
Properties
count = property
Returns the MInstruction counter value for this instruction.
Properties inherited from instructions.instruction.BaseInstruction
id = property
Gets the unique ID for the instruction.
schedule_timing = property
Retrieves the 1-based index for this instruction in its schedule listing, or less than 1 if not scheduled yet.
is_scheduled = property
Checks if the instruction is scheduled.
throughput = property
Gets the throughput of the instruction.
latency = property
Gets the latency of the instruction.
dests = property
Gets the list of destination objects.
sources = property
Gets the list of source objects.
Private Member Functions
def count (self)
def _get_cycle_ready (self)
str _toMASMISAFormat (self, *extra_args)
Private Attributes
__count
Static Private Attributes
int __minst_count
Additional Inherited Members
Public Attributes inherited from instructions.instruction.BaseInstruction
comment
Detailed Description
Represents a memory-level instruction (MInstruction).
This class is used to encapsulate the properties and behaviors of a memory-level instruction, including its throughput, latency, and a unique counter value that increases with each MInstruction created.
Methods: count: Returns the MInstruction counter value for this instruction.
Definition at line 14 of file minstruction.py.
Constructor & Destructor Documentation
__init__()
def instructions.minst.minstruction.MInstruction.__init__ (self, int id, int throughput, int latency, str comment = "")
Constructs a new MInstruction.
Parameters: id (int): User-defined ID for the instruction. It will be bundled with a nonce to form a unique ID.
throughput (int): The throughput of the instruction.
latency (int): The latency of the instruction.
comment (str, optional): A comment for the instruction. Defaults to an empty string.
Reimplemented from instructions.instruction.BaseInstruction.
Definition at line 33 of file minstruction.py.
Member Function Documentation
_get_cycle_ready()
def instructions.minst.minstruction.MInstruction._get_cycle_ready (self) private
   Returns a CycleType object indicating when the instruction is ready.
   Returns:
       CycleType: A CycleType object with bundle and cycle set to 0.
Reimplemented from instructions.instruction.BaseInstruction.
Definition at line 63 of file minstruction.py.
Referenced by common.cycle_tracking.CycleTracker.cycle_ready().
_toMASMISAFormat()
str instructions.minst.minstruction.MInstruction._toMASMISAFormat (self, * extra_args) private
   Converts the instruction to MInst ASM-ISA format.
   See inherited for more information.
   Parameters:
       extra_args: Additional arguments for formatting.
   Returns:
       str: The instruction in MInst ASM-ISA format.
Reimplemented from instructions.instruction.BaseInstruction.
Reimplemented in instructions.minst.msyncc.Instruction, instructions.minst.mstore.Instruction, and instructions.minst.mload.Instruction.
Definition at line 79 of file minstruction.py.
References instructions.instruction.BaseInstruction.dests, instructions.instruction.BaseInstruction.OP_NAME_ASM(), instructions.instruction.BaseInstruction.sources, and instructions.instruction.BaseInstruction.toStringFormat().
Referenced by instructions.instruction.BaseInstruction.freeze(), and instructions.instruction.BaseInstruction.toMASMISAFormat().
count()
def instructions.minst.minstruction.MInstruction.count (self) private
Definition at line 52 of file minstruction.py.
References instructions.minst.minstruction.MInstruction.__count, and instructions.minst.minstruction.MInstruction.count.
Member Data Documentation
__count
instructions.minst.minstruction.MInstruction.__count private
Definition at line 39 of file minstruction.py.
Referenced by instructions.minst.minstruction.MInstruction.count().
__minst_count
instructions.minst.minstruction.MInstruction.__minst_count static private
Definition at line 19 of file minstruction.py.
Property Documentation
count
instructions.minst.minstruction.MInstruction.count = property static
Returns the MInstruction counter value for this instruction.
This value monotonically increases per MInstruction created.
Returns: int: The counter value for this MInstruction.
Definition at line 50 of file minstruction.py.
Referenced by instructions.minst.minstruction.MInstruction.count().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/instructions/minst/minstruction.py