Encrypted Computing SDK: PISAProgramRuntime< T > Class Template Reference
PISAProgramRuntime< T > Class Template Reference
The PISAProgramRuntime class provides an interface to a PISA Functional model with functions for setting and getting memory and scheduling p-isa instruction execution.
#include <pisaprogramruntime.h>
Public Member Functions
PISAProgramRuntime ()=default
std::vector< T > getModulusChain ()
std::pair< std::string, std::vector< T > > getParamMemoryFromMultiRegisterDeviceMemory (std::string memory_2_param_root)
get2ParamMemoryFromDeviceMemory takes a string of form label_ringsize_RNS and returns a pair with all of the device terms reassembled.
void getMemory (std::vector< std::pair< std::string, pisa::MultiRegister< T >>> &memory_locations)
void setModulusChain (std::vector< T > modulus_chain)
void setMemory (std::vector< std::pair< std::string, pisa::MultiRegister< T >>> memory_values)
void setMemory (std::pair< std::string, pisa::MultiRegister< T >> memory_value)
void setParamMemoryToMultiRegisterDeviceMemory (std::pair< std::string, std::vector< T >> trace_memory_map)
set2ParamMemoryToDeviceMemory takes a pair containing a memory address in 2 parameter form label_ringsize_RNS and maps it to device memory in label_ringsize_RNS_slice format.
void setParamMemoryToMultiRegisterDeviceMemory (std::vector< std::pair< std::string, std::vector< T >>> trace_memory_map)
void setImmediateToMultiRegisterDeviceMemory (std::pair< std::string, std::vector< T >> trace_memory_map)
void setImmediatesToMultiRegisterDeviceMemory (std::vector< std::pair< std::string, std::vector< T >>> trace_memory_map)
void setNTTTwiddleFactors (std::vector< std::vector< T >> ntt_tw)
void setINTTTwiddleFactors (pisa::TwiddleMap< T > intt_tw)
void executeProgram (const std::vector< pisa::PISAInstruction * > &instructions)
void executeProgram (std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction >>> input_layers)
void executeInstruction (pisa::PISAInstruction *instruction)
const pisa::PISAFunctionalModel< T > & model () const
void setModel (const pisa::PISAFunctionalModel< T > &newModel)
bool getDebugMode () const
void setDebugMode (bool newDebug_information_enabled)
void dumpDeviceMemory (std::ostream &output_stream)
void dumpDeviceMemory (std::ostream &output_stream, std::vector< std::string > addresses)
void setDeviceMemory (std::istream &input_stream)
Private Attributes
pisa::PISAFunctionalModel< T > m_model
bool m_debug_mode = false
Detailed Description
template<typename T>
class PISAProgramRuntime< T >
The PISAProgramRuntime class provides an interface to a PISA Functional model with functions for setting and getting memory and scheduling p-isa instruction execution.
Definition at line 20 of file pisaprogramruntime.h.
Constructor & Destructor Documentation
PISAProgramRuntime()
template<typename T > PISAProgramRuntime< T >::PISAProgramRuntime () default
Member Function Documentation
dumpDeviceMemory() [1/2]
template<typename T > void PISAProgramRuntime< T >::dumpDeviceMemory (std::ostream & output_stream)
Definition at line 326 of file pisaprogramruntime.h.
dumpDeviceMemory() [2/2]
template<typename T > void PISAProgramRuntime< T >::dumpDeviceMemory (std::ostream & output_stream, std::vector< std::string > addresses)
Definition at line 332 of file pisaprogramruntime.h.
executeInstruction()
template<typename T > void PISAProgramRuntime< T >::executeInstruction (pisa::PISAInstruction * instruction)
Definition at line 141 of file pisaprogramruntime.h.
executeProgram() [1/2]
template<typename T > void PISAProgramRuntime< T >::executeProgram (const std::vector< pisa::PISAInstruction * > & instructions)
Definition at line 80 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
executeProgram() [2/2]
template<typename T > void PISAProgramRuntime< T >::executeProgram (std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction >>> input_layers)
Definition at line 128 of file pisaprogramruntime.h.
getDebugMode()
template<typename T > bool PISAProgramRuntime< T >::getDebugMode
Definition at line 314 of file pisaprogramruntime.h.
getMemory()
template<typename T > void PISAProgramRuntime< T >::getMemory (std::vector< std::pair< std::string, pisa::MultiRegister< T >>> & memory_locations)
Definition at line 275 of file pisaprogramruntime.h.
getModulusChain()
template<typename T > std::vector< T > PISAProgramRuntime< T >::getModulusChain
Definition at line 74 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
getParamMemoryFromMultiRegisterDeviceMemory()
template<typename T > std::pair< std::string, std::vector< T > > PISAProgramRuntime< T >::getParamMemoryFromMultiRegisterDeviceMemory (std::string memory_2_param_root)
get2ParamMemoryFromDeviceMemory takes a string of form label_ringsize_RNS and returns a pair with all of the device terms reassembled.
Parameters
memory_2_param_root
Returns
Definition at line 234 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
model()
template<typename T > const pisa::PISAFunctionalModel< T > & PISAProgramRuntime< T >::model
Definition at line 302 of file pisaprogramruntime.h.
setDebugMode()
template<typename T > void PISAProgramRuntime< T >::setDebugMode (bool newDebug_information_enabled)
Definition at line 320 of file pisaprogramruntime.h.
setDeviceMemory()
template<typename T > void PISAProgramRuntime< T >::setDeviceMemory (std::istream & input_stream)
Definition at line 338 of file pisaprogramruntime.h.
setImmediatesToMultiRegisterDeviceMemory()
template<typename T > void PISAProgramRuntime< T >::setImmediatesToMultiRegisterDeviceMemory (std::vector< std::pair< std::string, std::vector< T >>> trace_memory_map)
Definition at line 225 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
setImmediateToMultiRegisterDeviceMemory()
template<typename T > void PISAProgramRuntime< T >::setImmediateToMultiRegisterDeviceMemory (std::pair< std::string, std::vector< T >> trace_memory_map)
Definition at line 206 of file pisaprogramruntime.h.
setINTTTwiddleFactors()
template<typename T > void PISAProgramRuntime< T >::setINTTTwiddleFactors (pisa::TwiddleMap< T > intt_tw)
Definition at line 296 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
setMemory() [1/2]
template<typename T > void PISAProgramRuntime< T >::setMemory (std::pair< std::string, pisa::MultiRegister< T >> memory_value)
Definition at line 156 of file pisaprogramruntime.h.
setMemory() [2/2]
template<typename T > void PISAProgramRuntime< T >::setMemory (std::vector< std::pair< std::string, pisa::MultiRegister< T >>> memory_values)
Definition at line 147 of file pisaprogramruntime.h.
setModel()
template<typename T > void PISAProgramRuntime< T >::setModel (const pisa::PISAFunctionalModel< T > & newModel)
Definition at line 308 of file pisaprogramruntime.h.
setModulusChain()
template<typename T > void PISAProgramRuntime< T >::setModulusChain (std::vector< T > modulus_chain)
Definition at line 284 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
setNTTTwiddleFactors()
template<typename T > void PISAProgramRuntime< T >::setNTTTwiddleFactors (std::vector< std::vector< T >> ntt_tw)
Definition at line 290 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
setParamMemoryToMultiRegisterDeviceMemory() [1/2]
template<typename T > void PISAProgramRuntime< T >::setParamMemoryToMultiRegisterDeviceMemory (std::pair< std::string, std::vector< T >> trace_memory_map)
set2ParamMemoryToDeviceMemory takes a pair containing a memory address in 2 parameter form label_ringsize_RNS and maps it to device memory in label_ringsize_RNS_slice format.
Parameters
trace_memory_map
Definition at line 162 of file pisaprogramruntime.h.
Referenced by PisaTestGenerator::populateCalculatedOutputResults().
setParamMemoryToMultiRegisterDeviceMemory() [2/2]
template<typename T > void PISAProgramRuntime< T >::setParamMemoryToMultiRegisterDeviceMemory (std::vector< std::pair< std::string, std::vector< T >>> trace_memory_map)
Definition at line 190 of file pisaprogramruntime.h.
Member Data Documentation
m_debug_mode
template<typename T > bool PISAProgramRuntime< T >::m_debug_mode = false private
Definition at line 69 of file pisaprogramruntime.h.
m_model
template<typename T > pisa::PISAFunctionalModel<T> PISAProgramRuntime< T >::m_model private
Definition at line 68 of file pisaprogramruntime.h.
The documentation for this class was generated from the following file:
p-isa_tools/functional_modeler/pisa_runtime/pisaprogramruntime.h