Encrypted Computing SDK: pisa::poly::PolyOperation Class Reference
pisa::poly::PolyOperation Class Reference
The PolyOperation class represents a polynomial operation involving 1 or more input polynomial objects.
#include <polyprogram.h>
Public Member Functions
PolyOperation ()
PolyOperation (const PolyOperationDesc &desc)
template<class Iterator >
PolyOperation (const PolyOperationDesc &desc, Iterator start, Iterator end, std::shared_ptr< pisa::poly::PolyProgram > parent)
virtual std::shared_ptr< PolyOperation > create ()
std::string outLabel ()
void addInput (std::string arg, int poly_num, int rns_num)
void addOutput (std::string arg, int poly_num, int rns_num)
int numInputOperands () const
int numOutputOperands () const
Polynomial getInputOperand (int x) const
Polynomial getOutputOperand (int x) const
const OperationDesc & description () const
void setDescription (const OperationDesc &newDescription)
const std::string & Name () const
void setOperationName (const std::string &newOperation_name)
int getCipherDegree () const
void setCipherDegree (int newCipher_degree)
int getRnsTerms () const
void setRnsTerms (int newRns_terms)
int getGaloisElt () const
void setGaloisElt (int newGalois_elt)
uint32_t getFactor () const
void setFactor (uint32_t newFactor)
const std::pair< std::string, ValueType > getParam (std::string key) const
const std::pair< std::string, ValueType > getParam (int component_index) const
const std::string getParamKey (int component_index) const
void setParam (std::pair< std::string, std::pair< std::string, ValueType >> param)
std::shared_ptr< PolyProgram > parentProgram () const
void setParentProgram (std::shared_ptr< PolyProgram > newParent_program)
const std::vector< Polynomial > & getInputLocations () const
const std::vector< Polynomial > & getOutputLocations () const
Static Public Member Functions
static std::string baseName ()
static std::shared_ptr< PolyOperation > create (PolyOperationDesc desc)
static std::shared_ptr< PolyOperation > create (PolyOperationDesc desc, std::initializer_list< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent)
static std::shared_ptr< PolyOperation > create (PolyOperationDesc desc, std::vector< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent)
Protected Member Functions
std::map< std::string, std::pair< std::string, ValueType > > & getParams ()
void setParams (const std::map< std::string, std::pair< std::string, ValueType >> &newParams)
Protected Attributes
int rns_terms
int cipher_degree
int galois_elt
uint32_t factor
std::string operation_name
std::vector< Polynomial > input_locations
std::vector< Polynomial > output_locations
std::map< std::string, std::pair< std::string, ValueType > > params
std::map< int, std::string > param_index_lookup
OperationDesc m_description
std::shared_ptr< PolyProgram > m_parent_program = std::make_shared<PolyProgram>(default_global_poly_program)
Detailed Description
The PolyOperation class represents a polynomial operation involving 1 or more input polynomial objects.
Definition at line 103 of file polyprogram.h.
Constructor & Destructor Documentation
PolyOperation() [1/3]
pisa::poly::PolyOperation::PolyOperation ()
Definition at line 106 of file polyprogram.h.
PolyOperation() [2/3]
pisa::poly::PolyOperation::PolyOperation (const PolyOperationDesc & desc)
Definition at line 107 of file polyprogram.h.
References pisa::poly::PolyOperationDesc::desc, m_description, pisa::poly::PolyOperationDesc::name, and operation_name.
PolyOperation() [3/3]
template<class Iterator > pisa::poly::PolyOperation::PolyOperation (const PolyOperationDesc & desc, Iterator start, Iterator end, std::shared_ptr< pisa::poly::PolyProgram > parent)
Definition at line 113 of file polyprogram.h.
References addInput(), addOutput(), pisa::poly::ALPHA, pisa::poly::CIPHER_DEGREE, pisa::poly::Polynomial::decomposePolyStringForm(), pisa::poly::PolyOperationDesc::desc, pisa::poly::DNUM, pisa::poly::FACTOR, pisa::poly::FHE_SCHEME, pisa::poly::PolyOperationDesc::force_desc_op_name, fromString(), pisa::poly::GALOIS_ELT, pisa::poly::INPUT_ARGUMENT, pisa::poly::INPUT_OUTPUT_ARGUMENT, pisa::poly::KEY_RNS, m_description, m_parent_program, pisa::poly::PolyOperationDesc::name, pisa::poly::OP_NAME, operation_name, pisa::poly::OUTPUT_ARGUMENT, pisa::poly::PARAM, pisa::poly::OperationDesc::params, pisa::poly::POLYMOD_DEG_LOG2, pisa::poly::QSIZE, pisa::poly::RNS_TERM, setCipherDegree(), setFactor(), setGaloisElt(), setOperationName(), setParentProgram(), and setRnsTerms().
Member Function Documentation
addInput()
void pisa::poly::PolyOperation::addInput (std::string arg, int poly_num, int rns_num)
Definition at line 177 of file polyprogram.cpp.
References input_locations.
Referenced by PolyOperation().
addOutput()
void pisa::poly::PolyOperation::addOutput (std::string arg, int poly_num, int rns_num)
Definition at line 183 of file polyprogram.cpp.
References output_locations.
Referenced by PolyOperation().
baseName()
static std::string pisa::poly::PolyOperation::baseName () static
Definition at line 183 of file polyprogram.h.
create() [1/4]
virtual std::shared_ptr<PolyOperation> pisa::poly::PolyOperation::create () virtual
Definition at line 185 of file polyprogram.h.
Referenced by pisa::poly::library::createPolyOperation().
create() [2/4]
static std::shared_ptr<PolyOperation> pisa::poly::PolyOperation::create (PolyOperationDesc desc) static
Definition at line 186 of file polyprogram.h.
create() [3/4]
static std::shared_ptr<PolyOperation> pisa::poly::PolyOperation::create (PolyOperationDesc desc, std::initializer_list< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent) static
Definition at line 188 of file polyprogram.h.
References deadlock_test::args, pisa::poly::PolyOperationDesc::desc, pisa::poly::PolyOperationDesc::name, and pisa::poly::OperationDesc::params.
create() [4/4]
static std::shared_ptr<PolyOperation> pisa::poly::PolyOperation::create (PolyOperationDesc desc, std::vector< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent) static
Definition at line 201 of file polyprogram.h.
References deadlock_test::args, pisa::poly::PolyOperationDesc::desc, pisa::poly::PolyOperationDesc::name, and pisa::poly::OperationDesc::params.
description()
const OperationDesc & pisa::poly::PolyOperation::description () const
Definition at line 188 of file polyprogram.cpp.
References m_description.
getCipherDegree()
int pisa::poly::PolyOperation::getCipherDegree () const
Definition at line 42 of file polyprogram.cpp.
References input_locations.
Referenced by pisa::kernel::PISAKernel::createHECDataFormats().
getFactor()
uint32_t pisa::poly::PolyOperation::getFactor () const
Definition at line 150 of file polyprogram.cpp.
References params.
getGaloisElt()
int pisa::poly::PolyOperation::getGaloisElt () const
Definition at line 72 of file polyprogram.cpp.
References params.
Referenced by pisa::kernel::PISAKernel::createHECDataFormats().
getInputLocations()
const std::vector< Polynomial > & pisa::poly::PolyOperation::getInputLocations () const
Definition at line 321 of file polyprogram.cpp.
References input_locations.
Referenced by createKernelFilepath(), and genKernInput().
getInputOperand()
Polynomial pisa::poly::PolyOperation::getInputOperand (int x) const
Definition at line 220 of file polyprogram.h.
References input_locations.
Referenced by pisa::kernel::PISAKernel::create_legacy(), and genKernInput().
getOutputLocations()
const std::vector< Polynomial > & pisa::poly::PolyOperation::getOutputLocations () const
Definition at line 316 of file polyprogram.cpp.
References output_locations.
Referenced by genKernInput().
getOutputOperand()
Polynomial pisa::poly::PolyOperation::getOutputOperand (int x) const
Definition at line 221 of file polyprogram.h.
References output_locations.
getParam() [1/2]
const std::pair< std::string, ValueType > pisa::poly::PolyOperation::getParam (int component_index) const
Definition at line 258 of file polyprogram.cpp.
References param_index_lookup, and params.
getParam() [2/2]
const std::pair< std::string, ValueType > pisa::poly::PolyOperation::getParam (std::string key) const
Definition at line 253 of file polyprogram.cpp.
References params.
getParamKey()
const std::string pisa::poly::PolyOperation::getParamKey (int component_index) const
Definition at line 277 of file polyprogram.cpp.
References param_index_lookup.
getParams()
std::map< std::string, std::pair< std::string, ValueType > > & pisa::poly::PolyOperation::getParams () protected
Definition at line 306 of file polyprogram.cpp.
References params.
getRnsTerms()
int pisa::poly::PolyOperation::getRnsTerms () const
Definition at line 52 of file polyprogram.cpp.
References input_locations.
Referenced by pisa::kernel::PISAKernel::createHECDataFormats().
Name()
const std::string & pisa::poly::PolyOperation::Name () const
Definition at line 32 of file polyprogram.cpp.
References params.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::create_new(), pisa::kernel::PISAKernel::createHECDataFormats(), createKernelFilepath(), and genKernInput().
numInputOperands()
int pisa::poly::PolyOperation::numInputOperands () const
Definition at line 218 of file polyprogram.h.
References input_locations.
Referenced by genKernInput().
numOutputOperands()
int pisa::poly::PolyOperation::numOutputOperands () const
Definition at line 219 of file polyprogram.h.
References output_locations.
Referenced by genKernInput().
outLabel()
std::string pisa::poly::PolyOperation::outLabel ()
Definition at line 214 of file polyprogram.h.
parentProgram()
std::shared_ptr< PolyProgram > pisa::poly::PolyOperation::parentProgram () const
Definition at line 326 of file polyprogram.cpp.
References m_parent_program.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::createHECDataFormats(), createKernelFilepath(), and genKernInput().
setCipherDegree()
void pisa::poly::PolyOperation::setCipherDegree (int newCipher_degree)
Definition at line 47 of file polyprogram.cpp.
References params, and pisa::poly::UINT32.
Referenced by PolyOperation().
setDescription()
void pisa::poly::PolyOperation::setDescription (const OperationDesc & newDescription)
Definition at line 193 of file polyprogram.cpp.
References m_description.
setFactor()
void pisa::poly::PolyOperation::setFactor (uint32_t newFactor)
Definition at line 162 of file polyprogram.cpp.
References params, and pisa::poly::UINT32.
Referenced by PolyOperation().
setGaloisElt()
void pisa::poly::PolyOperation::setGaloisElt (int newGalois_elt)
Definition at line 84 of file polyprogram.cpp.
References params, and pisa::poly::UINT32.
Referenced by PolyOperation().
setOperationName()
void pisa::poly::PolyOperation::setOperationName (const std::string & newOperation_name)
Definition at line 37 of file polyprogram.cpp.
References params, and pisa::poly::STRING.
Referenced by PolyOperation().
setParam()
void pisa::poly::PolyOperation::setParam (std::pair< std::string, std::pair< std::string, ValueType >> param)
Definition at line 295 of file polyprogram.cpp.
References param_index_lookup, and params.
setParams()
void pisa::poly::PolyOperation::setParams (const std::map< std::string, std::pair< std::string, ValueType >> & newParams) protected
Definition at line 311 of file polyprogram.cpp.
References params.
setParentProgram()
void pisa::poly::PolyOperation::setParentProgram (std::shared_ptr< PolyProgram > newParent_program)
Definition at line 331 of file polyprogram.cpp.
References m_parent_program.
Referenced by PolyOperation().
setRnsTerms()
void pisa::poly::PolyOperation::setRnsTerms (int newRns_terms)
Definition at line 57 of file polyprogram.cpp.
References params, and pisa::poly::UINT32.
Referenced by PolyOperation().
Member Data Documentation
cipher_degree
int pisa::poly::PolyOperation::cipher_degree protected
Definition at line 260 of file polyprogram.h.
factor
uint32_t pisa::poly::PolyOperation::factor protected
Definition at line 262 of file polyprogram.h.
galois_elt
int pisa::poly::PolyOperation::galois_elt protected
Definition at line 261 of file polyprogram.h.
input_locations
std::vector<Polynomial> pisa::poly::PolyOperation::input_locations protected
Definition at line 265 of file polyprogram.h.
Referenced by addInput(), getCipherDegree(), getInputLocations(), getInputOperand(), getRnsTerms(), and numInputOperands().
m_description
OperationDesc pisa::poly::PolyOperation::m_description protected
Definition at line 269 of file polyprogram.h.
Referenced by description(), PolyOperation(), and setDescription().
m_parent_program
std::shared_ptr<PolyProgram> pisa::poly::PolyOperation::m_parent_program = std::make_shared<PolyProgram>(default_global_poly_program) protected
Definition at line 270 of file polyprogram.h.
Referenced by parentProgram(), PolyOperation(), and setParentProgram().
operation_name
std::string pisa::poly::PolyOperation::operation_name protected
Definition at line 264 of file polyprogram.h.
Referenced by PolyOperation().
output_locations
std::vector<Polynomial> pisa::poly::PolyOperation::output_locations protected
Definition at line 266 of file polyprogram.h.
Referenced by addOutput(), getOutputLocations(), getOutputOperand(), and numOutputOperands().
param_index_lookup
std::map<int, std::string> pisa::poly::PolyOperation::param_index_lookup protected
Definition at line 268 of file polyprogram.h.
Referenced by getParam(), getParamKey(), and setParam().
params
std::map<std::string, std::pair<std::string, ValueType> > pisa::poly::PolyOperation::params protected
Definition at line 267 of file polyprogram.h.
Referenced by getFactor(), getGaloisElt(), getParam(), getParams(), Name(), setCipherDegree(), setFactor(), setGaloisElt(), setOperationName(), setParam(), setParams(), and setRnsTerms().
rns_terms
int pisa::poly::PolyOperation::rns_terms protected
Definition at line 259 of file polyprogram.h.
The documentation for this class was generated from the following files:
p-isa_tools/program_mapper/poly_program/polyprogram.h
p-isa_tools/program_mapper/poly_program/polyprogram.cpp