Encrypted Computing SDK: pisa::performance::PISAPerformanceModeler Class Reference
pisa::performance::PISAPerformanceModeler Class Reference
#include <p_isa_performance_modeler.h>
Public Member Functions
PISAPerformanceModeler ()
void addGraphAnalysis (PerformanceReport &report)
void createMemoryGraph (graph::Graph< pisa::PISAInstruction > &graph)
void createInstructionGraph (graph::Graph< pisa::PISAInstruction > &graph)
void updateInstructionsToUniqueIntermediateRegisters ()
void updateInstructionsToUniqueIntermediateRegistersNew ()
void generateAndPrintPerformanceReport (PerformanceModels::PISAHardwareModel model=pisa::PerformanceModels::ExampleHardware())
void generatePerformanceReport (pisa::PerformanceModels::PISAHardwareModel hardware_model)
PerformanceReport generateInstructionAndMemoryPerformanceGraphReport (ScheduleConfig config, pisa::PerformanceModels::PISAHardwareModel hardware_model)
void generatePerformanceReportGraph ()
pisa::PerformanceModels::InstructionPerfCharacteristics getMemoryPerformance (graph::NetworkNode< pisa::PISAInstruction > &mem, int current_clock, pisa::PerformanceModels::PISAHardwareModel hardware_model)
void setInstructionStream (std::vector< pisa::PISAInstruction * > instructions)
Private Attributes
pisa::PerformanceModels::PISAHardwareModel m_hardware_model
std::map< std::string, uint > m_instruction_instance_count
std::vector< pisa::PISAInstruction * > m_instructions
Detailed Description
Definition at line 94 of file p_isa_performance_modeler.h.
Constructor & Destructor Documentation
PISAPerformanceModeler()
PISAPerformanceModeler::PISAPerformanceModeler ()
Definition at line 8 of file p_isa_performance_modeler.cpp.
Member Function Documentation
addGraphAnalysis()
void PISAPerformanceModeler::addGraphAnalysis (PerformanceReport & report)
Definition at line 12 of file p_isa_performance_modeler.cpp.
References graph::Graph< INSTRUCTION >::createGraph(), createInstructionGraph(), pisa::performance::PerformanceReport::graph_average_width, pisa::performance::PerformanceReport::graph_depth, pisa::performance::PerformanceReport::graph_max_width, pisa::performance::PerformanceReport::graph_min_width, m_instructions, pisa::performance::PerformanceReport::total_inputs, and pisa::performance::PerformanceReport::total_outputs.
Referenced by generateAndPrintPerformanceReport().
createInstructionGraph()
void PISAPerformanceModeler::createInstructionGraph (graph::Graph< pisa::PISAInstruction > & graph)
Definition at line 58 of file p_isa_performance_modeler.cpp.
References graph::OPERATION.
Referenced by addGraphAnalysis(), and generateInstructionAndMemoryPerformanceGraphReport().
createMemoryGraph()
void PISAPerformanceModeler::createMemoryGraph (graph::Graph< pisa::PISAInstruction > & graph)
Definition at line 46 of file p_isa_performance_modeler.cpp.
References graph::OPERATION.
Referenced by generateInstructionAndMemoryPerformanceGraphReport().
generateAndPrintPerformanceReport()
void PISAPerformanceModeler::generateAndPrintPerformanceReport (PerformanceModels::PISAHardwareModel model = pisa::PerformanceModels::ExampleHardware())
Definition at line 308 of file p_isa_performance_modeler.cpp.
References addGraphAnalysis(), he_as::config, isolation_test::file, generateInstructionAndMemoryPerformanceGraphReport(), pisa::performance::PerformanceReport::instruction_count, m_instruction_instance_count, m_instructions, pisa::performance::PerformanceReport::outputInstructions(), pisa::performance::PerformanceReport::print(), pisa::performance::PerformanceReport::report_name, and updateInstructionsToUniqueIntermediateRegistersNew().
generateInstructionAndMemoryPerformanceGraphReport()
PerformanceReport PISAPerformanceModeler::generateInstructionAndMemoryPerformanceGraphReport (ScheduleConfig config, pisa::PerformanceModels::PISAHardwareModel hardware_model)
Definition at line 379 of file p_isa_performance_modeler.cpp.
References he_as::config, graph::Graph< INSTRUCTION >::createGraph(), createInstructionGraph(), createMemoryGraph(), getMemoryPerformance(), pisa::performance::instruction, pisa::PerformanceModels::PISAHardwareModel::ISAInstructionMemoryMap, pisa::PerformanceModels::PISAHardwareModel::ISAInstructionPerformanceMap, pisa::PerformanceModels::InstructionPerfCharacteristics::latency, m_instructions, pisa::performance::memory, graph::OPERATION, pisa::performance::random, pisa::performance::PerformanceReport::schedule_timeline_mem_queue, pisa::performance::PerformanceReport::schedule_timeline_operation, pisa::PerformanceModels::InstructionPerfCharacteristics::throughput, pisa::performance::PerformanceReport::total_cycles_used, and pisa::performance::PerformanceReport::total_nops_issued.
Referenced by generateAndPrintPerformanceReport().
generatePerformanceReport()
void PISAPerformanceModeler::generatePerformanceReport (pisa::PerformanceModels::PISAHardwareModel hardware_model)
Definition at line 368 of file p_isa_performance_modeler.cpp.
References pisa::PerformanceModels::PISAHardwareModel::ISAInstructionPerformanceMap, m_instructions, and pisa::performance::PerformanceReport::total_cycles_used.
generatePerformanceReportGraph()
void PISAPerformanceModeler::generatePerformanceReportGraph ()
Definition at line 567 of file p_isa_performance_modeler.cpp.
getMemoryPerformance()
pisa::PerformanceModels::InstructionPerfCharacteristics PISAPerformanceModeler::getMemoryPerformance (graph::NetworkNode< pisa::PISAInstruction > & mem, int current_clock, pisa::PerformanceModels::PISAHardwareModel hardware_model)
Definition at line 572 of file p_isa_performance_modeler.cpp.
References pisa::PerformanceModels::PISAHardwareModel::ISAInstructionMemoryMap, and pisa::PerformanceModels::PISAHardwareModel::MemorySizesMap.
Referenced by generateInstructionAndMemoryPerformanceGraphReport().
setInstructionStream()
void PISAPerformanceModeler::setInstructionStream (std::vector< pisa::PISAInstruction * > instructions)
Definition at line 598 of file p_isa_performance_modeler.cpp.
References m_instruction_instance_count, and m_instructions.
updateInstructionsToUniqueIntermediateRegisters()
void PISAPerformanceModeler::updateInstructionsToUniqueIntermediateRegisters ()
Definition at line 70 of file p_isa_performance_modeler.cpp.
References graph::Graph< INSTRUCTION >::createGraph(), pisa::performance::instruction, m_instructions, and graph::OPERATION.
updateInstructionsToUniqueIntermediateRegistersNew()
void PISAPerformanceModeler::updateInstructionsToUniqueIntermediateRegistersNew ()
Definition at line 132 of file p_isa_performance_modeler.cpp.
References graph::Graph< INSTRUCTION >::createGraph(), pisa::performance::instruction, m_instructions, isolation_test::name, graph::NAME, and graph::OPERATION.
Referenced by generateAndPrintPerformanceReport().
Member Data Documentation
m_hardware_model
pisa::PerformanceModels::PISAHardwareModel pisa::performance::PISAPerformanceModeler::m_hardware_model private
Definition at line 115 of file p_isa_performance_modeler.h.
m_instruction_instance_count
std::map<std::string, uint> pisa::performance::PISAPerformanceModeler::m_instruction_instance_count private
Definition at line 117 of file p_isa_performance_modeler.h.
Referenced by generateAndPrintPerformanceReport(), and setInstructionStream().
m_instructions
std::vector<pisa::PISAInstruction *> pisa::performance::PISAPerformanceModeler::m_instructions private
Definition at line 118 of file p_isa_performance_modeler.h.
Referenced by addGraphAnalysis(), generateAndPrintPerformanceReport(), generateInstructionAndMemoryPerformanceGraphReport(), generatePerformanceReport(), setInstructionStream(), updateInstructionsToUniqueIntermediateRegisters(), and updateInstructionsToUniqueIntermediateRegistersNew().
The documentation for this class was generated from the following files:
p-isa_tools/common/p_isa/p_isa_performance_modeler.h
p-isa_tools/common/p_isa/p_isa_performance_modeler.cpp