Encrypted Computing SDK: pisa::Operand Class Reference
pisa::Operand Class Reference
The Operand class represents an operand for a PISA instruction.
#include <p_isa_instruction.h>
Public Member Functions
Operand ()
Operand (const std::string &_location, bool _immediate)
Operand (const std::string &name, int bank)
Operand (const std::string &location_and_bank)
const std::string & location () const
void setLocation (const std::string &newLocation)
int bank () const
void setBank (int newBank)
bool immediate () const
void setImmediate (bool newImmediate)
const std::string & locationRoot () const
void setLocationRoot (const std::string &newLocation_root)
bool outputBank () const
void setOutputBank (bool newOutput_bank)
Static Private Member Functions
static std::pair< std::string, std::string > splitLocation (const std::string &location)
splitLocation
Private Attributes
std::string m_location_root
std::string m_location_index
std::string m_location
int m_bank
bool m_immediate
bool m_output_bank = true
Friends
std::ostream & operator<< (std::ostream &stream, const Operand &op)
Detailed Description
The Operand class represents an operand for a PISA instruction.
Definition at line 107 of file p_isa_instruction.h.
Constructor & Destructor Documentation
Operand() [1/4]
pisa::Operand::Operand ()
Definition at line 110 of file p_isa_instruction.h.
Operand() [2/4]
pisa::Operand::Operand (const std::string & _location, bool _immediate)
Definition at line 116 of file p_isa_instruction.h.
Operand() [3/4]
pisa::Operand::Operand (const std::string & name, int bank)
Definition at line 122 of file p_isa_instruction.h.
References isolation_test::name, and setLocation().
Operand() [4/4]
pisa::Operand::Operand (const std::string & location_and_bank)
Definition at line 129 of file p_isa_instruction.h.
References bank(), location(), m_bank, m_immediate, and setLocation().
Member Function Documentation
bank()
int pisa::Operand::bank () const
Definition at line 160 of file p_isa_instruction.h.
References m_bank.
Referenced by Operand().
immediate()
bool pisa::Operand::immediate () const
Definition at line 196 of file p_isa_instruction.cpp.
References m_immediate.
location()
const std::string& pisa::Operand::location () const
Definition at line 147 of file p_isa_instruction.h.
References m_location.
Referenced by pisa::PISAFunctionalModel< T >::addInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::copyInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::decode(), pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::maciInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::macInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::muliInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::mulInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute(), Operand(), splitLocation(), and pisa::PISAFunctionalModel< T >::subInstrDecodeExecute().
locationRoot()
const std::string & pisa::Operand::locationRoot () const
Definition at line 206 of file p_isa_instruction.cpp.
References m_location_root.
outputBank()
bool pisa::Operand::outputBank () const
Definition at line 217 of file p_isa_instruction.cpp.
References m_output_bank.
setBank()
void pisa::Operand::setBank (int newBank)
Definition at line 165 of file p_isa_instruction.h.
References m_bank.
setImmediate()
void pisa::Operand::setImmediate (bool newImmediate)
Definition at line 201 of file p_isa_instruction.cpp.
References m_immediate.
Referenced by pisa::instruction::Maci::Maci(), and pisa::instruction::Muli::Muli().
setLocation()
void pisa::Operand::setLocation (const std::string & newLocation)
Definition at line 152 of file p_isa_instruction.h.
References m_location, m_location_index, m_location_root, and splitLocation().
Referenced by Operand().
setLocationRoot()
void pisa::Operand::setLocationRoot (const std::string & newLocation_root)
Definition at line 211 of file p_isa_instruction.cpp.
References m_location, m_location_index, and m_location_root.
setOutputBank()
void pisa::Operand::setOutputBank (bool newOutput_bank)
Definition at line 222 of file p_isa_instruction.cpp.
References m_output_bank.
splitLocation()
static std::pair<std::string, std::string> pisa::Operand::splitLocation (const std::string & location) static private
splitLocation
Parameters
location Attempts to split the register name into a root and address portion. Does this by reversing V0 logic that always appends poly and rns terms to end of input/register names(but varies depending on if 1 or n outputs)
Definition at line 195 of file p_isa_instruction.h.
References location(), and order_test::reg_name.
Referenced by setLocation().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const Operand & op) friend
Definition at line 170 of file p_isa_instruction.h.
Member Data Documentation
m_bank
int pisa::Operand::m_bank private
Definition at line 216 of file p_isa_instruction.h.
Referenced by bank(), Operand(), and setBank().
m_immediate
bool pisa::Operand::m_immediate private
Definition at line 217 of file p_isa_instruction.h.
Referenced by immediate(), Operand(), and setImmediate().
m_location
std::string pisa::Operand::m_location private
Definition at line 215 of file p_isa_instruction.h.
Referenced by location(), setLocation(), and setLocationRoot().
m_location_index
std::string pisa::Operand::m_location_index private
Definition at line 214 of file p_isa_instruction.h.
Referenced by setLocation(), and setLocationRoot().
m_location_root
std::string pisa::Operand::m_location_root private
Definition at line 213 of file p_isa_instruction.h.
Referenced by locationRoot(), setLocation(), and setLocationRoot().
m_output_bank
bool pisa::Operand::m_output_bank = true private
Definition at line 218 of file p_isa_instruction.h.
Referenced by outputBank(), and setOutputBank().
The documentation for this class was generated from the following files:
p-isa_tools/common/p_isa/p_isa_instruction.h
p-isa_tools/common/p_isa/p_isa_instruction.cpp