Encrypted Computing SDK: pisa::ProgramMapper< T > Class Template Reference
pisa::ProgramMapper< T > Class Template Reference
#include <program_mapper.h>
Public Member Functions
ProgramMapper ()
void generatePisaProgramFromHEProgram (std::shared_ptr< pisa::poly::PolyProgram > program_trace)
std::vector< pisa::kernel::PISAKernel * > generatePISAKernelsFromHEOperationVector (std::vector< std::shared_ptr< pisa::poly::PolyOperation >> operations, std::string kerngen_loc, int &max_rns_terms)
void mapKernelInputOutputToRegisterMap (std::vector< kernel::PISAKernel * > &p_isa_kernels, const std::vector< std::shared_ptr< pisa::poly::PolyOperation >> &program_trace, std::map< std::string, std::string > &register_map, std::vector< std::pair< std::string, std::vector< T >>> immediates=std::vector< std::pair< std::string, std::vector< T >>>())
std::map< std::string, std::string > mapProgramTraceOperationsIntoRegisterMap (std::vector< std::shared_ptr< pisa::poly::PolyOperation >> program_trace, std::map< std::string, std::string > register_map=std::map< std::string, std::string >())
std::vector< pisa::PISAInstruction * > outputCombinedPisaInstructions (std::vector< kernel::PISAKernel * > p_isa_kernels, bool apply_namespacing)
const ProgramMapperArguments & getArguments () const
void setArguments (const ProgramMapperArguments &newArguments)
Public Attributes
ProgramMapperArguments arguments
Detailed Description
template<typename T>
class pisa::ProgramMapper< T >
Definition at line 51 of file program_mapper.h.
Constructor & Destructor Documentation
ProgramMapper()
template<typename T > pisa::ProgramMapper< T >::ProgramMapper ()
Definition at line 54 of file program_mapper.h.
Member Function Documentation
generatePISAKernelsFromHEOperationVector()
template<typename T > std::vector< kernel::PISAKernel * > pisa::ProgramMapper< T >::generatePISAKernelsFromHEOperationVector (std::vector< std::shared_ptr< pisa::poly::PolyOperation >> operations, std::string kerngen_loc, int & max_rns_terms)
Definition at line 135 of file program_mapper.cpp.
generatePisaProgramFromHEProgram()
template<typename T > void pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram (std::shared_ptr< pisa::poly::PolyProgram > program_trace)
Definition at line 9 of file program_mapper.cpp.
References PISAGraphOptimizer::applyDuplicateInputVariableSeparation(), graph::Graph< INSTRUCTION >::createGraph(), PISAGraphOptimizer::generateInstructionStreamFromGraph(), PisaTestGenerator::generateJSONForGraph(), generateMemFile(), isolation_test::line, graph::NAME, PisaTestGenerator::populateCalculatedOutputResults(), order_test::register_map, PisaTestGenerator::writeJSON(), and writeToFileBy().
Referenced by main().
getArguments()
template<typename T > const ProgramMapperArguments & pisa::ProgramMapper< T >::getArguments
Definition at line 241 of file program_mapper.cpp.
mapKernelInputOutputToRegisterMap()
template<typename T > void pisa::ProgramMapper< T >::mapKernelInputOutputToRegisterMap (std::vector< kernel::PISAKernel * > & p_isa_kernels, const std::vector< std::shared_ptr< pisa::poly::PolyOperation >> & program_trace, std::map< std::string, std::string > & register_map, std::vector< std::pair< std::string, std::vector< T >>> immediates = std::vector<std::pair<std::string, std::vector<T>>>())
Definition at line 167 of file program_mapper.cpp.
References isolation_test::name, and order_test::register_map.
mapProgramTraceOperationsIntoRegisterMap()
template<typename T > std::map< std::string, std::string > pisa::ProgramMapper< T >::mapProgramTraceOperationsIntoRegisterMap (std::vector< std::shared_ptr< pisa::poly::PolyOperation >> program_trace, std::map< std::string, std::string > register_map = std::map<std::string, std::string>())
Definition at line 197 of file program_mapper.cpp.
References order_test::register_map.
outputCombinedPisaInstructions()
template<typename T > std::vector< PISAInstruction * > pisa::ProgramMapper< T >::outputCombinedPisaInstructions (std::vector< kernel::PISAKernel * > p_isa_kernels, bool apply_namespacing)
Definition at line 227 of file program_mapper.cpp.
setArguments()
template<typename T > void pisa::ProgramMapper< T >::setArguments (const ProgramMapperArguments & newArguments)
Definition at line 247 of file program_mapper.cpp.
Referenced by main().
Member Data Documentation
arguments
template<typename T > ProgramMapperArguments pisa::ProgramMapper< T >::arguments
Definition at line 74 of file program_mapper.h.
The documentation for this class was generated from the following files:
p-isa_tools/program_mapper/program_mapper.h
p-isa_tools/program_mapper/program_mapper.cpp