Encrypted Computing SDK: linker.instructions.minst.mload.Instruction Class Reference
linker.instructions.minst.mload.Instruction Class Reference
Encapsulates an mload MInstruction.
Public Member Functions
def __init__ (self, list tokens, str comment="")
Constructs a new mload MInstruction.
Public Member Functions inherited from linker.instructions.minst.minstruction.MInstruction
str to_line (self)
Retrieves the string form of the instruction to write to the instruction file.
Public Member Functions inherited from linker.instructions.instruction.BaseInstruction
str name (cls)
Name for the instruction.
int NAME_TOKEN_INDEX (cls)
Index for the token containing the name of the instruction in the list of tokens.
int NUM_TOKENS (cls)
Number of tokens required for this instruction.
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __str__ (self)
Properties
source = property
Gets the name of the source.
Properties inherited from linker.instructions.instruction.BaseInstruction
id = property
Unique ID for the instruction.
tokens = property
Gets the list of tokens for the instruction.
Private Member Functions
int _get_num_tokens (cls)
str _get_name (cls)
str source (self)
def source (self, str value)
Additional Inherited Members
Public Attributes inherited from linker.instructions.instruction.BaseInstruction
comment
Detailed Description
Encapsulates an mload MInstruction.
This instruction loads a single polynomial residue from local memory to scratchpad.
For more information, check the specification: https://github.com/IntelLabs/hec-assembler-tools/blob/master/docsrc/inst_spec/minst/minst_mload.md
Properties: source: Gets or sets the name of the source.
Definition at line 14 of file mload.py.
Constructor & Destructor Documentation
__init__()
def linker.instructions.minst.mload.Instruction.__init__ (self, list tokens, str comment = "")
Constructs a new mload MInstruction.
Args: tokens (list): A list of tokens representing the instruction. comment (str, optional): An optional comment for the instruction. Defaults to an empty string.
Raises: ValueError: If the number of tokens is invalid or the instruction name is incorrect.
Reimplemented from linker.instructions.minst.minstruction.MInstruction.
Definition at line 53 of file mload.py.
Member Function Documentation
_get_name()
str linker.instructions.minst.mload.Instruction._get_name (cls) private
   Gets the name of the instruction.
   Returns:
       str: The name of the instruction, which is "mload".
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 40 of file mload.py.
Referenced by instructions.instruction.BaseInstruction.name(), xinst.xinstruction.XInstruction.name(), and linker.instructions.instruction.BaseInstruction.name().
_get_num_tokens()
int linker.instructions.minst.mload.Instruction._get_num_tokens (cls) private
   Gets the number of tokens required for the instruction.
   The `mload` instruction requires 4 tokens:
   <line: uint>, mload, <dst: uint>, <src_var: str>
   Returns:
       int: The number of tokens, which is 4.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 28 of file mload.py.
Referenced by linker.instructions.instruction.BaseInstruction.NUM_TOKENS().
source() [1/2]
str linker.instructions.minst.mload.Instruction.source (self) private
Definition at line 67 of file mload.py.
References linker.instructions.minst.mload.Instruction.source, and linker.instructions.instruction.BaseInstruction.tokens.
source() [2/2]
def linker.instructions.minst.mload.Instruction.source (self, str value) private
   Sets the name of the source.
   Args:
       value (str): The name of the source to set.
Definition at line 78 of file mload.py.
References linker.instructions.minst.mload.Instruction.source, and linker.instructions.instruction.BaseInstruction.tokens.
Property Documentation
source
linker.instructions.minst.mload.Instruction.source = property static
Gets the name of the source.
This is a Variable name when loaded. Should be set to HBM address to write back.
Returns: str: The name of the source.
Definition at line 65 of file mload.py.
Referenced by linker.instructions.minst.mload.Instruction.source().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/linker/instructions/minst/mload.py