Encrypted Computing SDK: instructions.cinst.cinstruction.CInstruction Class Reference
instructions.cinst.cinstruction.CInstruction Class Reference
Represents a CInstruction, which is a type of BaseInstruction.
Public Member Functions
def __init__ (self, int id, int throughput, int latency, str comment="")
Constructs a new CInstruction.
Public Member Functions inherited from instructions.instruction.BaseInstruction
dict isa_spec_as_dict (cls)
Returns attributes as dictionary.
def SetNumDests (cls, val)
def SetNumSources (cls, val)
def SetDefaultThroughput (cls, val)
def SetDefaultLatency (cls, val)
str name (cls)
Name for the instruction.
str OP_NAME_PISA (cls)
P-ISA name for the instruction.
str OP_NAME_ASM (cls)
ASM-ISA name for instruction.
def __repr__ (self)
Returns a string representation of the BaseInstruction object.
def __eq__ (self, other)
Checks equality between two BaseInstruction objects.
def __hash__ (self)
Returns the hash of the BaseInstruction object.
def __str__ (self)
Returns a string representation of the BaseInstruction object.
def set_schedule_timing_index (self, int value)
Sets the schedule timing index.
def freeze (self)
Called immediately after _schedule() to freeze the instruction after scheduling to preserve the instruction string representation to output into the listing.
int schedule (self, CycleType cycle_count, int schedule_idx)
Schedules and freezes the instruction, simulating timings of executing this instruction.
str toStringFormat (self, preamble, str op_name, *extra_args)
Converts the instruction to a string format.
str toPISAFormat (self)
Converts the instruction to P-ISA kernel format.
str toXASMISAFormat (self)
Converts the instruction to ASM-ISA format.
str toCASMISAFormat (self)
Converts the instruction to CInst ASM-ISA format.
str toMASMISAFormat (self)
Converts the instruction to MInst ASM-ISA format.
Private Member Functions
def _get_cycle_ready (self)
str _toCASMISAFormat (self, *extra_args)
Additional Inherited Members
Public Attributes inherited from instructions.instruction.BaseInstruction
comment
Properties inherited from instructions.instruction.BaseInstruction
id = property
Gets the unique ID for the instruction.
schedule_timing = property
Retrieves the 1-based index for this instruction in its schedule listing, or less than 1 if not scheduled yet.
is_scheduled = property
Checks if the instruction is scheduled.
throughput = property
Gets the throughput of the instruction.
latency = property
Gets the latency of the instruction.
dests = property
Gets the list of destination objects.
sources = property
Gets the list of source objects.
Detailed Description
Represents a CInstruction, which is a type of BaseInstruction.
This class provides the basic structure and functionality for CInstructions, including methods for converting to CInst ASM-ISA format.
Attributes: id (int): User-defined ID for the instruction. throughput (int): The throughput of the instruction. latency (int): The latency of the instruction. comment (str): An optional comment for the instruction.
Definition at line 16 of file cinstruction.py.
Constructor & Destructor Documentation
__init__()
def instructions.cinst.cinstruction.CInstruction.__init__ (self, int id, int throughput, int latency, str comment = "")
Constructs a new CInstruction.
Parameters: id (int): User-defined ID for the instruction. It will be bundled with a nonce to form a unique ID. throughput (int): The throughput of the instruction. latency (int): The latency of the instruction. comment (str, optional): An optional comment for the instruction.
Reimplemented from instructions.instruction.BaseInstruction.
Reimplemented in instructions.cinst.kgstart.Instruction, and instructions.cinst.cexit.Instruction.
Definition at line 30 of file cinstruction.py.
Member Function Documentation
_get_cycle_ready()
def instructions.cinst.cinstruction.CInstruction._get_cycle_ready (self) private
   Returns the cycle ready value for the instruction.
   This method overrides the base method to provide a specific cycle ready value for CInstructions.
   Returns:
       CycleType: A CycleType object with bundle and cycle set to 0.
Reimplemented from instructions.instruction.BaseInstruction.
Definition at line 51 of file cinstruction.py.
Referenced by common.cycle_tracking.CycleTracker.cycle_ready().
_toCASMISAFormat()
str instructions.cinst.cinstruction.CInstruction._toCASMISAFormat (self, * extra_args) private
   Converts the instruction to CInst ASM-ISA format.
   This method constructs the ASM-ISA format string for the instruction by combining
   the instruction's sources and destinations with any additional arguments.
   Parameters:
       extra_args: Additional arguments for the conversion.
   Returns:
       str: The CInst ASM-ISA format string of the instruction.
Reimplemented from instructions.instruction.BaseInstruction.
Reimplemented in instructions.cinst.xinstfetch.Instruction, instructions.cinst.nload.Instruction, instructions.cinst.kgstart.Instruction, instructions.cinst.kgseed.Instruction, instructions.cinst.kgload.Instruction, instructions.cinst.ifetch.Instruction, instructions.cinst.csyncm.Instruction, instructions.cinst.cstore.Instruction, instructions.cinst.cnop.Instruction, instructions.cinst.cexit.Instruction, instructions.cinst.bones.Instruction, and instructions.cinst.bload.Instruction.
Definition at line 68 of file cinstruction.py.
References instructions.instruction.BaseInstruction.dests, instructions.instruction.BaseInstruction.OP_NAME_ASM(), instructions.instruction.BaseInstruction.sources, and instructions.instruction.BaseInstruction.toStringFormat().
Referenced by instructions.instruction.BaseInstruction.freeze(), and instructions.instruction.BaseInstruction.toCASMISAFormat().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/instructions/cinst/cinstruction.py