Encrypted Computing SDK: pisa::PISAParser Class Reference
pisa::PISAParser Class Reference
#include <p_isa_parser.h>
Public Member Functions
PISAParser ()=delete
Static Public Member Functions
static std::vector< PISAInstruction * > parse (const std::string &filename)
Static Private Member Functions
static PISAInstruction * parseInstruction (const std::vector< std::string > &components)
static void parseInstruction (const std::string &, pisa::PARAM_TYPE, pisa::PISAInstruction *instr)
static void parseComponent (const std::string &component, pisa::PARAM_TYPE type, pisa::PISAInstruction *instr)
static void parse_OP_NAME (const std::string &component, pisa::PISAInstruction *instr)
static void parse_INPUT_OPERAND (const std::string &component, pisa::PISAInstruction *instr)
static void parse_IMMEDIATE (const std::string &component, pisa::PISAInstruction *instr)
static void parse_OUTPUT_OPERAND (const std::string &component, pisa::PISAInstruction *instr)
static void parse_INPUT_OUTPUT_OPERAND (const std::string &component, pisa::PISAInstruction *instr)
static void parse_POLYMOD_DEG_LOG2 (const std::string &component, pisa::PISAInstruction *instr)
static void parse_RESIDUAL (const std::string &component, pisa::PISAInstruction *instr)
static void parse_ADDITIONAL_PARAMS (const std::string &component, pisa::PISAInstruction *instr)
static void parse_W_PARAM (const std::string &component, pisa::PISAInstruction *instr)
static void parse_GALOIS_ELEMENT (const std::string &component, pisa::PISAInstruction *instr)
static void parse_GROUP_ID (const std::string &component, pisa::PISAInstruction *instr)
static void parse_STAGE (const std::string &component, pisa::PISAInstruction *instr)
static void parse_BLOCK (const std::string &component, pisa::PISAInstruction *instr)
Static Private Attributes
static constexpr int OP_CODE_LOCATION = 1
Detailed Description
Definition at line 13 of file p_isa_parser.h.
Constructor & Destructor Documentation
PISAParser()
pisa::PISAParser::PISAParser () delete
Member Function Documentation
parse()
std::vector< pisa::PISAInstruction * > pisa::PISAParser::parse (const std::string & filename) static
Definition at line 13 of file p_isa_parser.cpp.
References isolation_test::file, and parseInstruction().
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::create_new(), pisa::kernel::PISAKernel::createHECDataFormats(), and main().
parse_ADDITIONAL_PARAMS()
void pisa::PISAParser::parse_ADDITIONAL_PARAMS (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 185 of file p_isa_parser.cpp.
parse_BLOCK()
void pisa::PISAParser::parse_BLOCK (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 180 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setBlock().
parse_GALOIS_ELEMENT()
void pisa::PISAParser::parse_GALOIS_ELEMENT (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 165 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setGalois_element().
parse_GROUP_ID()
void pisa::PISAParser::parse_GROUP_ID (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 170 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setGroupId().
parse_IMMEDIATE()
void pisa::PISAParser::parse_IMMEDIATE (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 137 of file p_isa_parser.cpp.
References pisa::PISAInstruction::addInputOperand(), and whiteSpaceRemoved().
parse_INPUT_OPERAND()
void pisa::PISAParser::parse_INPUT_OPERAND (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 132 of file p_isa_parser.cpp.
References pisa::PISAInstruction::addInputOperand().
parse_INPUT_OUTPUT_OPERAND()
void pisa::PISAParser::parse_INPUT_OUTPUT_OPERAND (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 148 of file p_isa_parser.cpp.
References pisa::PISAInstruction::addInputOperand(), and pisa::PISAInstruction::addOutputOperand().
parse_OP_NAME()
void pisa::PISAParser::parse_OP_NAME (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 127 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setName(), and whiteSpaceRemoved().
parse_OUTPUT_OPERAND()
void pisa::PISAParser::parse_OUTPUT_OPERAND (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 143 of file p_isa_parser.cpp.
References pisa::PISAInstruction::addOutputOperand().
parse_POLYMOD_DEG_LOG2()
void pisa::PISAParser::parse_POLYMOD_DEG_LOG2 (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 154 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setPMD().
parse_RESIDUAL()
void pisa::PISAParser::parse_RESIDUAL (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 159 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setResidual().
parse_STAGE()
void pisa::PISAParser::parse_STAGE (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 175 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setStage().
parse_W_PARAM()
void pisa::PISAParser::parse_W_PARAM (const std::string & component, pisa::PISAInstruction * instr) static private
Definition at line 190 of file p_isa_parser.cpp.
References pisa::PISAInstruction::setWParam().
parseComponent()
void pisa::PISAParser::parseComponent (const std::string & component, pisa::PARAM_TYPE type, pisa::PISAInstruction * instr) static private
Definition at line 79 of file p_isa_parser.cpp.
References pisa::ADDITIONAL_PARAMS, pisa::BLOCK, pisa::GALOIS_ELEMENT, pisa::GROUP_ID, pisa::IMMEDIATE, pisa::INPUT_OPERAND, pisa::INPUT_OUTPUT_OPERAND, pisa::OP_NAME, pisa::OUTPUT_OPERAND, pisa::POLYMOD_DEG_LOG2, pisa::RESIDUAL, pisa::STAGE, inject_bundles::type, and pisa::W_PACKED_PARAM.
parseInstruction() [1/2]
static void pisa::PISAParser::parseInstruction (const std::string & , pisa::PARAM_TYPE , pisa::PISAInstruction * instr) static private
parseInstruction() [2/2]
pisa::PISAInstruction * pisa::PISAParser::parseInstruction (const std::vector< std::string > & components) static private
Definition at line 51 of file p_isa_parser.cpp.
References pisa::PISAInstruction::create(), pisa::PISAInstruction::getDescription(), pisa::InstructionMap, pisa::InstructionDesc::params, and whiteSpaceRemoved().
Referenced by parse().
Member Data Documentation
OP_CODE_LOCATION
constexpr int pisa::PISAParser::OP_CODE_LOCATION = 1 static constexpr private
Definition at line 20 of file p_isa_parser.h.
The documentation for this class was generated from the following files:
p-isa_tools/common/p_isa/parser/p_isa_parser.h
p-isa_tools/common/p_isa/parser/p_isa_parser.cpp