Encrypted Computing SDK: linker.instructions.xinst.xinstruction.XInstruction Class Reference
linker.instructions.xinst.xinstruction.XInstruction Class Reference
Represents an XInstruction, inheriting from BaseInstruction.
Public Member Functions
def __init__ (self, list tokens, str comment="")
Constructs a new XInstruction.
Public Member Functions inherited from linker.instructions.instruction.BaseInstruction
str name (cls)
Name for the instruction.
int NAME_TOKEN_INDEX (cls)
Index for the token containing the name of the instruction in the list of tokens.
int NUM_TOKENS (cls)
Number of tokens required for this instruction.
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __str__ (self)
str to_line (self)
Retrieves the string form of the instruction to write to the instruction file.
Properties
bundle = property
Gets the bundle index.
Properties inherited from linker.instructions.instruction.BaseInstruction
id = property
Unique ID for the instruction.
tokens = property
Gets the list of tokens for the instruction.
Private Member Functions
int _get_name_token_index (cls)
int bundle (self)
def bundle (self, int value)
Additional Inherited Members
Public Attributes inherited from linker.instructions.instruction.BaseInstruction
comment
Detailed Description
Represents an XInstruction, inheriting from BaseInstruction.
Definition at line 7 of file xinstruction.py.
Constructor & Destructor Documentation
__init__()
def linker.instructions.xinst.xinstruction.XInstruction.__init__ (self, list tokens, str comment = "")
Constructs a new XInstruction.
Parameters: tokens (list): List of tokens for the instruction. comment (str): Optional comment for the instruction.
Raises: ValueError: If the number of tokens is invalid or the instruction name is incorrect.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Reimplemented in linker.instructions.xinst.xstore.Instruction, linker.instructions.xinst.twntt.Instruction, linker.instructions.xinst.twintt.Instruction, linker.instructions.xinst.sub.Instruction, linker.instructions.xinst.rshuffle.Instruction, linker.instructions.xinst.ntt.Instruction, linker.instructions.xinst.nop.Instruction, linker.instructions.xinst.muli.Instruction, linker.instructions.xinst.mul.Instruction, linker.instructions.xinst.move.Instruction, linker.instructions.xinst.maci.Instruction, linker.instructions.xinst.mac.Instruction, linker.instructions.xinst.intt.Instruction, linker.instructions.xinst.exit.Instruction, and linker.instructions.xinst.add.Instruction.
Definition at line 35 of file xinstruction.py.
Member Function Documentation
_get_name_token_index()
int linker.instructions.xinst.xinstruction.XInstruction._get_name_token_index (cls) private
   Gets the index of the token containing the name of the instruction.
   Returns:
       int: The index of the name token, which is 2.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 18 of file xinstruction.py.
Referenced by linker.instructions.instruction.BaseInstruction.NAME_TOKEN_INDEX().
bundle() [1/2]
int linker.instructions.xinst.xinstruction.XInstruction.bundle (self) private
Definition at line 50 of file xinstruction.py.
References linker.instructions.xinst.xinstruction.XInstruction.bundle, inject_bundles.int, and linker.instructions.instruction.BaseInstruction.tokens.
Referenced by common.cycle_tracking.CycleType.__binaryop_cycles(), common.cycle_tracking.CycleType.__binaryop_tuple(), and xinst.xinstruction.XInstruction.__str__().
bundle() [2/2]
def linker.instructions.xinst.xinstruction.XInstruction.bundle (self, int value) private
   Sets the bundle index.
   Parameters:
       value (int): The new bundle index.
   Raises:
       ValueError: If the value is negative.
Definition at line 66 of file xinstruction.py.
References linker.instructions.xinst.xinstruction.XInstruction.bundle, and linker.instructions.instruction.BaseInstruction.tokens.
Referenced by common.cycle_tracking.CycleType.__binaryop_cycles(), common.cycle_tracking.CycleType.__binaryop_tuple(), and xinst.xinstruction.XInstruction.__str__().
Property Documentation
bundle
linker.instructions.xinst.xinstruction.XInstruction.bundle = property static
Gets the bundle index.
Returns: int: The bundle index.
Raises: RuntimeError: If the bundle format is invalid.
Definition at line 48 of file xinstruction.py.
Referenced by common.cycle_tracking.CycleType.__binaryop_cycles(), common.cycle_tracking.CycleType.__binaryop_tuple(), xinst.xinstruction.XInstruction.__str__(), and linker.instructions.xinst.xinstruction.XInstruction.bundle().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/linker/instructions/xinst/xinstruction.py