Encrypted Computing SDK: pisa::WParam Class Reference
pisa::WParam Class Reference
The WParam class w_<res>_<stage>_<block>
#include <p_isa_instruction.h>
Public Member Functions
WParam ()=default
WParam (const std::string &w_param)
int residual () const
void setResidual (int newResidual)
int stage () const
void setStage (int newStage)
int block () const
void setBlock (int newBlock)
Private Attributes
int m_residual
int m_stage
int m_block
Friends
std::ostream & operator<< (std::ostream &stream, WParam op)
Detailed Description
The WParam class w_<res>_<stage>_<block>
Definition at line 58 of file p_isa_instruction.h.
Constructor & Destructor Documentation
WParam() [1/2]
pisa::WParam::WParam () default
WParam() [2/2]
pisa::WParam::WParam (const std::string & w_param)
Definition at line 63 of file p_isa_instruction.h.
References m_block, m_residual, and m_stage.
Member Function Documentation
block()
int pisa::WParam::block () const
Definition at line 186 of file p_isa_instruction.cpp.
References m_block.
Referenced by instructions.xinst.twintt.Instruction::__repr__(), instructions.xinst.twntt.Instruction::__repr__(), instructions.xinst.twintt.Instruction::_toPISAFormat(), instructions.xinst.twntt.Instruction::_toPISAFormat(), instructions.xinst.twintt.Instruction::_toXASMISAFormat(), instructions.xinst.twntt.Instruction::_toXASMISAFormat(), pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), and pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute().
residual()
int pisa::WParam::residual () const
Definition at line 166 of file p_isa_instruction.cpp.
References m_residual.
Referenced by pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), and pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute().
setBlock()
void pisa::WParam::setBlock (int newBlock)
Definition at line 191 of file p_isa_instruction.cpp.
References m_block.
setResidual()
void pisa::WParam::setResidual (int newResidual)
Definition at line 171 of file p_isa_instruction.cpp.
References m_residual.
setStage()
void pisa::WParam::setStage (int newStage)
Definition at line 181 of file p_isa_instruction.cpp.
References m_stage.
stage()
int pisa::WParam::stage () const
Definition at line 176 of file p_isa_instruction.cpp.
References m_stage.
Referenced by instructions.xinst.twintt.Instruction::__repr__(), instructions.xinst.twntt.Instruction::__repr__(), instructions.xinst.intt.Instruction::_toPISAFormat(), instructions.xinst.ntt.Instruction::_toPISAFormat(), instructions.xinst.twintt.Instruction::_toPISAFormat(), instructions.xinst.twntt.Instruction::_toPISAFormat(), instructions.xinst.intt.Instruction::_toXASMISAFormat(), instructions.xinst.ntt.Instruction::_toXASMISAFormat(), instructions.xinst.twintt.Instruction::_toXASMISAFormat(), instructions.xinst.twntt.Instruction::_toXASMISAFormat(), pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), and pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, WParam op) friend
Definition at line 83 of file p_isa_instruction.h.
Member Data Documentation
m_block
int pisa::WParam::m_block private
Definition at line 101 of file p_isa_instruction.h.
Referenced by block(), setBlock(), and WParam().
m_residual
int pisa::WParam::m_residual private
Definition at line 99 of file p_isa_instruction.h.
Referenced by residual(), setResidual(), and WParam().
m_stage
int pisa::WParam::m_stage private
Definition at line 100 of file p_isa_instruction.h.
Referenced by setStage(), stage(), and WParam().
The documentation for this class was generated from the following files:
p-isa_tools/common/p_isa/p_isa_instruction.h
p-isa_tools/common/p_isa/p_isa_instruction.cpp