Encrypted Computing SDK: common.constants.MemoryModel Class Reference
common.constants.MemoryModel Class Reference
Constants related to memory model.
Classes
class HBM
Constants related to High Bandwidth Memory (HBM).
class SPAD
Constants related to Scratchpad Memory (SPAD).
Public Member Functions
def XINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the XINST queue in bytes.
def XINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the XINST queue in words.
def CINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the CINST queue in bytes.
def CINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the CINST queue in words.
def MINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the MINST queue in bytes.
def MINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the MINST queue in words.
def STORE_BUFFER_MAX_CAPACITY (cls)
Maximum capacity of the store buffer in bytes.
def STORE_BUFFER_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the store buffer in words.
int NUM_BLOCKS_PER_TWID_META_WORD (cls)
Number of blocks per twiddle metadata word.
int NUM_BLOCKS_PER_KGSEED_META_WORD (cls)
Number of blocks per key generation seed metadata word.
int NUM_ROUTING_TABLE_REGISTERS (cls)
Number of routing table registers.
int NUM_ONES_META_REGISTERS (cls)
Number of registers to hold identity metadata.
int NUM_TWIDDLE_META_REGISTERS (cls)
Number of registers to hold twiddle factor metadata.
int TWIDDLE_META_REGISTER_SIZE_BYTES (cls)
Size, in bytes, of a twiddle factor metadata register.
int MAX_RESIDUALS (cls)
Maximum number of residuals that can be processed in the CE without needing to load new metadata.
int NUM_REGISTER_BANKS (cls)
Number of register banks in the CE.
int NUM_REGISTERS_PER_BANK (cls)
Number of register per register banks in the CE.
dict hw_spec_as_dict (cls)
Returns hw configurable attributes as dictionary.
def setMaxXInstQueueCapacity (cls, int val)
Sets max XInst queue capacity.
def setMaxCInstQueueCapacity (cls, int val)
Sets max CInst queue capacity.
def setMaxMInstQueueCapacity (cls, int val)
Sets max MInst queue capacity.
def setMaxStoreBufferCapacity (cls, int val)
Sets max store buffer capacity.
def setNumBlocksPerTwidMetaWord (cls, int val)
Sets the number of blocks per twiddle metadata word.
def setNumBlocksPerKgseedMetaWord (cls, int val)
Sets the number of blocks per key generation seed metadata word.
def setNumRoutingTableRegisters (cls, int val)
Sets the number of routing table registers.
def setNumOnesMetaRegisters (cls, int val)
Sets the number of ones metadata registers.
def setNumTwiddleMetaRegisters (cls, int val)
Sets the number of twiddle metadata registers.
def setTwiddleMetaRegisterSizeBytes (cls, int val)
Sets the size of twiddle metadata register in bytes.
def setMaxResiduals (cls, int val)
Sets the maximum number of residuals.
def setNumRegisterBanks (cls, int val)
Sets the number of register banks.
def setNumRegistersPerBank (cls, int val)
Sets the number of registers per bank.
Private Attributes
__XINST_QUEUE_MAX_CAPACITY
__CINST_QUEUE_MAX_CAPACITY
__MINST_QUEUE_MAX_CAPACITY
__STORE_BUFFER_MAX_CAPACITY
__NUM_BLOCKS_PER_TWID_META_WORD
__NUM_BLOCKS_PER_KGSEED_META_WORD
__NUM_ROUTING_TABLE_REGISTERS
__NUM_ONES_META_REGISTERS
__NUM_TWIDDLE_META_REGISTERS
__TWIDDLE_META_REGISTER_SIZE_BYTES
__MAX_RESIDUALS
__NUM_REGISTER_BANKS
__NUM_REGISTERS_PER_BANK
Detailed Description
Constants related to memory model.
This class defines a hierarchical structure for different parts of the memory model, including queue capacities, metadata registers, and specific memory components like HBM and SPAD.
Definition at line 313 of file constants.py.
Member Function Documentation
CINST_QUEUE_MAX_CAPACITY()
def common.constants.MemoryModel.CINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the CINST queue in bytes.
Definition at line 341 of file constants.py.
References common.constants.MemoryModel.__CINST_QUEUE_MAX_CAPACITY.
CINST_QUEUE_MAX_CAPACITY_WORDS()
def common.constants.MemoryModel.CINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the CINST queue in words.
Definition at line 345 of file constants.py.
References common.constants.MemoryModel.__CINST_QUEUE_MAX_CAPACITY, and common.constants.convertBytes2Words().
hw_spec_as_dict()
dict common.constants.MemoryModel.hw_spec_as_dict (cls)
Returns hw configurable attributes as dictionary.
Definition at line 434 of file constants.py.
References common.constants.MemoryModel.__CINST_QUEUE_MAX_CAPACITY, common.constants.MemoryModel.__MINST_QUEUE_MAX_CAPACITY, common.constants.MemoryModel.__STORE_BUFFER_MAX_CAPACITY, common.constants.MemoryModel.__XINST_QUEUE_MAX_CAPACITY, common.constants.MemoryModel.MAX_RESIDUALS(), common.constants.MemoryModel.NUM_BLOCKS_PER_KGSEED_META_WORD(), common.constants.MemoryModel.NUM_BLOCKS_PER_TWID_META_WORD(), common.constants.MemoryModel.NUM_ONES_META_REGISTERS(), common.constants.MemoryModel.NUM_REGISTER_BANKS(), common.constants.MemoryModel.NUM_REGISTERS_PER_BANK(), common.constants.MemoryModel.NUM_ROUTING_TABLE_REGISTERS(), common.constants.MemoryModel.NUM_TWIDDLE_META_REGISTERS(), and common.constants.MemoryModel.TWIDDLE_META_REGISTER_SIZE_BYTES().
MAX_RESIDUALS()
int common.constants.MemoryModel.MAX_RESIDUALS (cls)
Maximum number of residuals that can be processed in the CE without needing to load new metadata.
Definition at line 417 of file constants.py.
References common.constants.MemoryModel.__MAX_RESIDUALS.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
MINST_QUEUE_MAX_CAPACITY()
def common.constants.MemoryModel.MINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the MINST queue in bytes.
Definition at line 349 of file constants.py.
References common.constants.MemoryModel.__MINST_QUEUE_MAX_CAPACITY.
MINST_QUEUE_MAX_CAPACITY_WORDS()
def common.constants.MemoryModel.MINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the MINST queue in words.
Definition at line 353 of file constants.py.
References common.constants.MemoryModel.__MINST_QUEUE_MAX_CAPACITY, and common.constants.convertBytes2Words().
NUM_BLOCKS_PER_KGSEED_META_WORD()
int common.constants.MemoryModel.NUM_BLOCKS_PER_KGSEED_META_WORD (cls)
Number of blocks per key generation seed metadata word.
Definition at line 371 of file constants.py.
References common.constants.MemoryModel.__NUM_BLOCKS_PER_KGSEED_META_WORD.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_BLOCKS_PER_TWID_META_WORD()
int common.constants.MemoryModel.NUM_BLOCKS_PER_TWID_META_WORD (cls)
Number of blocks per twiddle metadata word.
Definition at line 366 of file constants.py.
References common.constants.MemoryModel.__NUM_BLOCKS_PER_TWID_META_WORD.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_ONES_META_REGISTERS()
int common.constants.MemoryModel.NUM_ONES_META_REGISTERS (cls)
Number of registers to hold identity metadata.
This directly affects the maximum number of residuals that can be processed in the CE without needing to load new metadata.
Definition at line 392 of file constants.py.
References common.constants.MemoryModel.__NUM_ONES_META_REGISTERS.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_REGISTER_BANKS()
int common.constants.MemoryModel.NUM_REGISTER_BANKS (cls)
Number of register banks in the CE.
Definition at line 422 of file constants.py.
References common.constants.MemoryModel.__NUM_REGISTER_BANKS.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_REGISTERS_PER_BANK()
int common.constants.MemoryModel.NUM_REGISTERS_PER_BANK (cls)
Number of register per register banks in the CE.
Definition at line 427 of file constants.py.
References common.constants.MemoryModel.__NUM_REGISTERS_PER_BANK.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_ROUTING_TABLE_REGISTERS()
int common.constants.MemoryModel.NUM_ROUTING_TABLE_REGISTERS (cls)
Number of routing table registers.
This affects how many rshuffle of different types can be performed at the same time, since rshuffle instructions will pick a routing table to use to compute the shuffled result.
Definition at line 382 of file constants.py.
References common.constants.MemoryModel.__NUM_ROUTING_TABLE_REGISTERS.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
NUM_TWIDDLE_META_REGISTERS()
int common.constants.MemoryModel.NUM_TWIDDLE_META_REGISTERS (cls)
Number of registers to hold twiddle factor metadata.
This directly affects the maximum number of residuals that can be processed in the CE without needing to load new metadata.
Definition at line 402 of file constants.py.
References common.constants.MemoryModel.__NUM_TWIDDLE_META_REGISTERS.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
setMaxCInstQueueCapacity()
def common.constants.MemoryModel.setMaxCInstQueueCapacity (cls, int val)
Sets max CInst queue capacity.
Definition at line 461 of file constants.py.
setMaxMInstQueueCapacity()
def common.constants.MemoryModel.setMaxMInstQueueCapacity (cls, int val)
Sets max MInst queue capacity.
Definition at line 468 of file constants.py.
setMaxResiduals()
def common.constants.MemoryModel.setMaxResiduals (cls, int val)
Sets the maximum number of residuals.
Definition at line 524 of file constants.py.
setMaxStoreBufferCapacity()
def common.constants.MemoryModel.setMaxStoreBufferCapacity (cls, int val)
Sets max store buffer capacity.
Definition at line 475 of file constants.py.
setMaxXInstQueueCapacity()
def common.constants.MemoryModel.setMaxXInstQueueCapacity (cls, int val)
Sets max XInst queue capacity.
Definition at line 454 of file constants.py.
setNumBlocksPerKgseedMetaWord()
def common.constants.MemoryModel.setNumBlocksPerKgseedMetaWord (cls, int val)
Sets the number of blocks per key generation seed metadata word.
Definition at line 489 of file constants.py.
setNumBlocksPerTwidMetaWord()
def common.constants.MemoryModel.setNumBlocksPerTwidMetaWord (cls, int val)
Sets the number of blocks per twiddle metadata word.
Definition at line 482 of file constants.py.
setNumOnesMetaRegisters()
def common.constants.MemoryModel.setNumOnesMetaRegisters (cls, int val)
Sets the number of ones metadata registers.
Definition at line 503 of file constants.py.
setNumRegisterBanks()
def common.constants.MemoryModel.setNumRegisterBanks (cls, int val)
Sets the number of register banks.
Definition at line 531 of file constants.py.
setNumRegistersPerBank()
def common.constants.MemoryModel.setNumRegistersPerBank (cls, int val)
Sets the number of registers per bank.
Definition at line 538 of file constants.py.
setNumRoutingTableRegisters()
def common.constants.MemoryModel.setNumRoutingTableRegisters (cls, int val)
Sets the number of routing table registers.
Definition at line 496 of file constants.py.
setNumTwiddleMetaRegisters()
def common.constants.MemoryModel.setNumTwiddleMetaRegisters (cls, int val)
Sets the number of twiddle metadata registers.
Definition at line 510 of file constants.py.
setTwiddleMetaRegisterSizeBytes()
def common.constants.MemoryModel.setTwiddleMetaRegisterSizeBytes (cls, int val)
Sets the size of twiddle metadata register in bytes.
Definition at line 517 of file constants.py.
STORE_BUFFER_MAX_CAPACITY()
def common.constants.MemoryModel.STORE_BUFFER_MAX_CAPACITY (cls)
Maximum capacity of the store buffer in bytes.
Definition at line 357 of file constants.py.
References common.constants.MemoryModel.__STORE_BUFFER_MAX_CAPACITY.
STORE_BUFFER_MAX_CAPACITY_WORDS()
def common.constants.MemoryModel.STORE_BUFFER_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the store buffer in words.
Definition at line 361 of file constants.py.
References common.constants.MemoryModel.__STORE_BUFFER_MAX_CAPACITY, and common.constants.convertBytes2Words().
TWIDDLE_META_REGISTER_SIZE_BYTES()
int common.constants.MemoryModel.TWIDDLE_META_REGISTER_SIZE_BYTES (cls)
Size, in bytes, of a twiddle factor metadata register.
Definition at line 409 of file constants.py.
References common.constants.MemoryModel.__TWIDDLE_META_REGISTER_SIZE_BYTES.
Referenced by common.constants.MemoryModel.hw_spec_as_dict().
XINST_QUEUE_MAX_CAPACITY()
def common.constants.MemoryModel.XINST_QUEUE_MAX_CAPACITY (cls)
Maximum capacity of the XINST queue in bytes.
Definition at line 333 of file constants.py.
References common.constants.MemoryModel.__XINST_QUEUE_MAX_CAPACITY.
XINST_QUEUE_MAX_CAPACITY_WORDS()
def common.constants.MemoryModel.XINST_QUEUE_MAX_CAPACITY_WORDS (cls)
Maximum capacity of the XINST queue in words.
Definition at line 337 of file constants.py.
References common.constants.MemoryModel.__XINST_QUEUE_MAX_CAPACITY, and common.constants.convertBytes2Words().
Member Data Documentation
__CINST_QUEUE_MAX_CAPACITY
common.constants.MemoryModel.__CINST_QUEUE_MAX_CAPACITY private
Definition at line 462 of file constants.py.
Referenced by common.constants.MemoryModel.CINST_QUEUE_MAX_CAPACITY(), common.constants.MemoryModel.CINST_QUEUE_MAX_CAPACITY_WORDS(), and common.constants.MemoryModel.hw_spec_as_dict().
__MAX_RESIDUALS
common.constants.MemoryModel.__MAX_RESIDUALS private
Definition at line 525 of file constants.py.
Referenced by common.constants.MemoryModel.MAX_RESIDUALS().
__MINST_QUEUE_MAX_CAPACITY
common.constants.MemoryModel.__MINST_QUEUE_MAX_CAPACITY private
Definition at line 469 of file constants.py.
Referenced by common.constants.MemoryModel.hw_spec_as_dict(), common.constants.MemoryModel.MINST_QUEUE_MAX_CAPACITY(), and common.constants.MemoryModel.MINST_QUEUE_MAX_CAPACITY_WORDS().
__NUM_BLOCKS_PER_KGSEED_META_WORD
common.constants.MemoryModel.__NUM_BLOCKS_PER_KGSEED_META_WORD private
Definition at line 490 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_BLOCKS_PER_KGSEED_META_WORD().
__NUM_BLOCKS_PER_TWID_META_WORD
common.constants.MemoryModel.__NUM_BLOCKS_PER_TWID_META_WORD private
Definition at line 483 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_BLOCKS_PER_TWID_META_WORD().
__NUM_ONES_META_REGISTERS
common.constants.MemoryModel.__NUM_ONES_META_REGISTERS private
Definition at line 504 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_ONES_META_REGISTERS().
__NUM_REGISTER_BANKS
common.constants.MemoryModel.__NUM_REGISTER_BANKS private
Definition at line 532 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_REGISTER_BANKS().
__NUM_REGISTERS_PER_BANK
common.constants.MemoryModel.__NUM_REGISTERS_PER_BANK private
Definition at line 539 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_REGISTERS_PER_BANK().
__NUM_ROUTING_TABLE_REGISTERS
common.constants.MemoryModel.__NUM_ROUTING_TABLE_REGISTERS private
Definition at line 497 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_ROUTING_TABLE_REGISTERS().
__NUM_TWIDDLE_META_REGISTERS
common.constants.MemoryModel.__NUM_TWIDDLE_META_REGISTERS private
Definition at line 511 of file constants.py.
Referenced by common.constants.MemoryModel.NUM_TWIDDLE_META_REGISTERS().
__STORE_BUFFER_MAX_CAPACITY
common.constants.MemoryModel.__STORE_BUFFER_MAX_CAPACITY private
Definition at line 476 of file constants.py.
Referenced by common.constants.MemoryModel.hw_spec_as_dict(), common.constants.MemoryModel.STORE_BUFFER_MAX_CAPACITY(), and common.constants.MemoryModel.STORE_BUFFER_MAX_CAPACITY_WORDS().
__TWIDDLE_META_REGISTER_SIZE_BYTES
common.constants.MemoryModel.__TWIDDLE_META_REGISTER_SIZE_BYTES private
Definition at line 518 of file constants.py.
Referenced by common.constants.MemoryModel.TWIDDLE_META_REGISTER_SIZE_BYTES().
__XINST_QUEUE_MAX_CAPACITY
common.constants.MemoryModel.__XINST_QUEUE_MAX_CAPACITY private
Definition at line 455 of file constants.py.
Referenced by common.constants.MemoryModel.hw_spec_as_dict(), common.constants.MemoryModel.XINST_QUEUE_MAX_CAPACITY(), and common.constants.MemoryModel.XINST_QUEUE_MAX_CAPACITY_WORDS().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/common/constants.py