Encrypted Computing SDK: linker.instructions.cinst.kgstart.Instruction Class Reference
linker.instructions.cinst.kgstart.Instruction Class Reference
Encapsulates a kg_start CInstruction.
Public Member Functions
def __init__ (self, list tokens, str comment="")
Constructs a new kg_start CInstruction.
Public Member Functions inherited from linker.instructions.cinst.cinstruction.CInstruction
str to_line (self)
Retrieves the string form of the instruction to write to the instruction file.
Public Member Functions inherited from linker.instructions.instruction.BaseInstruction
str name (cls)
Name for the instruction.
int NAME_TOKEN_INDEX (cls)
Index for the token containing the name of the instruction in the list of tokens.
int NUM_TOKENS (cls)
Number of tokens required for this instruction.
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __str__ (self)
Private Member Functions
int _get_num_tokens (cls)
str _get_name (cls)
Additional Inherited Members
Public Attributes inherited from linker.instructions.instruction.BaseInstruction
comment
Properties inherited from linker.instructions.instruction.BaseInstruction
id = property
Unique ID for the instruction.
tokens = property
Gets the list of tokens for the instruction.
Detailed Description
Encapsulates a kg_start CInstruction.
Definition at line 6 of file kgstart.py.
Constructor & Destructor Documentation
__init__()
def linker.instructions.cinst.kgstart.Instruction.__init__ (self, list tokens, str comment = "")
Constructs a new kg_start CInstruction.
Args: tokens (list): A list of tokens representing the instruction. comment (str, optional): An optional comment for the instruction. Defaults to an empty string.
Raises: ValueError: If the number of tokens is invalid or the instruction name is incorrect.
Reimplemented from linker.instructions.cinst.cinstruction.CInstruction.
Definition at line 45 of file kgstart.py.
Member Function Documentation
_get_name()
str linker.instructions.cinst.kgstart.Instruction._get_name (cls) private
   Gets the name of the instruction.
   Returns:
       str: The name of the instruction, which is "kg_start".
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 32 of file kgstart.py.
Referenced by instructions.instruction.BaseInstruction.name(), xinst.xinstruction.XInstruction.name(), and linker.instructions.instruction.BaseInstruction.name().
_get_num_tokens()
int linker.instructions.cinst.kgstart.Instruction._get_num_tokens (cls) private
   Gets the number of tokens required for the instruction.
   The `kg_start` instruction requires 2 tokens:
   <line: uint>, kg_start
   Returns:
       int: The number of tokens, which is 2.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 20 of file kgstart.py.
Referenced by linker.instructions.instruction.BaseInstruction.NUM_TOKENS().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/linker/instructions/cinst/kgstart.py