Encrypted Computing SDK: graph::Graph< INSTRUCTION > Class Template Reference
graph::Graph< INSTRUCTION > Class Template Reference
#include <graph.h>
Public Member Functions
Graph ()=default
Graph (Graph &graph)
Graph clone () const
void printGraphInfo () const
NetworkNode< INSTRUCTION > getNode (int node_id)
std::vector< NetworkNode< INSTRUCTION > > getNodes () const
std::vector< NetworkNode< INSTRUCTION > > getOutputNodes () const
std::vector< NetworkNode< INSTRUCTION > > getInputNodes (bool include_registers=true, bool include_immediates=true, bool include_operations=true) const
void removeAllExceptOutputNodes ()
void removeAllExceptInputNodes ()
void removeNode (NetworkNode< INSTRUCTION > &node)
void removeNodeMaintainConnections (NetworkNode< INSTRUCTION > &node)
size_t getNodeCount ()
std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction > > > getGraphInputLayers ()
Graph getInstructionGraph ()
Graph getDataGraph ()
void renderGraphToPNGDot (const std::string &filename, LABEL_OPTION label) const
void writeDotFile (const std::string &filename, LABEL_OPTION label) const
Graph getNodeDependencyGraph (int start_node_id, bool trace_ancestors, bool trace_dependents) const
Static Public Member Functions
static Graph createGraph (std::vector< INSTRUCTION * > instructions)
Private Member Functions
Network< INSTRUCTION > cloneGraph (const Network< INSTRUCTION > &input) const
void getOutputNodesInPlace (Network< INSTRUCTION > &graph_output_nodes)
Network< INSTRUCTION > getOutputNodesInternal (const Network< INSTRUCTION > &graph) const
void getInputNodesInPlace (Network< INSTRUCTION > &graph)
void reverseEdgeDirections (Network< INSTRUCTION > &graph)
Network< INSTRUCTION > GetBfsTree (const Network< INSTRUCTION > &graph, int start_node_id, bool in_direction, bool out_direction) const
TIntStrH getDataNodeNames (Network< INSTRUCTION > graph) const
TIntStrH getInstructionResults (Network< INSTRUCTION > graph) const
Private Attributes
std::map< std::string, std::vector< int > > node_ID_Map
Network< INSTRUCTION > network
Detailed Description
template<typename INSTRUCTION>
class graph::Graph< INSTRUCTION >
Definition at line 100 of file graph.h.
Constructor & Destructor Documentation
Graph() [1/2]
template<typename INSTRUCTION > graph::Graph< INSTRUCTION >::Graph () default
Graph() [2/2]
template<typename INSTRUCTION > graph::Graph< INSTRUCTION >::Graph (Graph< INSTRUCTION > & graph)
Definition at line 106 of file graph.h.
Member Function Documentation
clone()
template<typename INSTRUCTION > Graph graph::Graph< INSTRUCTION >::clone () const
Definition at line 112 of file graph.h.
References graph::Graph< INSTRUCTION >::cloneGraph(), and graph::Graph< INSTRUCTION >::network.
Referenced by PISAGraphOptimizer::generateInstructionStreamFromGraph(), graph::Graph< INSTRUCTION >::getDataGraph(), and graph::Graph< INSTRUCTION >::getInstructionGraph().
cloneGraph()
template<typename INSTRUCTION > Network< INSTRUCTION > graph::Graph< INSTRUCTION >::cloneGraph (const Network< INSTRUCTION > & input) const private
Definition at line 380 of file graph.h.
Referenced by graph::Graph< INSTRUCTION >::clone().
createGraph()
template<typename INSTRUCTION > Graph< INSTRUCTION > graph::Graph< INSTRUCTION >::createGraph (std::vector< INSTRUCTION * > instructions) static
Definition at line 184 of file graph.h.
References graph::IMMEDIATE, graph::OPERATION, and graph::REGISTER_ADDRESS.
Referenced by pisa::performance::PISAPerformanceModeler::addGraphAnalysis(), pisa::kernel::PISAKernel::determineVariableNamingViaGraph(), pisa::performance::PISAPerformanceModeler::generateInstructionAndMemoryPerformanceGraphReport(), pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram(), main(), pisa::performance::PISAPerformanceModeler::updateInstructionsToUniqueIntermediateRegisters(), and pisa::performance::PISAPerformanceModeler::updateInstructionsToUniqueIntermediateRegistersNew().
GetBfsTree()
template<typename INSTRUCTION > Network< INSTRUCTION > graph::Graph< INSTRUCTION >::GetBfsTree (const Network< INSTRUCTION > & graph, int start_node_id, bool in_direction, bool out_direction) const private
Definition at line 478 of file graph.h.
getDataGraph()
template<typename INSTRUCTION > Graph graph::Graph< INSTRUCTION >::getDataGraph ()
Definition at line 147 of file graph.h.
References graph::Graph< INSTRUCTION >::clone(), and graph::OPERATION.
getDataNodeNames()
template<typename INSTRUCTION > TIntStrH graph::Graph< INSTRUCTION >::getDataNodeNames (Network< INSTRUCTION > graph) const private
Definition at line 534 of file graph.h.
References isolation_test::name.
getGraphInputLayers()
template<typename INSTRUCTION > std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction > > > graph::Graph< INSTRUCTION >::getGraphInputLayers
Definition at line 356 of file graph.h.
getInputNodes()
template<typename INSTRUCTION > std::vector< NetworkNode< INSTRUCTION > > graph::Graph< INSTRUCTION >::getInputNodes (bool include_registers = true, bool include_immediates = true, bool include_operations = true) const
Definition at line 305 of file graph.h.
References graph::IMMEDIATE, graph::OPERATION, and graph::REGISTER_ADDRESS.
Referenced by PisaTestGenerator::generateJSONForGraph().
getInputNodesInPlace()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::getInputNodesInPlace (Network< INSTRUCTION > & graph) private
Definition at line 420 of file graph.h.
Referenced by graph::Graph< INSTRUCTION >::removeAllExceptInputNodes().
getInstructionGraph()
template<typename INSTRUCTION > Graph graph::Graph< INSTRUCTION >::getInstructionGraph ()
Definition at line 134 of file graph.h.
References graph::Graph< INSTRUCTION >::clone(), and graph::OPERATION.
getInstructionResults()
template<typename INSTRUCTION > TIntStrH graph::Graph< INSTRUCTION >::getInstructionResults (Network< INSTRUCTION > graph) const private
Definition at line 557 of file graph.h.
References isolation_test::name.
getNode()
template<typename INSTRUCTION > NetworkNode< INSTRUCTION > graph::Graph< INSTRUCTION >::getNode (int node_id)
Definition at line 262 of file graph.h.
Referenced by PISAGraphOptimizer::nodeInstructionAdjustment(), PISAGraphOptimizer::nodeLocklist(), PISAGraphOptimizer::nodeMACVariableAdjustment(), and PISAGraphOptimizer::nodeVariableAdjustment().
getNodeCount()
template<typename INSTRUCTION > size_t graph::Graph< INSTRUCTION >::getNodeCount ()
Definition at line 132 of file graph.h.
References graph::Graph< INSTRUCTION >::network.
getNodeDependencyGraph()
template<typename INSTRUCTION > Graph< INSTRUCTION > graph::Graph< INSTRUCTION >::getNodeDependencyGraph (int start_node_id, bool trace_ancestors, bool trace_dependents) const
Definition at line 464 of file graph.h.
References graph::Graph< INSTRUCTION >::network.
getNodes()
template<typename INSTRUCTION > std::vector< NetworkNode< INSTRUCTION > > graph::Graph< INSTRUCTION >::getNodes
Definition at line 280 of file graph.h.
Referenced by PISAGraphOptimizer::generateInstructionStreamFromGraph().
getOutputNodes()
template<typename INSTRUCTION > std::vector< NetworkNode< INSTRUCTION > > graph::Graph< INSTRUCTION >::getOutputNodes
Definition at line 290 of file graph.h.
Referenced by PisaTestGenerator::generateJSONForGraph().
getOutputNodesInPlace()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::getOutputNodesInPlace (Network< INSTRUCTION > & graph_output_nodes) private
Definition at line 395 of file graph.h.
Referenced by graph::Graph< INSTRUCTION >::removeAllExceptOutputNodes().
getOutputNodesInternal()
template<typename INSTRUCTION > Network< INSTRUCTION > graph::Graph< INSTRUCTION >::getOutputNodesInternal (const Network< INSTRUCTION > & graph) const private
Definition at line 412 of file graph.h.
printGraphInfo()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::printGraphInfo () const
Definition at line 119 of file graph.h.
References graph::Graph< INSTRUCTION >::network.
removeAllExceptInputNodes()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::removeAllExceptInputNodes ()
Definition at line 129 of file graph.h.
References graph::Graph< INSTRUCTION >::getInputNodesInPlace(), and graph::Graph< INSTRUCTION >::network.
removeAllExceptOutputNodes()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::removeAllExceptOutputNodes ()
Definition at line 128 of file graph.h.
References graph::Graph< INSTRUCTION >::getOutputNodesInPlace(), and graph::Graph< INSTRUCTION >::network.
removeNode()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::removeNode (NetworkNode< INSTRUCTION > & node)
Definition at line 320 of file graph.h.
removeNodeMaintainConnections()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::removeNodeMaintainConnections (NetworkNode< INSTRUCTION > & node)
Definition at line 326 of file graph.h.
renderGraphToPNGDot()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::renderGraphToPNGDot (const std::string & filename, LABEL_OPTION label) const
Definition at line 426 of file graph.h.
References isolation_test::name, graph::NAME, and graph::OUT_STRING.
reverseEdgeDirections()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::reverseEdgeDirections (Network< INSTRUCTION > & graph) private
Definition at line 472 of file graph.h.
writeDotFile()
template<typename INSTRUCTION > void graph::Graph< INSTRUCTION >::writeDotFile (const std::string & filename, LABEL_OPTION label) const
Definition at line 445 of file graph.h.
References isolation_test::name, graph::NAME, and graph::OUT_STRING.
Member Data Documentation
network
template<typename INSTRUCTION > Network<INSTRUCTION> graph::Graph< INSTRUCTION >::network private
Definition at line 180 of file graph.h.
Referenced by graph::Graph< INSTRUCTION >::clone(), graph::Graph< INSTRUCTION >::getNodeCount(), graph::Graph< INSTRUCTION >::getNodeDependencyGraph(), graph::Graph< INSTRUCTION >::printGraphInfo(), graph::Graph< INSTRUCTION >::removeAllExceptInputNodes(), and graph::Graph< INSTRUCTION >::removeAllExceptOutputNodes().
node_ID_Map
template<typename INSTRUCTION > std::map<std::string, std::vector<int> > graph::Graph< INSTRUCTION >::node_ID_Map private
Definition at line 179 of file graph.h.
The documentation for this class was generated from the following file:
p-isa_tools/common/graph/graph.h