Encrypted Computing SDK: pisa::kernel::Cache Class Reference
pisa::kernel::Cache Class Reference
#include <pisakernel.h>
Public Member Functions
Cache ()=delete
Cache (const std::string &dirname, bool use_cache=true, bool remove_cache=false)
std::string getDirname () const
bool use_cache () const
~Cache ()
Private Attributes
std::string _dirname
bool _use_cache
bool _remove_cache
Detailed Description
Definition at line 18 of file pisakernel.h.
Constructor & Destructor Documentation
Cache() [1/2]
pisa::kernel::Cache::Cache () delete
Cache() [2/2]
pisa::kernel::Cache::Cache (const std::string & dirname, bool use_cache = true, bool remove_cache = false)
Definition at line 22 of file pisakernel.h.
References _dirname.
~Cache()
pisa::kernel::Cache::~Cache ()
Definition at line 31 of file pisakernel.h.
References _dirname, and _remove_cache.
Member Function Documentation
getDirname()
std::string pisa::kernel::Cache::getDirname () const
Definition at line 28 of file pisakernel.h.
References _dirname.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::createHECDataFormats(), and createKernelFilepath().
use_cache()
bool pisa::kernel::Cache::use_cache () const
Definition at line 29 of file pisakernel.h.
References _use_cache.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::create_new(), and pisa::kernel::PISAKernel::createHECDataFormats().
Member Data Documentation
_dirname
std::string pisa::kernel::Cache::_dirname private
Definition at line 40 of file pisakernel.h.
Referenced by Cache(), getDirname(), and ~Cache().
_remove_cache
bool pisa::kernel::Cache::_remove_cache private
Definition at line 42 of file pisakernel.h.
Referenced by ~Cache().
_use_cache
bool pisa::kernel::Cache::_use_cache private
Definition at line 41 of file pisakernel.h.
Referenced by use_cache().
The documentation for this class was generated from the following file:
p-isa_tools/program_mapper/p_isa/pisakernel.h