Encrypted Computing SDK: memory_model.mem_info.MemInfoKeygenVariable Class Reference
memory_model.mem_info.MemInfoKeygenVariable Class Reference
Represents a memory information key generation variable.
Public Member Functions
def __init__ (self, str var_name, int seed_index, int key_index)
Initializes a new MemInfoKeygenVariable object with a specified name, seed index, and key index.
dict as_dict (self)
Converts the MemInfoKeygenVariable object to a dictionary.
Public Member Functions inherited from memory_model.mem_info.MemInfoVariable
def __init__ (self, str var_name, int hbm_address)
Initializes a new MemInfoVariable object with a specified name and HBM address.
def __repr__ (self)
Returns a string representation of the MemInfoVariable object.
Public Attributes
seed_index
key_index
Public Attributes inherited from memory_model.mem_info.MemInfoVariable
var_name
hbm_address
Detailed Description
Represents a memory information key generation variable.
This class extends MemInfoVariable to include additional attributes for key generation, specifically the seed index and key index associated with the variable.
Definition at line 56 of file mem_info.py.
Constructor & Destructor Documentation
__init__()
def memory_model.mem_info.MemInfoKeygenVariable.__init__ (self, str var_name, int seed_index, int key_index)
Initializes a new MemInfoKeygenVariable object with a specified name, seed index, and key index.
Args: var_name (str): The name of the variable. Must be a valid identifier. seed_index (int): The index of the seed used for key generation. Must be a zero-based index. key_index (int): The index of the key. Must be a zero-based index.
Raises: IndexError: If the seed index or key index is negative.
Definition at line 68 of file mem_info.py.
Member Function Documentation
as_dict()
dict memory_model.mem_info.MemInfoKeygenVariable.as_dict (self)
Converts the MemInfoKeygenVariable object to a dictionary.
Returns: dict: A dictionary representation of the variable, including its name, seed index, and key index.
Reimplemented from memory_model.mem_info.MemInfoVariable.
Definition at line 86 of file mem_info.py.
References memory_model.mem_info.MemInfoKeygenVariable.key_index, memory_model.mem_info.MemInfoKeygenVariable.seed_index, and memory_model.mem_info.MemInfoVariable.var_name.
Referenced by memory_model.mem_info.MemInfoVariable.__repr__(), common.run_config.RunConfig.__str__(), he_as.AssemblerRunConfig.__str__(), and he_link.LinkerRunConfig.__str__().
Member Data Documentation
key_index
memory_model.mem_info.MemInfoKeygenVariable.key_index
Definition at line 78 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfoKeygenVariable.as_dict().
seed_index
memory_model.mem_info.MemInfoKeygenVariable.seed_index
Definition at line 77 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfoKeygenVariable.as_dict().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/memory_model/mem_info.py