Encrypted Computing SDK: pisa::PISAInstructionTrace< T > Class Template Reference
pisa::PISAInstructionTrace< T > Class Template Reference
#include <p_isa_instruction_trace.h>
Public Member Functions
PISAInstructionTrace ()
PISAInstructionTrace (std::shared_ptr< PISAInstruction > instr, std::vector< MultiRegister< T >> inputs, std::vector< MultiRegister< T >> outputs)
const std::vector< MultiRegister< T > > & executionResult () const
void setExecutionResult (const std::vector< MultiRegister< T >> &newExecution_result)
const std::vector< MultiRegister< T > > & executionInputs () const
void setExecutionInputs (const std::vector< MultiRegister< T >> &newExecution_inputs)
std::string outLabel ()
void printInstructionTrace (int max_values=10)
const std::shared_ptr< PISAInstruction > & instruction () const
void setInstruction (const std::shared_ptr< PISAInstruction > &newInstruction)
void setInstruction (pisa::PISAInstruction *instr)
Private Attributes
std::shared_ptr< PISAInstruction > m_instruction
std::vector< MultiRegister< T > > m_execution_inputs
std::vector< MultiRegister< T > > m_execution_result
Detailed Description
template<typename T>
class pisa::PISAInstructionTrace< T >
Definition at line 11 of file p_isa_instruction_trace.h.
Constructor & Destructor Documentation
PISAInstructionTrace() [1/2]
template<typename T > pisa::PISAInstructionTrace< T >::PISAInstructionTrace ()
Definition at line 14 of file p_isa_instruction_trace.h.
PISAInstructionTrace() [2/2]
template<typename T > pisa::PISAInstructionTrace< T >::PISAInstructionTrace (std::shared_ptr< PISAInstruction > instr, std::vector< MultiRegister< T >> inputs, std::vector< MultiRegister< T >> outputs)
Member Function Documentation
executionInputs()
template<typename T > const std::vector<MultiRegister<T> >& pisa::PISAInstructionTrace< T >::executionInputs () const
Referenced by pisa::PISAInstructionTrace< T >::outLabel().
executionResult()
template<typename T > const std::vector<MultiRegister<T> >& pisa::PISAInstructionTrace< T >::executionResult () const
Referenced by pisa::PISAInstructionTrace< T >::outLabel().
instruction()
template<typename T > const std::shared_ptr<PISAInstruction>& pisa::PISAInstructionTrace< T >::instruction () const
Definition at line 72 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::m_instruction.
outLabel()
template<typename T > std::string pisa::PISAInstructionTrace< T >::outLabel ()
Definition at line 28 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::executionInputs(), and pisa::PISAInstructionTrace< T >::executionResult().
printInstructionTrace()
template<typename T > void pisa::PISAInstructionTrace< T >::printInstructionTrace (int max_values = 10)
Definition at line 45 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::m_execution_inputs, pisa::PISAInstructionTrace< T >::m_execution_result, and pisa::PISAInstructionTrace< T >::m_instruction.
setExecutionInputs()
template<typename T > void pisa::PISAInstructionTrace< T >::setExecutionInputs (const std::vector< MultiRegister< T >> & newExecution_inputs)
Definition at line 23 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::m_execution_inputs.
setExecutionResult()
template<typename T > void pisa::PISAInstructionTrace< T >::setExecutionResult (const std::vector< MultiRegister< T >> & newExecution_result)
Definition at line 17 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::m_execution_result.
setInstruction() [1/2]
template<typename T > void pisa::PISAInstructionTrace< T >::setInstruction (const std::shared_ptr< PISAInstruction > & newInstruction)
Definition at line 76 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::m_instruction.
Referenced by pisa::PISAFunctionalModel< T >::decode(), and pisa::PISAInstructionTrace< T >::setInstruction().
setInstruction() [2/2]
template<typename T > void pisa::PISAInstructionTrace< T >::setInstruction (pisa::PISAInstruction * instr)
Definition at line 80 of file p_isa_instruction_trace.h.
References pisa::PISAInstructionTrace< T >::setInstruction().
Member Data Documentation
m_execution_inputs
template<typename T > std::vector<MultiRegister<T> > pisa::PISAInstructionTrace< T >::m_execution_inputs private
Definition at line 87 of file p_isa_instruction_trace.h.
Referenced by pisa::PISAInstructionTrace< T >::printInstructionTrace(), and pisa::PISAInstructionTrace< T >::setExecutionInputs().
m_execution_result
template<typename T > std::vector<MultiRegister<T> > pisa::PISAInstructionTrace< T >::m_execution_result private
Definition at line 88 of file p_isa_instruction_trace.h.
Referenced by pisa::PISAInstructionTrace< T >::printInstructionTrace(), and pisa::PISAInstructionTrace< T >::setExecutionResult().
m_instruction
template<typename T > std::shared_ptr<PISAInstruction> pisa::PISAInstructionTrace< T >::m_instruction private
Definition at line 86 of file p_isa_instruction_trace.h.
Referenced by pisa::PISAInstructionTrace< T >::instruction(), pisa::PISAInstructionTrace< T >::printInstructionTrace(), and pisa::PISAInstructionTrace< T >::setInstruction().
The documentation for this class was generated from the following file:
p-isa_tools/functional_modeler/pisa_runtime/p_isa_instruction_trace.h