Encrypted Computing SDK: linker.instructions.cinst.xinstfetch.Instruction Class Reference
linker.instructions.cinst.xinstfetch.Instruction Class Reference
Encapsulates a xinstfetch CInstruction.
Public Member Functions
def __init__ (self, list tokens, str comment="")
Constructs a new xinstfetch CInstruction.
Public Member Functions inherited from linker.instructions.cinst.cinstruction.CInstruction
str to_line (self)
Retrieves the string form of the instruction to write to the instruction file.
Public Member Functions inherited from linker.instructions.instruction.BaseInstruction
str name (cls)
Name for the instruction.
int NAME_TOKEN_INDEX (cls)
Index for the token containing the name of the instruction in the list of tokens.
int NUM_TOKENS (cls)
Number of tokens required for this instruction.
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __str__ (self)
Properties
dstXQueue = property
Gets the destination in the XINST queue.
srcHBM = property
Gets the source in the HBM.
Properties inherited from linker.instructions.instruction.BaseInstruction
id = property
Unique ID for the instruction.
tokens = property
Gets the list of tokens for the instruction.
Private Member Functions
int _get_num_tokens (cls)
str _get_name (cls)
int dstXQueue (self)
def dstXQueue (self, int value)
int srcHBM (self)
def srcHBM (self, int value)
Additional Inherited Members
Public Attributes inherited from linker.instructions.instruction.BaseInstruction
comment
Detailed Description
Encapsulates a xinstfetch CInstruction.
This instruction fetches instructions from the HBM and sends them to the XINST queue.
For more information, check the xinstfetch Specification: https://github.com/IntelLabs/hec-assembler-tools/blob/master/docsrc/inst_spec/cinst/cinst_xinstfetch.md
Properties: dstXQueue: Gets or sets the destination in the XINST queue. srcHBM: Gets or sets the source in the HBM.
Definition at line 15 of file xinstfetch.py.
Constructor & Destructor Documentation
__init__()
def linker.instructions.cinst.xinstfetch.Instruction.__init__ (self, list tokens, str comment = "")
Constructs a new xinstfetch CInstruction.
Args: tokens (list): A list of tokens representing the instruction. comment (str, optional): An optional comment for the instruction. Defaults to an empty string.
Raises: ValueError: If the number of tokens is invalid or the instruction name is incorrect. NotImplementedError: If the xinstfetch CInstruction is not supported in the linker.
Reimplemented from linker.instructions.cinst.cinstruction.CInstruction.
Definition at line 55 of file xinstfetch.py.
Member Function Documentation
_get_name()
str linker.instructions.cinst.xinstfetch.Instruction._get_name (cls) private
   Gets the name of the instruction.
   Returns:
       str: The name of the instruction, which is "xinstfetch".
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 41 of file xinstfetch.py.
Referenced by instructions.instruction.BaseInstruction.name(), xinst.xinstruction.XInstruction.name(), and linker.instructions.instruction.BaseInstruction.name().
_get_num_tokens()
int linker.instructions.cinst.xinstfetch.Instruction._get_num_tokens (cls) private
   Gets the number of tokens required for the instruction.
   The `xinstfetch` instruction requires 4 tokens:
   <line: uint>, xinstfetch, <xq_dst:uint>, <hbm_src: uint>
   Returns:
       int: The number of tokens, which is 4.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 29 of file xinstfetch.py.
Referenced by linker.instructions.instruction.BaseInstruction.NUM_TOKENS().
dstXQueue() [1/2]
int linker.instructions.cinst.xinstfetch.Instruction.dstXQueue (self) private
Definition at line 68 of file xinstfetch.py.
References linker.instructions.cinst.xinstfetch.Instruction.dstXQueue, inject_bundles.int, and linker.instructions.instruction.BaseInstruction.tokens.
dstXQueue() [2/2]
def linker.instructions.cinst.xinstfetch.Instruction.dstXQueue (self, int value) private
   Sets the destination in the XINST queue.
   Args:
       value (int): The destination value to set.
   Raises:
       ValueError: If the value is negative.
Definition at line 82 of file xinstfetch.py.
References linker.instructions.cinst.xinstfetch.Instruction.dstXQueue, and linker.instructions.instruction.BaseInstruction.tokens.
srcHBM() [1/2]
int linker.instructions.cinst.xinstfetch.Instruction.srcHBM (self) private
Definition at line 96 of file xinstfetch.py.
References inject_bundles.int, linker.instructions.cinst.xinstfetch.Instruction.srcHBM, and linker.instructions.instruction.BaseInstruction.tokens.
srcHBM() [2/2]
def linker.instructions.cinst.xinstfetch.Instruction.srcHBM (self, int value) private
   Sets the source in the HBM.
   Args:
       value (int): The source value to set.
   Raises:
       ValueError: If the value is negative.
Definition at line 110 of file xinstfetch.py.
References linker.instructions.cinst.xinstfetch.Instruction.srcHBM, and linker.instructions.instruction.BaseInstruction.tokens.
Property Documentation
dstXQueue
linker.instructions.cinst.xinstfetch.Instruction.dstXQueue = property static
Gets the destination in the XINST queue.
Returns: int: The destination in the XINST queue.
Definition at line 66 of file xinstfetch.py.
Referenced by linker.instructions.cinst.xinstfetch.Instruction.dstXQueue().
srcHBM
linker.instructions.cinst.xinstfetch.Instruction.srcHBM = property static
Gets the source in the HBM.
Returns: int: The source in the HBM.
Definition at line 94 of file xinstfetch.py.
Referenced by linker.instructions.cinst.xinstfetch.Instruction.srcHBM().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/linker/instructions/cinst/xinstfetch.py