Encrypted Computing SDK: pisa::instruction::Ntt Class Reference
pisa::instruction::Ntt Class Reference
The Ntt class represents an ntt instruction in P_ISA.
#include <p_isa_instructions.h>
Public Member Functions
Ntt ()
Ntt (int poly_mod, Operand output_op0, Operand output_op1, Operand input_op0, Operand input_op1, WParam w_param, int residual)
PISAInstruction * create () override
Public Member Functions inherited from pisa::PISAInstruction
PISAInstruction (std::string name)
PISAInstruction (std::string name, InstructionDesc desc)
Operand & getInputOperand (int n)
Operand & getOutputOperand (int n)
void setInputOperand (const Operand &op, int n)
void setOutputOperand (const Operand &op, int n)
void addInputOperand (const Operand &op)
void addOutputOperand (const Operand &op)
int PMD () const
void setPMD (int newPmd_log2)
const std::string & Name () const
void setName (const std::string &newOperation_name)
int residual () const
void setResidual (int newResidual)
int numOutputOperands () const
int numInputOperands () const
int stage () const
void setStage (int newStage)
int block () const
void setBlock (int newBlock)
const WParam & wParam () const
void setWParam (const WParam &newW_param)
int galois_element () const
void setGalois_element (int newGalois_element)
const InstructionDesc getDescription () const
bool outputBlock () const
void setOutputBlock (bool newOutput_block)
int groupId () const
void setGroupId (int newGroup_id)
Public Member Functions inherited from ISAInstruction
ISAInstruction ()=default
Static Public Attributes
static const std::string baseName = "ntt"
Additional Inherited Members
Static Public Member Functions inherited from pisa::PISAInstruction
static std::string operationName ()
Protected Attributes inherited from pisa::PISAInstruction
int m_pmd_log2
std::string m_operation_name
std::vector< Operand > m_input_operands
std::vector< Operand > m_output_operands
std::vector< int > m_additional_params
WParam m_w_param
int m_residual
int m_group_id
int m_stage
int m_galois_element
int m_block
bool m_output_block
InstructionDesc m_description
Detailed Description
The Ntt class represents an ntt instruction in P_ISA.
Argument Type Description
POLYMOD_DEG_LOG2 Int Used for bit reversal and address calculations
OP_NAME string ntt
OUTPUT_OPERAND [out] string dst1 = label of output register
OUTPUT_OPERAND [out] string dst2 = label of output register
INPUT_OPERAND string src1 = label of input register
INPUT_OPERAND string src2 = label of input register
W_PACKED_PARAM string encodes as a string the following values residual_stage_block used for intt calculations
RESIDUAL int mod_q = index of modulus value to use
High level functional description: #TBD needs to ntt?
Definition at line 294 of file p_isa_instructions.h.
Constructor & Destructor Documentation
Ntt() [1/2]
pisa::instruction::Ntt::Ntt ()
Definition at line 297 of file p_isa_instructions.h.
Referenced by create().
Ntt() [2/2]
pisa::instruction::Ntt::Ntt (int poly_mod, Operand output_op0, Operand output_op1, Operand input_op0, Operand input_op1, WParam w_param, int residual)
Definition at line 299 of file p_isa_instructions.h.
References pisa::PISAInstruction::addInputOperand(), pisa::PISAInstruction::addOutputOperand(), pisa::PISAInstruction::residual(), pisa::PISAInstruction::setPMD(), pisa::PISAInstruction::setResidual(), and pisa::PISAInstruction::setWParam().
Member Function Documentation
create()
PISAInstruction* pisa::instruction::Ntt::create () override virtual
Reimplemented from pisa::PISAInstruction.
Definition at line 313 of file p_isa_instructions.h.
References Ntt().
Member Data Documentation
baseName
const std::string pisa::instruction::Ntt::baseName = "ntt" static
Definition at line 312 of file p_isa_instructions.h.
Referenced by pisa::PISAFunctionalModel< T >::decode(), pisa::PerformanceModels::ExampleHardware::ExampleHardware(), pisa::PerformanceModels::Model1::Model1(), and pisa::PerformanceModels::Model2::Model2().
The documentation for this class was generated from the following file:
p-isa_tools/common/p_isa/p_isa_instructions.h