Encrypted Computing SDK: common.constants.Constants Class Reference
common.constants.Constants Class Reference
Contains project level and global constants that won't fit logically into any other category.
Public Member Functions
int KILOBYTE (cls)
Number of bytes in a kilobyte (2^10).
int MEGABYTE (csl)
Number of bytes in a megabyte (2^20).
int GIGABYTE (cls)
Number of bytes in a gigabyte (2^30).
int WORD_SIZE (cls)
Word size in bytes (32KB/word).
str REPLACEMENT_POLICY_FTBU (cls)
Identifier for the "furthest used" replacement policy.
str REPLACEMENT_POLICY_LRU (cls)
Identifier for the "least recently used" replacement policy.
tuple REPLACEMENT_POLICIES (cls)
Tuple containing all replacement policy identifiers.
int XINSTRUCTION_SIZE_BYTES (cls)
Size of an x-instruction in bytes.
int MAX_BUNDLE_SIZE (cls)
Maximum number of instructions in a bundle.
int MAX_BUNDLE_SIZE_BYTES (cls)
Maximum bundle size in bytes.
str TW_GRAMMAR_SEPARATOR (cls)
Separator for twiddle arguments.
list OPERATIONS (cls)
List of high-level operations supported by the system.
dict hw_spec_as_dict (cls)
Returns hw configurable attributes as dictionary.
def setMaxBundleSize (cls, int val)
Updates max bundle size.
def setXInstructionSizeBytes (cls, int val)
Updates size of single XInstruction.
Private Attributes
__MAX_BUNDLE_SIZE
__XINSTRUCTION_SIZE_BYTES
Detailed Description
Contains project level and global constants that won't fit logically into any other category.
Attributes: KILOBYTE (int): Number of bytes in a kilobyte (2^10). MEGABYTE (int): Number of bytes in a megabyte (2^20). GIGABYTE (int): Number of bytes in a gigabyte (2^30). WORD_SIZE (int): Word size in bytes (32KB/word).
REPLACEMENT_POLICY_FTBU (str): Identifier for the "furthest used" replacement policy. REPLACEMENT_POLICY_LRU (str): Identifier for the "least recently used" replacement policy. REPLACEMENT_POLICIES (tuple): Tuple containing all replacement policy identifiers.
XINSTRUCTION_SIZE_BYTES (int): Size of an x-instruction in bytes. MAX_BUNDLE_SIZE (int): Maximum number of instructions in a bundle. MAX_BUNDLE_SIZE_BYTES (int): Maximum bundle size in bytes.
TW_GRAMMAR_SEPARATOR (str): Separator for twiddle arguments used in grammar parsing. OPERATIONS (list): List of high-level operations supported by the system.
Definition at line 24 of file constants.py.
Member Function Documentation
GIGABYTE()
int common.constants.Constants.GIGABYTE (cls)
Number of bytes in a gigabyte (2^30).
Definition at line 44 of file constants.py.
hw_spec_as_dict()
dict common.constants.Constants.hw_spec_as_dict (cls)
Returns hw configurable attributes as dictionary.
Definition at line 108 of file constants.py.
References common.constants.Constants.MAX_BUNDLE_SIZE(), and common.constants.Constants.XINSTRUCTION_SIZE_BYTES().
KILOBYTE()
int common.constants.Constants.KILOBYTE (cls)
Number of bytes in a kilobyte (2^10).
Definition at line 34 of file constants.py.
Referenced by common.constants.Constants.WORD_SIZE().
MAX_BUNDLE_SIZE()
int common.constants.Constants.MAX_BUNDLE_SIZE (cls)
Maximum number of instructions in a bundle.
Definition at line 80 of file constants.py.
References common.constants.Constants.__MAX_BUNDLE_SIZE.
Referenced by common.constants.Constants.hw_spec_as_dict(), and common.constants.Constants.MAX_BUNDLE_SIZE_BYTES().
MAX_BUNDLE_SIZE_BYTES()
int common.constants.Constants.MAX_BUNDLE_SIZE_BYTES (cls)
Maximum bundle size in bytes.
Definition at line 85 of file constants.py.
References common.constants.Constants.MAX_BUNDLE_SIZE(), and common.constants.Constants.XINSTRUCTION_SIZE_BYTES().
MEGABYTE()
int common.constants.Constants.MEGABYTE (csl)
Number of bytes in a megabyte (2^20).
Definition at line 39 of file constants.py.
OPERATIONS()
list common.constants.Constants.OPERATIONS (cls)
List of high-level operations supported by the system.
Definition at line 99 of file constants.py.
REPLACEMENT_POLICIES()
tuple common.constants.Constants.REPLACEMENT_POLICIES (cls)
Tuple containing all replacement policy identifiers.
Definition at line 67 of file constants.py.
References common.constants.Constants.REPLACEMENT_POLICY_FTBU(), and common.constants.Constants.REPLACEMENT_POLICY_LRU().
REPLACEMENT_POLICY_FTBU()
str common.constants.Constants.REPLACEMENT_POLICY_FTBU (cls)
Identifier for the "furthest used" replacement policy.
Definition at line 57 of file constants.py.
Referenced by common.constants.Constants.REPLACEMENT_POLICIES().
REPLACEMENT_POLICY_LRU()
str common.constants.Constants.REPLACEMENT_POLICY_LRU (cls)
Identifier for the "least recently used" replacement policy.
Definition at line 62 of file constants.py.
Referenced by common.constants.Constants.REPLACEMENT_POLICIES().
setMaxBundleSize()
def common.constants.Constants.setMaxBundleSize (cls, int val)
Updates max bundle size.
Definition at line 115 of file constants.py.
setXInstructionSizeBytes()
def common.constants.Constants.setXInstructionSizeBytes (cls, int val)
Updates size of single XInstruction.
Definition at line 120 of file constants.py.
TW_GRAMMAR_SEPARATOR()
str common.constants.Constants.TW_GRAMMAR_SEPARATOR (cls)
Separator for twiddle arguments.
Used in the grammar to parse the twiddle argument of an xntt kernel operation.
Definition at line 94 of file constants.py.
WORD_SIZE()
int common.constants.Constants.WORD_SIZE (cls)
Word size in bytes (32KB/word).
Definition at line 49 of file constants.py.
References common.constants.Constants.KILOBYTE().
XINSTRUCTION_SIZE_BYTES()
int common.constants.Constants.XINSTRUCTION_SIZE_BYTES (cls)
Size of an x-instruction in bytes.
Definition at line 75 of file constants.py.
References common.constants.Constants.__XINSTRUCTION_SIZE_BYTES.
Referenced by common.constants.Constants.hw_spec_as_dict(), and common.constants.Constants.MAX_BUNDLE_SIZE_BYTES().
Member Data Documentation
__MAX_BUNDLE_SIZE
common.constants.Constants.__MAX_BUNDLE_SIZE private
Definition at line 116 of file constants.py.
Referenced by common.constants.Constants.MAX_BUNDLE_SIZE().
__XINSTRUCTION_SIZE_BYTES
common.constants.Constants.__XINSTRUCTION_SIZE_BYTES private
Definition at line 121 of file constants.py.
Referenced by common.constants.Constants.XINSTRUCTION_SIZE_BYTES().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/common/constants.py