Encrypted Computing SDK: linker.instructions.xinst.twintt.Instruction Class Reference
linker.instructions.xinst.twintt.Instruction Class Reference
Encapsulates a twintt XInstruction.
Public Member Functions
def __init__ (self, list tokens, str comment="")
Constructs a new twintt XInstruction.
Public Member Functions inherited from linker.instructions.instruction.BaseInstruction
str name (cls)
Name for the instruction.
int NAME_TOKEN_INDEX (cls)
Index for the token containing the name of the instruction in the list of tokens.
int NUM_TOKENS (cls)
Number of tokens required for this instruction.
def __repr__ (self)
def __eq__ (self, other)
def __hash__ (self)
def __str__ (self)
str to_line (self)
Retrieves the string form of the instruction to write to the instruction file.
Private Member Functions
int _get_num_tokens (cls)
str _get_name (cls)
Additional Inherited Members
Public Attributes inherited from linker.instructions.instruction.BaseInstruction
comment
Properties inherited from linker.instructions.xinst.xinstruction.XInstruction
bundle = property
Gets the bundle index.
Properties inherited from linker.instructions.instruction.BaseInstruction
id = property
Unique ID for the instruction.
tokens = property
Gets the list of tokens for the instruction.
Detailed Description
Encapsulates a twintt XInstruction.
This instruction performs on-die generation of twiddle factors for the next stage of iNTT.
For more information, check the specification: https://github.com/IntelLabs/hec-assembler-tools/blob/master/docsrc/inst_spec/xinst/xinst_twintt.md.
Definition at line 11 of file twintt.py.
Constructor & Destructor Documentation
__init__()
def linker.instructions.xinst.twintt.Instruction.__init__ (self, list tokens, str comment = "")
Constructs a new twintt XInstruction.
Args: tokens (list): A list of tokens representing the instruction. comment (str, optional): An optional comment for the instruction. Defaults to an empty string.
Raises: ValueError: If the number of tokens is invalid or the instruction name is incorrect.
Reimplemented from linker.instructions.xinst.xinstruction.XInstruction.
Definition at line 50 of file twintt.py.
Member Function Documentation
_get_name()
str linker.instructions.xinst.twintt.Instruction._get_name (cls) private
   Gets the name of the instruction.
   Returns:
       str: The name of the instruction, which is "twintt".
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 37 of file twintt.py.
Referenced by instructions.instruction.BaseInstruction.name(), xinst.xinstruction.XInstruction.name(), and linker.instructions.instruction.BaseInstruction.name().
_get_num_tokens()
int linker.instructions.xinst.twintt.Instruction._get_num_tokens (cls) private
   Gets the number of tokens required for the instruction.
   The `twintt` instruction requires 10 tokens:
   F<bundle_idx: uint>, <info: str>, twintt, <dst_tw: str>, <src_tw: str>, <tw_meta: uint>, <stage: uint>, <block: uint>, <ring_dim: uint>, <res: uint>
   Returns:
       int: The number of tokens, which is 10.
Reimplemented from linker.instructions.instruction.BaseInstruction.
Definition at line 25 of file twintt.py.
Referenced by linker.instructions.instruction.BaseInstruction.NUM_TOKENS().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/linker/instructions/xinst/twintt.py