Encrypted Computing SDK: memory_model.mem_info.MemInfo Class Reference
memory_model.mem_info.MemInfo Class Reference
Represents memory information for a set of variables and metadata fields.
Classes
class Input
class Keygen
class Metadata
Encapsulates metadata fields within the memory information.
class Output
Public Member Functions
def __init__ (self, **kwargs)
Initializes a new MemInfo object.
def from_iter (cls, line_iter)
Creates a new MemInfo object from an iterator of strings, where each string is a line of text to parse.
def as_dict (self)
Returns a dictionary representation of this MemInfo object.
def validate (self)
Validates the MemInfo object to ensure consistency and correctness.
Static Public Attributes
Const = constants.MemInfo
Properties
keygens = property
Retrieves the list of keygen variables.
inputs = property
Retrieves the list of input variables.
outputs = property
Retrieves the list of output variables.
metadata = property
Retrieves the metadata associated with this MemInfo object.
Private Member Functions
list keygens (self)
list inputs (self)
list outputs (self)
Metadata metadata (self)
Private Attributes
__keygens
__inputs
__outputs
__metadata
Detailed Description
Represents memory information for a set of variables and metadata fields.
This class encapsulates the parsing and management of memory information variables, including key generation variables, input and output variables, and various metadata fields.
Definition at line 97 of file mem_info.py.
Constructor & Destructor Documentation
__init__()
def memory_model.mem_info.MemInfo.__init__ (self, ** kwargs)
Initializes a new MemInfo object.
Clients may call this method without parameters for default initialization. Clients should use MemInfo.from_iter() constructor to parse the contents of a .mem file.
Args: kwargs (dict): A dictionary as generated by the method MemInfo.as_dict(). This is provided as a shortcut to creating a MemInfo object from structured data such as the contents of a YAML file.
Definition at line 444 of file mem_info.py.
Member Function Documentation
as_dict()
def memory_model.mem_info.MemInfo.as_dict (self)
Returns a dictionary representation of this MemInfo object.
Returns: dict: A dictionary representation of the MemInfo object.
Definition at line 551 of file mem_info.py.
References memory_model.mem_info.MemInfo.inputs, memory_model.mem_info.MemInfo.keygens, memory_model.mem_info.MemInfo.metadata, and memory_model.mem_info.MemInfo.outputs.
Referenced by memory_model.mem_info.MemInfoVariable.__repr__(), common.run_config.RunConfig.__str__(), he_as.AssemblerRunConfig.__str__(), and he_link.LinkerRunConfig.__str__().
from_iter()
def memory_model.mem_info.MemInfo.from_iter (cls, line_iter)
Creates a new MemInfo object from an iterator of strings, where each string is a line of text to parse.
This constructor is intended to parse a .mem file.
Args: line_iter (iter): Iterator of strings. Each string is considered a line of text to parse.
Raises: RuntimeError: If there is an error parsing the lines.
Returns: MemInfo: The constructed MemInfo object.
Definition at line 466 of file mem_info.py.
References instructions.tokenizeFromLine().
inputs()
list memory_model.mem_info.MemInfo.inputs (self) private
Definition at line 518 of file mem_info.py.
References memory_model.mem_info.MemInfo.__inputs, and memory_model.mem_info.MemInfo.inputs.
Referenced by memory_model.mem_info.MemInfo.as_dict(), and memory_model.mem_info.MemInfo.validate().
keygens()
list memory_model.mem_info.MemInfo.keygens (self) private
Definition at line 506 of file mem_info.py.
References memory_model.mem_info.MemInfo.__keygens, and memory_model.mem_info.MemInfo.keygens.
Referenced by memory_model.mem_info.MemInfo.as_dict().
metadata()
Metadata memory_model.mem_info.MemInfo.metadata (self) private
Definition at line 542 of file mem_info.py.
References memory_model.mem_info.MemInfo.__metadata, and memory_model.mem_info.MemInfo.metadata.
Referenced by memory_model.mem_info.MemInfo.as_dict(), and memory_model.mem_info.MemInfo.validate().
outputs()
list memory_model.mem_info.MemInfo.outputs (self) private
Definition at line 530 of file mem_info.py.
References memory_model.mem_info.MemInfo.__outputs, and memory_model.mem_info.MemInfo.outputs.
Referenced by memory_model.mem_info.MemInfo.as_dict(), and memory_model.mem_info.MemInfo.validate().
validate()
def memory_model.mem_info.MemInfo.validate (self)
Validates the MemInfo object to ensure consistency and correctness.
Raises: RuntimeError: If the validation fails due to inconsistent metadata or duplicate variable names.
Definition at line 564 of file mem_info.py.
References memory_model.mem_info.MemInfo.inputs, memory_model.mem_info.MemInfo.metadata, and memory_model.mem_info.MemInfo.outputs.
Referenced by kerngen.high_parser.options_handler.OptionsIntDict.op_value().
Member Data Documentation
__inputs
memory_model.mem_info.MemInfo.__inputs private
Definition at line 446 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.inputs().
__keygens
memory_model.mem_info.MemInfo.__keygens private
Definition at line 445 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.keygens().
__metadata
memory_model.mem_info.MemInfo.__metadata private
Definition at line 448 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.metadata().
__outputs
memory_model.mem_info.MemInfo.__outputs private
Definition at line 447 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.outputs().
Const
memory_model.mem_info.MemInfo.Const = constants.MemInfo static
Definition at line 99 of file mem_info.py.
Property Documentation
inputs
memory_model.mem_info.MemInfo.inputs = property static
Retrieves the list of input variables.
Returns: list: Input variables.
Definition at line 516 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.as_dict(), memory_model.mem_info.MemInfo.inputs(), and memory_model.mem_info.MemInfo.validate().
keygens
memory_model.mem_info.MemInfo.keygens = property static
Retrieves the list of keygen variables.
Returns: list: Keygen variables.
Definition at line 504 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.as_dict(), and memory_model.mem_info.MemInfo.keygens().
metadata
memory_model.mem_info.MemInfo.metadata = property static
Retrieves the metadata associated with this MemInfo object.
Returns: Metadata: MemInfo's metadata.
Definition at line 540 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.as_dict(), memory_model.mem_info.MemInfo.metadata(), and memory_model.mem_info.MemInfo.validate().
outputs
memory_model.mem_info.MemInfo.outputs = property static
Retrieves the list of output variables.
Returns: list: Output variables.
Definition at line 528 of file mem_info.py.
Referenced by memory_model.mem_info.MemInfo.as_dict(), memory_model.mem_info.MemInfo.outputs(), and memory_model.mem_info.MemInfo.validate().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/memory_model/mem_info.py