Encrypted Computing SDK: pisa::PISAInstruction Class Reference
pisa::PISAInstruction Class Reference
The PISAInstruction class represents an instruction in the P-ISA instruction set. It is designed to be able to store all ISA instructions, not all elements are used for every instruction. The exact elements used by each instruction is stored in InstructionDesc.
#include <p_isa_instruction.h>
Public Member Functions
PISAInstruction (std::string name)
PISAInstruction (std::string name, InstructionDesc desc)
Operand & getInputOperand (int n)
Operand & getOutputOperand (int n)
void setInputOperand (const Operand &op, int n)
void setOutputOperand (const Operand &op, int n)
void addInputOperand (const Operand &op)
void addOutputOperand (const Operand &op)
int PMD () const
void setPMD (int newPmd_log2)
const std::string & Name () const
void setName (const std::string &newOperation_name)
int residual () const
void setResidual (int newResidual)
int numOutputOperands () const
int numInputOperands () const
int stage () const
void setStage (int newStage)
int block () const
void setBlock (int newBlock)
const WParam & wParam () const
void setWParam (const WParam &newW_param)
int galois_element () const
void setGalois_element (int newGalois_element)
const InstructionDesc getDescription () const
virtual PISAInstruction * create ()
bool outputBlock () const
void setOutputBlock (bool newOutput_block)
int groupId () const
void setGroupId (int newGroup_id)
Public Member Functions inherited from ISAInstruction
ISAInstruction ()=default
Static Public Member Functions
static std::string operationName ()
Protected Attributes
int m_pmd_log2
std::string m_operation_name
std::vector< Operand > m_input_operands
std::vector< Operand > m_output_operands
std::vector< int > m_additional_params
WParam m_w_param
int m_residual
int m_group_id
int m_stage
int m_galois_element
int m_block
bool m_output_block
InstructionDesc m_description
Friends
std::ostream & operator<< (std::ostream &stream, PISAInstruction instr)
Detailed Description
The PISAInstruction class represents an instruction in the P-ISA instruction set. It is designed to be able to store all ISA instructions, not all elements are used for every instruction. The exact elements used by each instruction is stored in InstructionDesc.
Definition at line 227 of file p_isa_instruction.h.
Constructor & Destructor Documentation
PISAInstruction() [1/2]
pisa::PISAInstruction::PISAInstruction (std::string name)
Definition at line 7 of file p_isa_instruction.cpp.
Referenced by create().
PISAInstruction() [2/2]
pisa::PISAInstruction::PISAInstruction (std::string name, InstructionDesc desc)
Definition at line 12 of file p_isa_instruction.cpp.
Member Function Documentation
addInputOperand()
void pisa::PISAInstruction::addInputOperand (const Operand & op)
Definition at line 40 of file p_isa_instruction.cpp.
References m_input_operands.
Referenced by pisa::instruction::Add::Add(), pisa::instruction::Copy::Copy(), pisa::instruction::Intt::Intt(), pisa::instruction::Mac::Mac(), pisa::instruction::Maci::Maci(), pisa::instruction::Mul::Mul(), pisa::instruction::Muli::Muli(), pisa::instruction::Ntt::Ntt(), pisa::PISAParser::parse_IMMEDIATE(), pisa::PISAParser::parse_INPUT_OPERAND(), pisa::PISAParser::parse_INPUT_OUTPUT_OPERAND(), and pisa::instruction::Sub::Sub().
addOutputOperand()
void pisa::PISAInstruction::addOutputOperand (const Operand & op)
Definition at line 45 of file p_isa_instruction.cpp.
References m_output_operands.
Referenced by pisa::instruction::Add::Add(), pisa::instruction::Copy::Copy(), pisa::instruction::Intt::Intt(), pisa::instruction::Mac::Mac(), pisa::instruction::Maci::Maci(), pisa::instruction::Mul::Mul(), pisa::instruction::Muli::Muli(), pisa::instruction::Ntt::Ntt(), pisa::PISAParser::parse_INPUT_OUTPUT_OPERAND(), pisa::PISAParser::parse_OUTPUT_OPERAND(), and pisa::instruction::Sub::Sub().
block()
int pisa::PISAInstruction::block () const
Definition at line 100 of file p_isa_instruction.cpp.
References m_block.
Referenced by instructions.xinst.twintt.Instruction::__repr__(), instructions.xinst.twntt.Instruction::__repr__(), instructions.xinst.twintt.Instruction::_toPISAFormat(), instructions.xinst.twntt.Instruction::_toPISAFormat(), instructions.xinst.twintt.Instruction::_toXASMISAFormat(), and instructions.xinst.twntt.Instruction::_toXASMISAFormat().
create()
PISAInstruction * pisa::PISAInstruction::create () virtual
Reimplemented in pisa::instruction::Copy, pisa::instruction::Muli, pisa::instruction::Ntt, pisa::instruction::Intt, pisa::instruction::Maci, pisa::instruction::Mac, pisa::instruction::Mul, pisa::instruction::Sub, and pisa::instruction::Add.
Definition at line 131 of file p_isa_instruction.cpp.
References PISAInstruction().
Referenced by pisa::PISAParser::parseInstruction().
galois_element()
int pisa::PISAInstruction::galois_element () const
Definition at line 111 of file p_isa_instruction.cpp.
References m_galois_element.
Referenced by pisa::instruction::Intt::Intt(), and pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute().
getDescription()
const InstructionDesc pisa::PISAInstruction::getDescription () const
Definition at line 126 of file p_isa_instruction.cpp.
References m_description.
Referenced by pisa::PISAParser::parseInstruction().
getInputOperand()
Operand & pisa::PISAInstruction::getInputOperand (int n)
Definition at line 18 of file p_isa_instruction.cpp.
References m_input_operands, and m_output_block.
Referenced by pisa::PISAFunctionalModel< T >::addInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::copyInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::decode(), pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::maciInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::macInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::muliInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::mulInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::readInput(), and pisa::PISAFunctionalModel< T >::subInstrDecodeExecute().
getOutputOperand()
Operand & pisa::PISAInstruction::getOutputOperand (int n)
Definition at line 24 of file p_isa_instruction.cpp.
References m_output_block, and m_output_operands.
Referenced by pisa::PISAFunctionalModel< T >::addInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::copyInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::decode(), pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::maciInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::macInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::muliInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::mulInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::readOutput(), and pisa::PISAFunctionalModel< T >::subInstrDecodeExecute().
groupId()
int pisa::PISAInstruction::groupId () const
Definition at line 156 of file p_isa_instruction.cpp.
References m_group_id.
Name()
const std::string & pisa::PISAInstruction::Name () const
Definition at line 60 of file p_isa_instruction.cpp.
References m_operation_name.
Referenced by pisa::PISAFunctionalModel< T >::decode().
numInputOperands()
int pisa::PISAInstruction::numInputOperands () const
Definition at line 85 of file p_isa_instruction.cpp.
References m_input_operands.
Referenced by pisa::PISAFunctionalModel< T >::readInput().
numOutputOperands()
int pisa::PISAInstruction::numOutputOperands () const
Definition at line 80 of file p_isa_instruction.cpp.
References m_output_operands.
Referenced by pisa::PISAFunctionalModel< T >::readOutput().
operationName()
std::string pisa::PISAInstruction::operationName () static
Definition at line 121 of file p_isa_instruction.cpp.
outputBlock()
bool pisa::PISAInstruction::outputBlock () const
Definition at line 146 of file p_isa_instruction.cpp.
References m_output_block.
PMD()
int pisa::PISAInstruction::PMD () const
Definition at line 50 of file p_isa_instruction.cpp.
References m_pmd_log2.
Referenced by pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), and pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute().
residual()
int pisa::PISAInstruction::residual () const
Definition at line 70 of file p_isa_instruction.cpp.
References m_residual.
Referenced by pisa::instruction::Add::Add(), pisa::PISAFunctionalModel< T >::addInstrDecodeExecute(), pisa::instruction::Intt::Intt(), pisa::instruction::Mac::Mac(), pisa::instruction::Maci::Maci(), pisa::PISAFunctionalModel< T >::maciInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::macInstrDecodeExecute(), pisa::instruction::Mul::Mul(), pisa::instruction::Muli::Muli(), pisa::PISAFunctionalModel< T >::muliInstrDecodeExecute(), pisa::PISAFunctionalModel< T >::mulInstrDecodeExecute(), pisa::instruction::Ntt::Ntt(), pisa::instruction::Sub::Sub(), and pisa::PISAFunctionalModel< T >::subInstrDecodeExecute().
setBlock()
void pisa::PISAInstruction::setBlock (int newBlock)
Definition at line 105 of file p_isa_instruction.cpp.
References m_block.
Referenced by pisa::PISAParser::parse_BLOCK().
setGalois_element()
void pisa::PISAInstruction::setGalois_element (int newGalois_element)
Definition at line 116 of file p_isa_instruction.cpp.
References m_galois_element.
Referenced by pisa::instruction::Intt::Intt(), and pisa::PISAParser::parse_GALOIS_ELEMENT().
setGroupId()
void pisa::PISAInstruction::setGroupId (int newGroup_id)
Definition at line 161 of file p_isa_instruction.cpp.
References m_group_id.
Referenced by pisa::PISAParser::parse_GROUP_ID().
setInputOperand()
void pisa::PISAInstruction::setInputOperand (const Operand & op, int n)
Definition at line 30 of file p_isa_instruction.cpp.
References m_input_operands.
setName()
void pisa::PISAInstruction::setName (const std::string & newOperation_name)
Definition at line 65 of file p_isa_instruction.cpp.
References m_operation_name.
Referenced by pisa::PISAParser::parse_OP_NAME().
setOutputBlock()
void pisa::PISAInstruction::setOutputBlock (bool newOutput_block)
Definition at line 151 of file p_isa_instruction.cpp.
References m_output_block.
setOutputOperand()
void pisa::PISAInstruction::setOutputOperand (const Operand & op, int n)
Definition at line 35 of file p_isa_instruction.cpp.
References m_output_operands.
setPMD()
void pisa::PISAInstruction::setPMD (int newPmd_log2)
Definition at line 55 of file p_isa_instruction.cpp.
References m_pmd_log2.
Referenced by pisa::instruction::Add::Add(), pisa::instruction::Copy::Copy(), pisa::instruction::Intt::Intt(), pisa::instruction::Mac::Mac(), pisa::instruction::Maci::Maci(), pisa::instruction::Mul::Mul(), pisa::instruction::Muli::Muli(), pisa::instruction::Ntt::Ntt(), pisa::PISAParser::parse_POLYMOD_DEG_LOG2(), and pisa::instruction::Sub::Sub().
setResidual()
void pisa::PISAInstruction::setResidual (int newResidual)
Definition at line 75 of file p_isa_instruction.cpp.
References m_residual.
Referenced by pisa::instruction::Add::Add(), pisa::instruction::Intt::Intt(), pisa::instruction::Mac::Mac(), pisa::instruction::Maci::Maci(), pisa::instruction::Mul::Mul(), pisa::instruction::Muli::Muli(), pisa::instruction::Ntt::Ntt(), pisa::PISAParser::parse_RESIDUAL(), and pisa::instruction::Sub::Sub().
setStage()
void pisa::PISAInstruction::setStage (int newStage)
Definition at line 95 of file p_isa_instruction.cpp.
References m_stage.
Referenced by pisa::PISAParser::parse_STAGE().
setWParam()
void pisa::PISAInstruction::setWParam (const WParam & newW_param)
Definition at line 141 of file p_isa_instruction.cpp.
References m_w_param.
Referenced by pisa::instruction::Intt::Intt(), pisa::instruction::Ntt::Ntt(), and pisa::PISAParser::parse_W_PARAM().
stage()
int pisa::PISAInstruction::stage () const
Definition at line 90 of file p_isa_instruction.cpp.
References m_stage.
Referenced by instructions.xinst.twintt.Instruction::__repr__(), instructions.xinst.twntt.Instruction::__repr__(), instructions.xinst.intt.Instruction::_toPISAFormat(), instructions.xinst.ntt.Instruction::_toPISAFormat(), instructions.xinst.twintt.Instruction::_toPISAFormat(), instructions.xinst.twntt.Instruction::_toPISAFormat(), instructions.xinst.intt.Instruction::_toXASMISAFormat(), instructions.xinst.ntt.Instruction::_toXASMISAFormat(), instructions.xinst.twintt.Instruction::_toXASMISAFormat(), and instructions.xinst.twntt.Instruction::_toXASMISAFormat().
wParam()
const WParam & pisa::PISAInstruction::wParam () const
Definition at line 136 of file p_isa_instruction.cpp.
References m_w_param.
Referenced by pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute(), and pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, PISAInstruction instr) friend
Definition at line 255 of file p_isa_instruction.h.
Member Data Documentation
m_additional_params
std::vector<int> pisa::PISAInstruction::m_additional_params protected
Definition at line 350 of file p_isa_instruction.h.
m_block
int pisa::PISAInstruction::m_block protected
Definition at line 358 of file p_isa_instruction.h.
Referenced by block(), and setBlock().
m_description
InstructionDesc pisa::PISAInstruction::m_description protected
Definition at line 361 of file p_isa_instruction.h.
Referenced by getDescription().
m_galois_element
int pisa::PISAInstruction::m_galois_element protected
Definition at line 356 of file p_isa_instruction.h.
Referenced by galois_element(), pisa::instruction::Intt::Intt(), and setGalois_element().
m_group_id
int pisa::PISAInstruction::m_group_id protected
Definition at line 353 of file p_isa_instruction.h.
Referenced by groupId(), and setGroupId().
m_input_operands
std::vector<Operand> pisa::PISAInstruction::m_input_operands protected
Definition at line 348 of file p_isa_instruction.h.
Referenced by addInputOperand(), getInputOperand(), numInputOperands(), and setInputOperand().
m_operation_name
std::string pisa::PISAInstruction::m_operation_name protected
Definition at line 347 of file p_isa_instruction.h.
Referenced by Name(), and setName().
m_output_block
bool pisa::PISAInstruction::m_output_block protected
Definition at line 360 of file p_isa_instruction.h.
Referenced by getInputOperand(), getOutputOperand(), outputBlock(), and setOutputBlock().
m_output_operands
std::vector<Operand> pisa::PISAInstruction::m_output_operands protected
Definition at line 349 of file p_isa_instruction.h.
Referenced by addOutputOperand(), getOutputOperand(), numOutputOperands(), and setOutputOperand().
m_pmd_log2
int pisa::PISAInstruction::m_pmd_log2 protected
Definition at line 346 of file p_isa_instruction.h.
Referenced by PMD(), and setPMD().
m_residual
int pisa::PISAInstruction::m_residual protected
Definition at line 352 of file p_isa_instruction.h.
Referenced by pisa::instruction::Copy::Copy(), residual(), and setResidual().
m_stage
int pisa::PISAInstruction::m_stage protected
Definition at line 354 of file p_isa_instruction.h.
Referenced by setStage(), and stage().
m_w_param
WParam pisa::PISAInstruction::m_w_param protected
Definition at line 351 of file p_isa_instruction.h.
Referenced by setWParam(), and wParam().
The documentation for this class was generated from the following files:
p-isa_tools/common/p_isa/p_isa_instruction.h
p-isa_tools/common/p_isa/p_isa_instruction.cpp