Encrypted Computing SDK: PISAGraphOptimizer Class Reference
PISAGraphOptimizer Class Reference
#include <pisa_graph_optimizer.h>
Public Member Functions
PISAGraphOptimizer ()
std::vector< pisa::PISAInstruction * > generateInstructionStreamFromGraph (graph::Graph< pisa::PISAInstruction > &p_isa_graph, bool fixed_order, std::vector< pisa::PISAInstruction * > instr_order)
void isolateGraphVariables (graph::Graph< pisa::PISAInstruction > &p_isa_graph, std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction >>> &layers)
void applyDuplicateInputVariableSeparation (std::vector< pisa::PISAInstruction * > &instr_order)
void nodeLocklist (graph::NetworkNode< pisa::PISAInstruction > &node, graph::Graph< pisa::PISAInstruction > &p_isa_graph)
void nodeVariableAdjustment (graph::NetworkNode< pisa::PISAInstruction > &node, graph::Graph< pisa::PISAInstruction > &p_isa_graph)
void nodeMACVariableAdjustment (graph::NetworkNode< pisa::PISAInstruction > &node, graph::Graph< pisa::PISAInstruction > &p_isa_graph)
void nodeInstructionAdjustment (graph::NetworkNode< pisa::PISAInstruction > &node, graph::Graph< pisa::PISAInstruction > &p_isa_graph)
Public Attributes
int unique_counter = 1
bool perform_variable_isolation = false
std::map< std::string, bool > rename_lock_list
Detailed Description
Definition at line 10 of file pisa_graph_optimizer.h.
Constructor & Destructor Documentation
PISAGraphOptimizer()
PISAGraphOptimizer::PISAGraphOptimizer ()
Definition at line 6 of file pisa_graph_optimizer.cpp.
Member Function Documentation
applyDuplicateInputVariableSeparation()
void PISAGraphOptimizer::applyDuplicateInputVariableSeparation (std::vector< pisa::PISAInstruction * > & instr_order)
Definition at line 106 of file pisa_graph_optimizer.cpp.
References instructions.xinst::Copy, and order_test::match.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
generateInstructionStreamFromGraph()
std::vector< pisa::PISAInstruction * > PISAGraphOptimizer::generateInstructionStreamFromGraph (graph::Graph< pisa::PISAInstruction > & p_isa_graph, bool fixed_order, std::vector< pisa::PISAInstruction * > instr_order)
Definition at line 10 of file pisa_graph_optimizer.cpp.
References graph::Graph< INSTRUCTION >::clone(), graph::Graph< INSTRUCTION >::getNodes(), isolateGraphVariables(), graph::OPERATION, and perform_variable_isolation.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
isolateGraphVariables()
void PISAGraphOptimizer::isolateGraphVariables (graph::Graph< pisa::PISAInstruction > & p_isa_graph, std::vector< std::vector< graph::NetworkNode< pisa::PISAInstruction >>> & layers)
Definition at line 68 of file pisa_graph_optimizer.cpp.
References nodeInstructionAdjustment(), nodeLocklist(), and nodeVariableAdjustment().
Referenced by generateInstructionStreamFromGraph().
nodeInstructionAdjustment()
void PISAGraphOptimizer::nodeInstructionAdjustment (graph::NetworkNode< pisa::PISAInstruction > & node, graph::Graph< pisa::PISAInstruction > & p_isa_graph)
Definition at line 224 of file pisa_graph_optimizer.cpp.
References pisa::instruction::Mac::baseName, pisa::instruction::Muli::baseName, graph::Graph< INSTRUCTION >::getNode(), and graph::IMMEDIATE.
Referenced by isolateGraphVariables().
nodeLocklist()
void PISAGraphOptimizer::nodeLocklist (graph::NetworkNode< pisa::PISAInstruction > & node, graph::Graph< pisa::PISAInstruction > & p_isa_graph)
Definition at line 170 of file pisa_graph_optimizer.cpp.
References pisa::instruction::Mac::baseName, graph::Graph< INSTRUCTION >::getNode(), and rename_lock_list.
Referenced by isolateGraphVariables().
nodeMACVariableAdjustment()
void PISAGraphOptimizer::nodeMACVariableAdjustment (graph::NetworkNode< pisa::PISAInstruction > & node, graph::Graph< pisa::PISAInstruction > & p_isa_graph)
Definition at line 204 of file pisa_graph_optimizer.cpp.
References pisa::instruction::Mac::baseName, and graph::Graph< INSTRUCTION >::getNode().
nodeVariableAdjustment()
void PISAGraphOptimizer::nodeVariableAdjustment (graph::NetworkNode< pisa::PISAInstruction > & node, graph::Graph< pisa::PISAInstruction > & p_isa_graph)
Definition at line 186 of file pisa_graph_optimizer.cpp.
References graph::Graph< INSTRUCTION >::getNode(), rename_lock_list, and unique_counter.
Referenced by isolateGraphVariables().
Member Data Documentation
perform_variable_isolation
bool PISAGraphOptimizer::perform_variable_isolation = false
Definition at line 29 of file pisa_graph_optimizer.h.
Referenced by generateInstructionStreamFromGraph().
rename_lock_list
std::map<std::string, bool> PISAGraphOptimizer::rename_lock_list
Definition at line 30 of file pisa_graph_optimizer.h.
Referenced by nodeLocklist(), and nodeVariableAdjustment().
unique_counter
int PISAGraphOptimizer::unique_counter = 1
Definition at line 28 of file pisa_graph_optimizer.h.
Referenced by nodeVariableAdjustment().
The documentation for this class was generated from the following files:
p-isa_tools/program_mapper/p_isa/pisa_graph_optimizer.h
p-isa_tools/program_mapper/p_isa/pisa_graph_optimizer.cpp