Encrypted Computing SDK: RandomStreamInstructionTest Class Reference
RandomStreamInstructionTest Class Reference
#include <random_instr_stream_instruction_test.h>
Public Member Functions
RandomStreamInstructionTest ()
void constructTest () override
pisa::PISAInstruction * createInstr (std::string op, std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createAddInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createMulInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createMacInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createMaciInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createMuliInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createSubInstr (std::string output, std::string input0, std::string input1)
pisa::PISAInstruction * createCopyInstr (std::string output, std::string input0)
Public Member Functions inherited from PisaInstructionTest
PisaInstructionTest ()
const std::vector< pisa::PISAInstruction * > & getInstructionTrace ()
std::map< std::string, std::string > & getConfiguration ()
Static Public Member Functions
static std::string operationName ()
Additional Inherited Members
Protected Attributes inherited from PisaInstructionTest
std::vector< pisa::PISAInstruction * > instruction_trace
bool created = false
std::map< std::string, std::string > configuration
Detailed Description
Definition at line 15 of file random_instr_stream_instruction_test.h.
Constructor & Destructor Documentation
RandomStreamInstructionTest()
RandomStreamInstructionTest::RandomStreamInstructionTest ()
Definition at line 42 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and operationName().
Member Function Documentation
constructTest()
void RandomStreamInstructionTest::constructTest () override virtual
Reimplemented from PisaInstructionTest.
Definition at line 57 of file random_instr_stream_instruction_test.h.
References he_as::config, PisaInstructionTest::configuration, PisaInstructionTest::created, createInstr(), and PisaInstructionTest::instruction_trace.
createAddInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createAddInstr (std::string output, std::string input0, std::string input1)
Definition at line 194 of file random_instr_stream_instruction_test.h.
References instructions.xinst::Add, and PisaInstructionTest::configuration.
Referenced by createInstr().
createCopyInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createCopyInstr (std::string output, std::string input0)
Definition at line 248 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Copy.
Referenced by createInstr().
createInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createInstr (std::string op, std::string output, std::string input0, std::string input1)
Definition at line 159 of file random_instr_stream_instruction_test.h.
References createAddInstr(), createCopyInstr(), createMaciInstr(), createMacInstr(), createMuliInstr(), createMulInstr(), and createSubInstr().
Referenced by constructTest().
createMaciInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createMaciInstr (std::string output, std::string input0, std::string input1)
Definition at line 221 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Maci.
Referenced by createInstr().
createMacInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createMacInstr (std::string output, std::string input0, std::string input1)
Definition at line 212 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Mac.
Referenced by createInstr().
createMuliInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createMuliInstr (std::string output, std::string input0, std::string input1)
Definition at line 230 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Muli.
Referenced by createInstr().
createMulInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createMulInstr (std::string output, std::string input0, std::string input1)
Definition at line 203 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Mul.
Referenced by createInstr().
createSubInstr()
pisa::PISAInstruction * RandomStreamInstructionTest::createSubInstr (std::string output, std::string input0, std::string input1)
Definition at line 239 of file random_instr_stream_instruction_test.h.
References PisaInstructionTest::configuration, and instructions.xinst::Sub.
Referenced by createInstr().
operationName()
std::string RandomStreamInstructionTest::operationName () static
Definition at line 37 of file random_instr_stream_instruction_test.h.
Referenced by RandomStreamInstructionTest().
The documentation for this class was generated from the following file:
p-isa_tools/program_mapper/p_isa/tests/pisa_instruction_tests/random_instr_stream_instruction_test.h