Encrypted Computing SDK: memory_model.variable.DummyVariable Class Reference
memory_model.variable.DummyVariable Class Reference
Represents a dummy variable used as a placeholder.
Public Member Functions
def __init__ (self, tag=None)
Initializes a new DummyVariable object.
Public Member Functions inherited from memory_model.variable.Variable
def parseFromPISAFormat (cls, str s_pisa)
Parses a Variable from P-ISA format and return a tuple that can be used to construct a Variable object.
bool validateName (cls, str name)
Validates whether a name is an appropriate identifier for a variable.
def __init__ (self, str var_name, int suggested_bank=-1)
Constructs a new Variable object with a specified name and suggested bank number.
def __repr__ (self)
Returns a string representation of the Variable object.
def __str__ (self)
Returns the name of the variable as its string representation.
def __eq__ (self, other)
Checks equality with another Variable object.
def __hash__ (self)
Returns the hash of the variable's name.
str toPISAFormat (self)
Converts the variable to P-ISA kernel format.
str toXASMISAFormat (self)
Converts the variable to XInst ASM-ISA format.
str toCASMISAFormat (self)
Converts the variable to CInst ASM-ISA format.
str toMASMISAFormat (self)
Converts the variable to MInst ASM-ISA format.
Public Attributes
tag
Public Attributes inherited from memory_model.variable.Variable
hbm_address
accessed_by_xinsts
last_x_access
Private Member Functions
def _get_var_name (self)
def _set_register (self, value)
def _set_spad_address (self, int value)
Additional Inherited Members
Properties inherited from memory_model.variable.Variable
name = property
Gets the name of the variable.
suggested_bank = property
Gets or sets the suggested bank for the variable.
register = property
Gets or sets the register for this variable.
register_dirty = property
Gets or sets whether the register for this variable is "dirty".
spad_address = property
Gets or sets the SPAD address for this variable.
spad_dirty = property
Gets or sets whether the SPAD location for this variable is "dirty".
Detailed Description
Represents a dummy variable used as a placeholder.
A dummy variable serves as a placeholder to indicate registers that will be available in the next bundle, but not in the current one, such as after a move operation. It can be identified by its empty name.
Definition at line 414 of file variable.py.
Constructor & Destructor Documentation
__init__()
def memory_model.variable.DummyVariable.__init__ (self, tag = None)
Initializes a new DummyVariable object.
Args: tag (optional): An optional tag to associate with the dummy variable. Defaults to 0 if not provided.
Definition at line 425 of file variable.py.
Member Function Documentation
_get_var_name()
def memory_model.variable.DummyVariable._get_var_name (self) private
   Get the name of the dummy variable.
   Returns:
       str: An empty string, indicating the variable is a dummy.
Reimplemented from memory_model.variable.Variable.
Definition at line 437 of file variable.py.
Referenced by memory_model.variable.Variable.name().
_set_register()
def memory_model.variable.DummyVariable._set_register (self, value) private
   Overrides the method to set the register for the dummy variable.
   This method does nothing for a dummy variable.
Reimplemented from memory_model.variable.Variable.
Definition at line 447 of file variable.py.
Referenced by memory_model.variable.Variable.register().
_set_spad_address()
def memory_model.variable.DummyVariable._set_spad_address (self, int value) private
   Overrides the method to set the SPAD address for the dummy variable.
   This method does nothing for a dummy variable.
Reimplemented from memory_model.variable.Variable.
Definition at line 457 of file variable.py.
Referenced by memory_model.variable.Variable.spad_address().
Member Data Documentation
tag
memory_model.variable.DummyVariable.tag
Definition at line 427 of file variable.py.
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/memory_model/variable.py