Encrypted Computing SDK: memory_model.register_file.RegisterBank Class Reference
memory_model.register_file.RegisterBank Class Reference
Encapsulates a register bank.
Classes
class __RBIterator
Public Member Functions
def __init__ (self, int bank_index, range register_range=None)
Constructs a new RegisterBank object.
def __iter__ (self)
Returns an iterator over the registers in the register bank.
def __repr__ (self)
Returns a string representation of the RegisterBank object.
def getRegister (self, int idx)
Retrieves the register associated with the specified index.
def findAvailableRegister (self, live_var_names, str replacement_policy=None)
Retrieve the next available register or propose a register to use if all are occupied.
def dump (self, ostream)
Dump the current state of the register bank to the specified output stream.
Properties
bank_index = property
Gets the index of the bank.
register_count = property
Gets the number of registers in this bank.
Private Member Functions
int bank_index (self)
int register_count (self)
Private Attributes
__bank_index
__registers
Detailed Description
Encapsulates a register bank.
This class provides an iterable over the registers contained in the register bank and offers methods to retrieve and manage registers.
Properties: bank_index (int): Index for the bank as specified during construction. register_count (int): Number of registers contained in the bank.
Methods: getRegister(idx: int) -> Register: Retrieves the register associated with the specified index.
findAvailableRegister(live_var_names, replacement_policy: str) -> Register: Retrieves the next available register or proposes a register to use if all are occupied, based on a replacement policy.
Definition at line 25 of file register_file.py.
Constructor & Destructor Documentation
__init__()
def memory_model.register_file.RegisterBank.__init__ (self, int bank_index, range register_range = None)
Constructs a new RegisterBank object.
Args: bank_index (int): Zero-based index for the bank to create. The memory model typically has 4 banks, but this is flexible to create more banks if needed. register_range (range, optional): A range for the indices of the registers contained in this register bank. Defaults to range(constants.MemoryModel.NUM_REGISTER_PER_BANKS).
Raises: ValueError: If the bank index is negative or if the register range is invalid.
Definition at line 60 of file register_file.py.
Member Function Documentation
__iter__()
def memory_model.register_file.RegisterBank.__iter__ (self)
Returns an iterator over the registers in the register bank.
Returns: __RBIterator: An iterator over the registers.
Definition at line 87 of file register_file.py.
__repr__()
def memory_model.register_file.RegisterBank.__repr__ (self)
Returns a string representation of the RegisterBank object.
Returns: str: A string representation of the RegisterBank.
Definition at line 96 of file register_file.py.
References memory_model.register_file.RegisterBank.bank_index, and inject_bundles.type.
bank_index()
int memory_model.register_file.RegisterBank.bank_index (self) private
Definition at line 113 of file register_file.py.
References memory_model.register_file.RegisterBank.__bank_index, and memory_model.register_file.RegisterBank.bank_index.
Referenced by memory_model.register_file.RegisterBank.__repr__().
dump()
def memory_model.register_file.RegisterBank.dump (self, ostream)
Dump the current state of the register bank to the specified output stream.
Args: ostream: The output stream to write the register bank state to.
Definition at line 180 of file register_file.py.
References memory_model.register_file.RegisterBank.getRegister(), and memory_model.register_file.RegisterBank.register_count.
findAvailableRegister()
def memory_model.register_file.RegisterBank.findAvailableRegister (self, live_var_names, str replacement_policy = None)
Retrieve the next available register or propose a register to use if all are occupied.
Args: live_var_names (set or list): A set of variable names containing the variables that are not available for replacement i.e. live variables. This is used to avoid replacing variables that were just allocated as dependencies for an upcoming instruction.
replacement_policy (str, optional): If specified, it must be a value from Constants.REPLACEMENT_POLICIES. Otherwise, this method will not find a location to replace if all registers are occupied. Values:
Constants.REPLACEMENT_POLICY_FTBU: suggests replacement of variable that is furthest accessed (using LRU and number of usages left as tie breakers).
Constants.REPLACEMENT_POLICY_LRU: suggests replacement of the least recently accessed variable.
Returns: Register: The first empty register, or the register to replace if all are occupied. Returns None if no suitable register is found.
Definition at line 166 of file register_file.py.
References memory_model.register_file.RegisterBank.__registers, and memory_model.register_file.RegisterBank.getRegister().
getRegister()
def memory_model.register_file.RegisterBank.getRegister (self, int idx)
Retrieves the register associated with the specified index.
Args: idx (int): Index for the register to retrieve. This can be a negative value.
Returns: Register: The register associated with the specified index.
Raises: ValueError: If the index is out of range.
Definition at line 140 of file register_file.py.
References memory_model.register_file.RegisterBank.__registers, and memory_model.register_file.RegisterBank.register_count.
Referenced by memory_model.register_file.RegisterBank.__RBIterator.__next__(), memory_model.register_file.RegisterBank.dump(), and memory_model.register_file.RegisterBank.findAvailableRegister().
register_count()
int memory_model.register_file.RegisterBank.register_count (self) private
Definition at line 125 of file register_file.py.
References memory_model.register_file.RegisterBank.__registers, and memory_model.register_file.RegisterBank.register_count.
Referenced by memory_model.register_file.RegisterBank.dump(), and memory_model.register_file.RegisterBank.getRegister().
Member Data Documentation
__bank_index
memory_model.register_file.RegisterBank.__bank_index private
Definition at line 74 of file register_file.py.
Referenced by memory_model.register_file.RegisterBank.bank_index().
__registers
memory_model.register_file.RegisterBank.__registers private
Definition at line 76 of file register_file.py.
Referenced by memory_model.register_file.RegisterBank.findAvailableRegister(), memory_model.register_file.RegisterBank.getRegister(), and memory_model.register_file.RegisterBank.register_count().
Property Documentation
bank_index
memory_model.register_file.RegisterBank.bank_index = property static
Gets the index of the bank.
Returns: int: The index of the bank.
Definition at line 111 of file register_file.py.
Referenced by memory_model.register_file.RegisterBank.__repr__(), and memory_model.register_file.RegisterBank.bank_index().
register_count
memory_model.register_file.RegisterBank.register_count = property static
Gets the number of registers in this bank.
Returns: int: The number of registers.
Definition at line 123 of file register_file.py.
Referenced by memory_model.register_file.RegisterBank.dump(), memory_model.register_file.RegisterBank.getRegister(), and memory_model.register_file.RegisterBank.register_count().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/memory_model/register_file.py