Encrypted Computing SDK: common.cycle_tracking.PrioritizedPlaceholder Class Reference
common.cycle_tracking.PrioritizedPlaceholder Class Reference
Base class for priority queue items.
Public Member Functions
def __init__ (self, priority=(0, 0), priority_delta=(0, 0))
Initializes a new PrioritizedPlaceholder object.
def __lt__ (self, other)
Compares this item with another item for less-than ordering based on priority.
def __eq__ (self, other)
Compares this item with another item for equality based on priority.
def __gt__ (self, other)
Compares this item with another item for greater-than ordering based on priority.
Properties
priority = property
Calculates and returns the current priority of the item.
priority_delta = property
Returns the current priority delta.
Private Member Functions
def priority (self)
def priority_delta (self)
def _get_priority (self)
def _get_priority_delta (self)
Private Attributes
_priority
_priority_delta
Detailed Description
Base class for priority queue items.
This class provides a framework for items that can be used in a priority queue, where each item has a priority that can be dynamically adjusted. Derived classes can override the _get_priority() method to provide their own logic for determining priority, allowing for priorities that change on the fly.
Priorities are expected to be tuples, and the class supports comparison operations based on these priorities.
Properties: priority (tuple): The current priority of the item, calculated as the sum of the base priority and the priority delta. priority_delta (tuple): The current priority delta.
Methods: _get_priority(): Returns the base priority of the item. _get_priority_delta(): Returns the priority delta of the item.
Definition at line 24 of file cycle_tracking.py.
Constructor & Destructor Documentation
__init__()
def common.cycle_tracking.PrioritizedPlaceholder.__init__ (self, priority = (0, 0), priority_delta = (0, 0))
Initializes a new PrioritizedPlaceholder object.
Args: priority (tuple, optional): The base priority of the item. Defaults to (0, 0). priority_delta (tuple, optional): The delta to be applied to the base priority. Defaults to (0, 0).
Definition at line 32 of file cycle_tracking.py.
Member Function Documentation
__eq__()
def common.cycle_tracking.PrioritizedPlaceholder.__eq__ (self, other)
Compares this item with another item for equality based on priority.
Args: other (PrioritizedPlaceholder): The other item to compare against.
Returns: bool: True if this item's priority is equal to the other item's priority, False otherwise.
Definition at line 109 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder.priority.
__gt__()
def common.cycle_tracking.PrioritizedPlaceholder.__gt__ (self, other)
Compares this item with another item for greater-than ordering based on priority.
Args: other (PrioritizedPlaceholder): The other item to compare against.
Returns: bool: True if this item's priority is greater than the other item's priority, False otherwise.
Definition at line 121 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder.priority.
__lt__()
def common.cycle_tracking.PrioritizedPlaceholder.__lt__ (self, other)
Compares this item with another item for less-than ordering based on priority.
Args: other (PrioritizedPlaceholder): The other item to compare against.
Returns: bool: True if this item's priority is less than the other item's priority, False otherwise.
Definition at line 97 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder.priority.
_get_priority()
def common.cycle_tracking.PrioritizedPlaceholder._get_priority (self) private
   Returns the base priority of the item.
   Returns:
       tuple: The base priority.
Definition at line 72 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder._priority.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.priority().
_get_priority_delta()
def common.cycle_tracking.PrioritizedPlaceholder._get_priority_delta (self) private
   Returns the priority delta of the item.
   This method can be overridden by derived classes to provide custom priority delta logic.
   Returns:
       tuple: The priority delta.
Definition at line 85 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder._priority_delta.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.priority_delta().
priority()
def common.cycle_tracking.PrioritizedPlaceholder.priority (self) private
Definition at line 49 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder._get_priority(), common.cycle_tracking.PrioritizedPlaceholder.priority, and common.cycle_tracking.PrioritizedPlaceholder.priority_delta.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.__eq__(), common.cycle_tracking.PrioritizedPlaceholder.__gt__(), and common.cycle_tracking.PrioritizedPlaceholder.__lt__().
priority_delta()
def common.cycle_tracking.PrioritizedPlaceholder.priority_delta (self) private
Definition at line 61 of file cycle_tracking.py.
References common.cycle_tracking.PrioritizedPlaceholder._get_priority_delta(), and common.cycle_tracking.PrioritizedPlaceholder.priority_delta.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.priority().
Member Data Documentation
_priority
common.cycle_tracking.PrioritizedPlaceholder._priority private
Definition at line 35 of file cycle_tracking.py.
Referenced by common.cycle_tracking.PrioritizedPlaceholder._get_priority().
_priority_delta
common.cycle_tracking.PrioritizedPlaceholder._priority_delta private
Definition at line 36 of file cycle_tracking.py.
Referenced by common.cycle_tracking.PrioritizedPlaceholder._get_priority_delta().
Property Documentation
priority
common.cycle_tracking.PrioritizedPlaceholder.priority = property static
Calculates and returns the current priority of the item.
The current priority is the sum of the base priority and the priority delta.
Returns: tuple: The current priority.
Definition at line 47 of file cycle_tracking.py.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.__eq__(), common.cycle_tracking.PrioritizedPlaceholder.__gt__(), common.cycle_tracking.PrioritizedPlaceholder.__lt__(), and common.cycle_tracking.PrioritizedPlaceholder.priority().
priority_delta
common.cycle_tracking.PrioritizedPlaceholder.priority_delta = property static
Returns the current priority delta.
Returns: tuple: The current delta.
Definition at line 59 of file cycle_tracking.py.
Referenced by common.cycle_tracking.PrioritizedPlaceholder.priority(), and common.cycle_tracking.PrioritizedPlaceholder.priority_delta().
The documentation for this class was generated from the following file:
assembler_tools/hec-assembler-tools/assembler/common/cycle_tracking.py