Encrypted Computing SDK: PisaTestGenerator Class Reference
PisaTestGenerator Class Reference
#include <pisa_test_generator.h>
Public Member Functions
PisaTestGenerator ()
graph::Graph< pisa::PISAInstruction > generateGraphFromProgramTrace (ProgramTrace program_trace)
graph::Graph< pisa::PISAInstruction > generateGraphFromHEOperationTrace (std::vector< pisa::poly::PolyOperation * > program_trace)
graph::Graph< pisa::PISAInstruction > generateGraphFromPISAInstructions (std::vector< pisa::PISAInstruction * > instructions)
void populateCalculatedOutputResults (std::vector< pisa::PISAInstruction * > instructions, json &input)
json generateJSONForGraph (graph::Graph< pisa::PISAInstruction > p_isa_graph, pisa::testgenerator::InputGenerationMode gen_mode=pisa::testgenerator::InputGenerationMode::SINGLE_ONE, unsigned int random_seed=0)
int findMaxRNSNumber (json &input_json)
void addMetaDataInformation (json &input_json, int RNS_NUM)
void addMetaDataInformation (json &input_json)
void convertPolyRnsChunkToPolyRns (json &input_json)
void convertPolyRnsChunkToPolyRnsHelper (json &input_json)
void writeJSON (json input_json, std::string file_name)
Public Attributes
json trace_file
int block_size = 8192
int modulus_value = 32684
Detailed Description
Definition at line 33 of file pisa_test_generator.h.
Constructor & Destructor Documentation
PisaTestGenerator()
PisaTestGenerator::PisaTestGenerator ()
Definition at line 13 of file pisa_test_generator.cpp.
Member Function Documentation
addMetaDataInformation() [1/2]
void PisaTestGenerator::addMetaDataInformation (json & input_json)
Definition at line 176 of file pisa_test_generator.cpp.
References addMetaDataInformation(), and findMaxRNSNumber().
addMetaDataInformation() [2/2]
void PisaTestGenerator::addMetaDataInformation (json & input_json, int RNS_NUM)
Definition at line 140 of file pisa_test_generator.cpp.
References block_size, and modulus_value.
Referenced by addMetaDataInformation(), and generateJSONForGraph().
convertPolyRnsChunkToPolyRns()
void PisaTestGenerator::convertPolyRnsChunkToPolyRns (json & input_json)
Definition at line 182 of file pisa_test_generator.cpp.
References convertPolyRnsChunkToPolyRnsHelper().
Referenced by generateJSONForGraph().
convertPolyRnsChunkToPolyRnsHelper()
void PisaTestGenerator::convertPolyRnsChunkToPolyRnsHelper (json & input_json)
Definition at line 188 of file pisa_test_generator.cpp.
Referenced by convertPolyRnsChunkToPolyRns().
findMaxRNSNumber()
int PisaTestGenerator::findMaxRNSNumber (json & input_json)
Definition at line 120 of file pisa_test_generator.cpp.
Referenced by addMetaDataInformation().
generateGraphFromHEOperationTrace()
graph::Graph<pisa::PISAInstruction> PisaTestGenerator::generateGraphFromHEOperationTrace (std::vector< pisa::poly::PolyOperation * > program_trace)
generateGraphFromPISAInstructions()
graph::Graph<pisa::PISAInstruction> PisaTestGenerator::generateGraphFromPISAInstructions (std::vector< pisa::PISAInstruction * > instructions)
generateGraphFromProgramTrace()
graph::Graph<pisa::PISAInstruction> PisaTestGenerator::generateGraphFromProgramTrace (ProgramTrace program_trace)
generateJSONForGraph()
json PisaTestGenerator::generateJSONForGraph (graph::Graph< pisa::PISAInstruction > p_isa_graph, pisa::testgenerator::InputGenerationMode gen_mode = pisa::testgenerator::InputGenerationMode::SINGLE_ONE, unsigned int random_seed = 0)
Definition at line 55 of file pisa_test_generator.cpp.
References addMetaDataInformation(), pisa::testgenerator::ALL_ONES, pisa::testgenerator::ALL_RANDOM, pisa::testgenerator::ASCENDING_FROM_ZERO, block_size, convertPolyRnsChunkToPolyRns(), graph::Graph< INSTRUCTION >::getInputNodes(), graph::Graph< INSTRUCTION >::getOutputNodes(), modulus_value, pisa::testgenerator::ONE_RANDOM, and pisa::testgenerator::SINGLE_ONE.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
populateCalculatedOutputResults()
void PisaTestGenerator::populateCalculatedOutputResults (std::vector< pisa::PISAInstruction * > instructions, json & input)
Definition at line 17 of file pisa_test_generator.cpp.
References PISAProgramRuntime< T >::executeProgram(), PISAProgramRuntime< T >::getModulusChain(), PISAProgramRuntime< T >::getParamMemoryFromMultiRegisterDeviceMemory(), PISAProgramRuntime< T >::setImmediatesToMultiRegisterDeviceMemory(), PISAProgramRuntime< T >::setINTTTwiddleFactors(), PISAProgramRuntime< T >::setModulusChain(), PISAProgramRuntime< T >::setNTTTwiddleFactors(), and PISAProgramRuntime< T >::setParamMemoryToMultiRegisterDeviceMemory().
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
writeJSON()
void PisaTestGenerator::writeJSON (json input_json, std::string file_name)
Definition at line 225 of file pisa_test_generator.cpp.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
Member Data Documentation
block_size
int PisaTestGenerator::block_size = 8192
Definition at line 51 of file pisa_test_generator.h.
Referenced by addMetaDataInformation(), and generateJSONForGraph().
modulus_value
int PisaTestGenerator::modulus_value = 32684
Definition at line 52 of file pisa_test_generator.h.
Referenced by addMetaDataInformation(), and generateJSONForGraph().
trace_file
json PisaTestGenerator::trace_file
Definition at line 49 of file pisa_test_generator.h.
The documentation for this class was generated from the following files:
p-isa_tools/program_mapper/p_isa/pisa_test_generator.h
p-isa_tools/program_mapper/p_isa/pisa_test_generator.cpp