Encrypted Computing SDK: pisa::PISAFunctionalModel< T > Class Template Reference
pisa::PISAFunctionalModel< T > Class Template Reference
#include <p_isa_functional_model.h>
Public Member Functions
PISAFunctionalModel ()
void generate_bit_reverse_table (int N, int ln)
void decode (pisa::PISAInstruction *instr)
decode: decodes instruction into a specific instance before calling implementation for that instruction.
T montgomeryMul (T a, T b, T modulus, bool use_mont=true)
montgomeryMul Performs montgomery Mul with uint64_t inputs.
T montgomeryAdd (T a, T b, T modulus, bool use_mont=true)
std::vector< pisa::MultiRegister< T > > readOutput (pisa::PISAInstruction *instr)
readOutput Reads the values stored in the output memory locations and returns them as a vector
std::vector< pisa::MultiRegister< T > > readInput (pisa::PISAInstruction *instr)
readInput Reads the values stored in the input memory locations and returns them as a vector
void addInstrDecodeExecute (pisa::instruction::Add *instr)
add provides functional implementation of add operation.
void copyInstrDecodeExecute (pisa::instruction::Copy *instr)
copy provides functional implementation of copy operation.
void subInstrDecodeExecute (pisa::instruction::Sub *instr)
sub provides functional implementation of sub operation.
void mulInstrDecodeExecute (pisa::instruction::Mul *instr)
mul provides functional implementation of mul operation.
void muliInstrDecodeExecute (pisa::instruction::Muli *instr)
muli provides functional implementation of muli operation which multiplies a multiregister elementwise by a scalar immediate value
void macInstrDecodeExecute (pisa::instruction::Mac *instr)
mac provides functional implementation of mac operation.
void maciInstrDecodeExecute (pisa::instruction::Maci *instr)
maci provides functional implementation of maci operation.
void iNttInstrDecodeExecute (pisa::instruction::Intt *instr)
iNTT provides functional implementation of iNTT operation.
void nttInstrDecodeExecute (pisa::instruction::Ntt *instr)
NTT provides functional implementation of NTT operation.
std::vector< T > getModulusChain () const
void setModulusChain (std::vector< T > new_modulus_chain)
std::vector< std::string > getMatching3ParamRegisterNames (std::string register_2_param_name)
getMatching3ParamRegisterNames will match 2 param names in form of <name>_<index0>_<index1> with matching 3 param names of form <name>_<index0>_<index1>_<index2
const std::vector< pisa::PISAInstructionTrace< T > > & executionTrace () const
void enableExecutionTrace ()
void stopExecutionTrace ()
const std::vector< std::vector< T > > & getTwiddleNtt () const
void setTwiddleNtt (const std::vector< std::vector< T >> &newTwiddle_ntt)
const TwiddleMap< T > & getTwiddleIntt () const
void setTwiddleIntt (const TwiddleMap< T > &newTwiddle_intt)
uint getMultiRegisterWidth () const
PISAMemoryModel< T > & getMemory ()
void setMemory (const PISAMemoryModel< T > &newMemory)
void dumpMemoryToStream (std::ostream &output_stream)
dumpMemoryToStream outputs all values currently stored in the devices memory and any global context memory values.
void dumpMemoryToStream (std::ostream &output_stream, std::vector< std::string > addresses)
void readMemoryFromStream (std::istream &input_stream)
readMemoryFromStream Accepts a memory dump in csv format and sets all memory values to provided values.
Private Member Functions
void createStartTable (int increment)
Private Attributes
std::vector< uint32_t > m_bit_reverse_table
PISAMemoryModel< T > m_memory
std::vector< T > m_modulus_chain
std::vector< std::vector< T > > m_twiddle_ntt
TwiddleMap< T > m_twiddle_intt
const uint m_multi_register_width = 8192
bool m_montgomery_enabled = true
bool m_debug_information_enabled = false
bool m_trace_execution = false
std::vector< int > m_start_table
std::vector< pisa::PISAInstructionTrace< T > > m_execution_trace
Detailed Description
template<typename T>
class pisa::PISAFunctionalModel< T >
Definition at line 25 of file p_isa_functional_model.h.
Constructor & Destructor Documentation
PISAFunctionalModel()
template<typename T > pisa::PISAFunctionalModel< T >::PISAFunctionalModel
Definition at line 196 of file p_isa_functional_model.h.
Member Function Documentation
addInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::addInstrDecodeExecute (pisa::instruction::Add * instr)
add provides functional implementation of add operation.
Definition at line 362 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
copyInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::copyInstrDecodeExecute (pisa::instruction::Copy * instr)
copy provides functional implementation of copy operation.
Operation Definition dst(int32) = (src_1(int32))
Definition at line 381 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), and pisa::Operand::location().
createStartTable()
template<typename T > void pisa::PISAFunctionalModel< T >::createStartTable (int increment) private
Definition at line 696 of file p_isa_functional_model.h.
decode()
template<typename T > void pisa::PISAFunctionalModel< T >::decode (pisa::PISAInstruction * instr)
decode: decodes instruction into a specific instance before calling implementation for that instruction.
Parameters
instr
Definition at line 211 of file p_isa_functional_model.h.
References pisa::instruction::Add::baseName, pisa::instruction::Sub::baseName, pisa::instruction::Mul::baseName, pisa::instruction::Mac::baseName, pisa::instruction::Maci::baseName, pisa::instruction::Intt::baseName, pisa::instruction::Ntt::baseName, pisa::instruction::Muli::baseName, pisa::instruction::Copy::baseName, pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), pisa::PISAInstruction::Name(), and pisa::PISAInstructionTrace< T >::setInstruction().
dumpMemoryToStream() [1/2]
template<typename T > void pisa::PISAFunctionalModel< T >::dumpMemoryToStream (std::ostream & output_stream)
dumpMemoryToStream outputs all values currently stored in the devices memory and any global context memory values.
Parameters
output_stream An output stream object to which to write memory values
Definition at line 753 of file p_isa_functional_model.h.
dumpMemoryToStream() [2/2]
template<typename T > void pisa::PISAFunctionalModel< T >::dumpMemoryToStream (std::ostream & output_stream, std::vector< std::string > addresses)
Definition at line 802 of file p_isa_functional_model.h.
enableExecutionTrace()
template<typename T > void pisa::PISAFunctionalModel< T >::enableExecutionTrace
Definition at line 683 of file p_isa_functional_model.h.
executionTrace()
template<typename T > const std::vector< pisa::PISAInstructionTrace< T > > & pisa::PISAFunctionalModel< T >::executionTrace
Definition at line 677 of file p_isa_functional_model.h.
generate_bit_reverse_table()
template<typename T > void pisa::PISAFunctionalModel< T >::generate_bit_reverse_table (int N, int ln)
Definition at line 202 of file p_isa_functional_model.h.
getMatching3ParamRegisterNames()
template<typename T > std::vector< std::string > pisa::PISAFunctionalModel< T >::getMatching3ParamRegisterNames (std::string register_2_param_name)
getMatching3ParamRegisterNames will match 2 param names in form of <name>_<index0>_<index1> with matching 3 param names of form <name>_<index0>_<index1>_<index2
Parameters
register_2_param_name
Returns
Definition at line 658 of file p_isa_functional_model.h.
References order_test::reg_name.
getMemory()
template<typename T > PISAMemoryModel< T > & pisa::PISAFunctionalModel< T >::getMemory
Definition at line 741 of file p_isa_functional_model.h.
getModulusChain()
template<typename T > std::vector< T > pisa::PISAFunctionalModel< T >::getModulusChain
Definition at line 646 of file p_isa_functional_model.h.
getMultiRegisterWidth()
template<typename T > uint pisa::PISAFunctionalModel< T >::getMultiRegisterWidth
Definition at line 891 of file p_isa_functional_model.h.
getTwiddleIntt()
template<typename T > const TwiddleMap< T > & pisa::PISAFunctionalModel< T >::getTwiddleIntt
Definition at line 897 of file p_isa_functional_model.h.
getTwiddleNtt()
template<typename T > const std::vector< std::vector< T > > & pisa::PISAFunctionalModel< T >::getTwiddleNtt
Definition at line 909 of file p_isa_functional_model.h.
iNttInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::iNttInstrDecodeExecute (pisa::instruction::Intt * instr)
iNTT provides functional implementation of iNTT operation.
Todo:
This all needs to be verified Operation Definition dst0 = src0; dst1 = src1;
Definition at line 488 of file p_isa_functional_model.h.
References pisa::WParam::block(), pisa::MultiRegister< T >::data(), pisa::PISAInstruction::galois_element(), pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), pisa::PISAInstruction::PMD(), pisa::WParam::residual(), pisa::MultiRegister< T >::size(), pisa::WParam::stage(), and pisa::PISAInstruction::wParam().
maciInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::maciInstrDecodeExecute (pisa::instruction::Maci * instr)
maci provides functional implementation of maci operation.
Operation Definition dst(int32) = (dst(int32) + src_1(int32)*imm(int32)) % modulus_q
Definition at line 469 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
macInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::macInstrDecodeExecute (pisa::instruction::Mac * instr)
mac provides functional implementation of mac operation.
Operation Definition dst(int32) = (dst(int32) + src_1(int32)*src_2(int32)) % modulus_q
Definition at line 450 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
montgomeryAdd()
template<typename T > T pisa::PISAFunctionalModel< T >::montgomeryAdd (T a, T b, T modulus, bool use_mont = true)
Definition at line 312 of file p_isa_functional_model.h.
montgomeryMul()
template<typename T > T pisa::PISAFunctionalModel< T >::montgomeryMul (T a, T b, T modulus, bool use_mont = true)
montgomeryMul Performs montgomery Mul with uint64_t inputs.
Parameters
a
b
modulus
use_mont
Returns
Definition at line 291 of file p_isa_functional_model.h.
muliInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::muliInstrDecodeExecute (pisa::instruction::Muli * instr)
muli provides functional implementation of muli operation which multiplies a multiregister elementwise by a scalar immediate value
Operation Definition dst(pisa::MultiRegister<T>32) = (src_1(pisa::MultiRegister<T>32)*immediate) % modulus_q
Definition at line 433 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
mulInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::mulInstrDecodeExecute (pisa::instruction::Mul * instr)
mul provides functional implementation of mul operation.
Operation Definition dst(int32) = (src_1(int32)*src_2(int32)) % modulus_q
Definition at line 416 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
nttInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::nttInstrDecodeExecute (pisa::instruction::Ntt * instr)
NTT provides functional implementation of NTT operation.
Todo:
This all needs to be verified Operation Definition
Definition at line 561 of file p_isa_functional_model.h.
References pisa::WParam::block(), pisa::MultiRegister< T >::data(), pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), pisa::PISAInstruction::PMD(), pisa::WParam::residual(), pisa::MultiRegister< T >::size(), pisa::WParam::stage(), and pisa::PISAInstruction::wParam().
readInput()
template<typename T > std::vector< pisa::MultiRegister< T > > pisa::PISAFunctionalModel< T >::readInput (pisa::PISAInstruction * instr)
readInput Reads the values stored in the input memory locations and returns them as a vector
Parameters
instr
Returns
Definition at line 350 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), and pisa::PISAInstruction::numInputOperands().
readMemoryFromStream()
template<typename T > void pisa::PISAFunctionalModel< T >::readMemoryFromStream (std::istream & input_stream)
readMemoryFromStream Accepts a memory dump in csv format and sets all memory values to provided values.
Parameters
input_stream
Definition at line 818 of file p_isa_functional_model.h.
readOutput()
template<typename T > std::vector< pisa::MultiRegister< T > > pisa::PISAFunctionalModel< T >::readOutput (pisa::PISAInstruction * instr)
readOutput Reads the values stored in the output memory locations and returns them as a vector
Parameters
instr
Returns
Definition at line 338 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getOutputOperand(), and pisa::PISAInstruction::numOutputOperands().
setMemory()
template<typename T > void pisa::PISAFunctionalModel< T >::setMemory (const PISAMemoryModel< T > & newMemory)
Definition at line 747 of file p_isa_functional_model.h.
setModulusChain()
template<typename T > void pisa::PISAFunctionalModel< T >::setModulusChain (std::vector< T > new_modulus_chain)
Definition at line 652 of file p_isa_functional_model.h.
setTwiddleIntt()
template<typename T > void pisa::PISAFunctionalModel< T >::setTwiddleIntt (const TwiddleMap< T > & newTwiddle_intt)
Definition at line 903 of file p_isa_functional_model.h.
setTwiddleNtt()
template<typename T > void pisa::PISAFunctionalModel< T >::setTwiddleNtt (const std::vector< std::vector< T >> & newTwiddle_ntt)
Definition at line 915 of file p_isa_functional_model.h.
stopExecutionTrace()
template<typename T > void pisa::PISAFunctionalModel< T >::stopExecutionTrace
Definition at line 690 of file p_isa_functional_model.h.
subInstrDecodeExecute()
template<typename T > void pisa::PISAFunctionalModel< T >::subInstrDecodeExecute (pisa::instruction::Sub * instr)
sub provides functional implementation of sub operation.
Operation Definition dst(int32) = (src_1(int32) - src_2(int32)) % modulus_q
Definition at line 393 of file p_isa_functional_model.h.
References pisa::PISAInstruction::getInputOperand(), pisa::PISAInstruction::getOutputOperand(), pisa::Operand::location(), and pisa::PISAInstruction::residual().
Member Data Documentation
m_bit_reverse_table
template<typename T > std::vector<uint32_t> pisa::PISAFunctionalModel< T >::m_bit_reverse_table private
Definition at line 177 of file p_isa_functional_model.h.
m_debug_information_enabled
template<typename T > bool pisa::PISAFunctionalModel< T >::m_debug_information_enabled = false private
Definition at line 188 of file p_isa_functional_model.h.
m_execution_trace
template<typename T > std::vector<pisa::PISAInstructionTrace<T> > pisa::PISAFunctionalModel< T >::m_execution_trace private
Definition at line 192 of file p_isa_functional_model.h.
m_memory
template<typename T > PISAMemoryModel<T> pisa::PISAFunctionalModel< T >::m_memory private
Definition at line 179 of file p_isa_functional_model.h.
m_modulus_chain
template<typename T > std::vector<T> pisa::PISAFunctionalModel< T >::m_modulus_chain private
Definition at line 182 of file p_isa_functional_model.h.
m_montgomery_enabled
template<typename T > bool pisa::PISAFunctionalModel< T >::m_montgomery_enabled = true private
Definition at line 187 of file p_isa_functional_model.h.
m_multi_register_width
template<typename T > const uint pisa::PISAFunctionalModel< T >::m_multi_register_width = 8192 private
Definition at line 185 of file p_isa_functional_model.h.
m_start_table
template<typename T > std::vector<int> pisa::PISAFunctionalModel< T >::m_start_table private
Definition at line 190 of file p_isa_functional_model.h.
m_trace_execution
template<typename T > bool pisa::PISAFunctionalModel< T >::m_trace_execution = false private
Definition at line 189 of file p_isa_functional_model.h.
m_twiddle_intt
template<typename T > TwiddleMap<T> pisa::PISAFunctionalModel< T >::m_twiddle_intt private
Definition at line 184 of file p_isa_functional_model.h.
m_twiddle_ntt
template<typename T > std::vector<std::vector<T> > pisa::PISAFunctionalModel< T >::m_twiddle_ntt private
Definition at line 183 of file p_isa_functional_model.h.
The documentation for this class was generated from the following file:
p-isa_tools/functional_modeler/functional_models/p_isa_functional_model.h