Encrypted Computing SDK: p-isa_tools/functional_modeler/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <unordered_set>
#include <argmap.h>
#include <config.h>
#include <functional_modeler/data_handlers/json_data_handler.h>
#include <functional_modeler/pisa_runtime/pisaprogramruntime.h>
#include <common/graph/graph.h>
#include <common/p_isa/p_isa.h>
#include <common/p_isa/p_isa_performance_modeler.h>
#include <common/p_isa/parser/p_isa_parser.h>
#include <common/timer/timer.h>
Classes
struct FunctionalModelerArguments
Typedefs
using DATA_TYPE = uint32_t
Functions
FunctionalModelerArguments parseCommandLineArguments (int argc, char **argv)
template<typename T >
void executePISAInstructions (const FunctionalModelerArguments &arguments, const std::vector< pisa::PISAInstruction * > &instructions, const JSONDataHandler< T > &json_data={})
int main (int argc, char **argv)
Typedef Documentation
DATA_TYPE
using DATA_TYPE = uint32_t
Definition at line 22 of file main.cpp.
Function Documentation
executePISAInstructions()
template<typename T > void executePISAInstructions (const FunctionalModelerArguments & arguments, const std::vector< pisa::PISAInstruction * > & instructions, const JSONDataHandler< T > & json_data = {})
Definition at line 175 of file main.cpp.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 612 of file main.cpp.
References graph::Graph< INSTRUCTION >::createGraph(), FunctionalModelerArguments::execute_p_isa_program, executePISAInstructions(), FunctionalModelerArguments::generate_graphs, FunctionalModelerArguments::graph_image_file_name, FunctionalModelerArguments::hec_dataformats_data_enabled, FunctionalModelerArguments::json_data_enabled, FunctionalModelerArguments::json_data_location, graph::NAME, FunctionalModelerArguments::p_isa_location, pisa::PISAParser::parse(), parseCommandLineArguments(), graph::printGraphInformation(), FunctionalModelerArguments::render_graph_to_image, and FunctionalModelerArguments::verbose.
parseCommandLineArguments()
FunctionalModelerArguments parseCommandLineArguments (int argc, char ** argv)
Definition at line 62 of file main.cpp.
References deadlock_test::args, and pisa::PerformanceModels::hardwareModels.
Referenced by main().