Encrypted Computing SDK: test_kerngraph_command Namespace Reference
test_kerngraph_command Namespace Reference
Functions
def run_parse_args_with_args (args)
Helper to run parse_args with specific sys.argv.
def test_parse_args_defaults ()
Test default argument values for parse_args.
def test_parse_args_debug_flag ()
Test enabling the debug flag.
def test_parse_args_target_multiple ()
Test parsing multiple target arguments.
def test_parse_args_primary_secondary_valid ()
Test valid primary and secondary loop key combinations.
def test_parse_args_primary_secondary_same ()
Test that primary and secondary keys cannot be the same.
def test_parse_args_invalid_primary_secondary ()
Test that invalid primary or secondary keys raise an error.
Function Documentation
run_parse_args_with_args()
def test_kerngraph_command.run_parse_args_with_args (args)
Helper to run parse_args with specific sys.argv.
Definition at line 34 of file test_kerngraph_command.py.
References isolation_test.parse_args().
Referenced by test_parse_args_debug_flag(), test_parse_args_defaults(), test_parse_args_invalid_primary_secondary(), test_parse_args_primary_secondary_valid(), and test_parse_args_target_multiple().
test_parse_args_debug_flag()
def test_kerngraph_command.test_parse_args_debug_flag ()
Test enabling the debug flag.
Definition at line 54 of file test_kerngraph_command.py.
References run_parse_args_with_args().
test_parse_args_defaults()
def test_kerngraph_command.test_parse_args_defaults ()
Test default argument values for parse_args.
Definition at line 44 of file test_kerngraph_command.py.
References run_parse_args_with_args().
test_parse_args_invalid_primary_secondary()
def test_kerngraph_command.test_parse_args_invalid_primary_secondary ()
Test that invalid primary or secondary keys raise an error.
Definition at line 84 of file test_kerngraph_command.py.
References run_parse_args_with_args().
test_parse_args_primary_secondary_same()
def test_kerngraph_command.test_parse_args_primary_secondary_same ()
Test that primary and secondary keys cannot be the same.
Definition at line 73 of file test_kerngraph_command.py.
References isolation_test.parse_args().
test_parse_args_primary_secondary_valid()
def test_kerngraph_command.test_parse_args_primary_secondary_valid ()
Test valid primary and secondary loop key combinations.
Definition at line 66 of file test_kerngraph_command.py.
References run_parse_args_with_args().
test_parse_args_target_multiple()
def test_kerngraph_command.test_parse_args_target_multiple ()
Test parsing multiple target arguments.
Definition at line 60 of file test_kerngraph_command.py.
References run_parse_args_with_args().