Encrypted Computing SDK: pisa::poly::library Namespace Reference
pisa::poly::library Namespace Reference
Namespaces
core
Functions
static void activatePolynomialLibrary ()
static PolyOperationDesc getPolyOperationDesc (std::string operation)
static std::shared_ptr< pisa::poly::PolyOperation > createPolyOperation (std::string operation)
static std::shared_ptr< pisa::poly::PolyOperation > createPolyOperation (std::string operation, std::initializer_list< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent)
static std::shared_ptr< pisa::poly::PolyOperation > createPolyOperation (std::string operation, std::initializer_list< std::string > args)
static std::shared_ptr< pisa::poly::PolyOperation > createPolyOperation (std::string operation, std::vector< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent)
static std::shared_ptr< pisa::poly::PolyOperation > createPolyOperation (std::string operation, std::vector< std::string > args)
Variables
static std::map< std::string, PolyOperationDesc > core_operation_library
static std::map< std::string, PolyOperationDesc > extended_operation_set
static std::map< std::string, PolyOperationDesc > active_polynomial_operation_library
static bool library_ready = false
Function Documentation
activatePolynomialLibrary()
static void pisa::poly::library::activatePolynomialLibrary () static
Definition at line 28 of file poly_operation_library.h.
References active_polynomial_operation_library, core_operation_library, and extended_operation_set.
Referenced by getPolyOperationDesc().
createPolyOperation() [1/5]
static std::shared_ptr<pisa::poly::PolyOperation> pisa::poly::library::createPolyOperation (std::string operation) static
Definition at line 55 of file poly_operation_library.h.
References pisa::poly::PolyOperation::create(), and getPolyOperationDesc().
Referenced by AddOperation::constructTest(), AddCorrected::constructTest(), createPolyOperation(), and PolynomialProgramHelper::parseInstruction().
createPolyOperation() [2/5]
static std::shared_ptr<pisa::poly::PolyOperation> pisa::poly::library::createPolyOperation (std::string operation, std::initializer_list< std::string > args) static
Definition at line 68 of file poly_operation_library.h.
References deadlock_test::args, createPolyOperation(), and pisa::poly::default_global_poly_program.
createPolyOperation() [3/5]
static std::shared_ptr<pisa::poly::PolyOperation> pisa::poly::library::createPolyOperation (std::string operation, std::initializer_list< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent) static
Definition at line 62 of file poly_operation_library.h.
References deadlock_test::args, pisa::poly::PolyOperation::create(), and getPolyOperationDesc().
createPolyOperation() [4/5]
static std::shared_ptr<pisa::poly::PolyOperation> pisa::poly::library::createPolyOperation (std::string operation, std::vector< std::string > args) static
Definition at line 79 of file poly_operation_library.h.
References deadlock_test::args, createPolyOperation(), and pisa::poly::default_global_poly_program.
createPolyOperation() [5/5]
static std::shared_ptr<pisa::poly::PolyOperation> pisa::poly::library::createPolyOperation (std::string operation, std::vector< std::string > args, std::shared_ptr< pisa::poly::PolyProgram > parent) static
Definition at line 73 of file poly_operation_library.h.
References deadlock_test::args, pisa::poly::PolyOperation::create(), and getPolyOperationDesc().
getPolyOperationDesc()
static PolyOperationDesc pisa::poly::library::getPolyOperationDesc (std::string operation) static
Definition at line 40 of file poly_operation_library.h.
References activatePolynomialLibrary(), active_polynomial_operation_library, and library_ready.
Referenced by createPolyOperation().
Variable Documentation
active_polynomial_operation_library
std::map<std::string, PolyOperationDesc> pisa::poly::library::active_polynomial_operation_library static
Definition at line 26 of file poly_operation_library.h.
Referenced by activatePolynomialLibrary(), and getPolyOperationDesc().
core_operation_library
std::map<std::string, PolyOperationDesc> pisa::poly::library::core_operation_library static
Initial value:
= {
    { "add", library::core::Add },
    { "add_plain", library::core::Add },
    { "sub", library::core::Sub },
    { "mul", library::core::Mul },
    { "mul_plain", library::core::Mul },
    { "square", library::core::Square },
    { "ntt", library::core::Ntt },
    { "intt", library::core::Intt },
    { "relin", library::core::Relin },
    { "mod_switch", library::core::ModSwitch },
    { "rescale", library::core::Rescale },
    { "rotate", library::core::Rotate },
}
Map used to specify the collection of kernels
Definition at line 10 of file poly_operation_library.h.
Referenced by activatePolynomialLibrary().
extended_operation_set
std::map<std::string, PolyOperationDesc> pisa::poly::library::extended_operation_set static
Definition at line 25 of file poly_operation_library.h.
Referenced by activatePolynomialLibrary().
library_ready
bool pisa::poly::library::library_ready = false static
Definition at line 38 of file poly_operation_library.h.
Referenced by getPolyOperationDesc().