Encrypted Computing SDK: stages.asm_scheduler Namespace Reference
stages.asm_scheduler Namespace Reference
Classes
class XStoreAssign
Encapsulates a compound operation of an xstore instruction and a register assignment.
class BundleData
Structure for a completed bundle of instructions.
class XWriteCycleTrack
Tracks the cycle where a write occurs to the register file by an XInstruction and which banks are being written to.
class CurrentrShuffleTable
Tracks the current rShuffle routing table.
class Simulation
Simulates the scheduling of instructions in a dependency graph.
Functions
bool __canScheduleInBundle (instr, Simulation simulation, int padding=1)
Determines if an instruction can be scheduled in the current bundle.
bool __flushVariableFromSPAD (instr, int dest_hbm_addr, Variable variable, Simulation simulation)
Flushes a variable from the SPAD to HBM.
object _createXStore (int instr_id, int dest_spad_addr, Variable evict_variable, Variable new_variable, str comment, Simulation simulation)
Creates an XStore instruction to move a variable into SPAD.
object __flushVariableFromRegisterFile (instr, int dest_spad_addr, Variable evict_variable, Variable new_variable, Simulation simulation)
Flushes a variable from the register file to SPAD.
bool scheduleXNOP (instr, int idle_cycles, Simulation simulation, bool force_nop=False)
Schedules a NOP instruction if necessary.
int findSPADAddress (instr, Simulation simulation)
Finds an available SPAD address for an instruction.
object findRegister (instr, int bank_idx, Simulation simulation, str override_replacement_policy=None, Variable dest_var=None)
Finds an available register for an instruction.
bool loadVariableHBMToSPAD (instr, Variable variable, Simulation simulation)
Loads a variable from HBM to SPAD.
bool hasBankWriteConflictGeneral (CycleType ready_cycle, int latency, banks, Simulation simulation)
Checks for bank write conflicts in general.
bool hasBankWriteConflict (instr, Simulation simulation)
Checks for bank write conflicts for a specific instruction.
int prepareInstruction (original_xinstr, Simulation simulation)
Prepares an instruction for scheduling.
(list, list, list, int) scheduleASMISAInstructions (nx.DiGraph dependency_graph, int max_bundle_size, MemoryModel mem_model, replacement_policy, bool progress_verbose=False)
Schedules ASM-ISA instructions based on a dependency graph of XInsts to minimize idle cycles.
Variables
Constants = constants.Constants
bool auto_allocate = True
Function Documentation
__canScheduleInBundle()
bool stages.asm_scheduler.__canScheduleInBundle (instr, Simulation simulation, int padding = 1) private
Determines if an instruction can be scheduled in the current bundle.
Parameters: instr: The instruction to be scheduled. simulation (Simulation): The current simulation context. padding (int): Extra instruction padding (like number of other instructions before this one, such as a nop).
Returns: bool: True if the instruction can be scheduled in the current bundle, False otherwise.
Definition at line 1808 of file asm_scheduler.py.
Referenced by stages.asm_scheduler.prepareInstruction(), and stages.asm_scheduler.scheduleASMISAInstructions().
__flushVariableFromRegisterFile()
object stages.asm_scheduler.__flushVariableFromRegisterFile (instr, int dest_spad_addr, Variable evict_variable, Variable new_variable, Simulation simulation) private
Flushes a variable from the register file to SPAD.
Parameters: instr: The instruction triggering the flush. dest_spad_addr (int): The destination SPAD address. evict_variable (Variable): The variable to evict. new_variable (Variable): The variable to be allocated in register after eviction, or None to keep register free. simulation (Simulation): The current simulation context.
Returns: object: The created XStore instruction.
Definition at line 1907 of file asm_scheduler.py.
References stages.asm_scheduler._createXStore().
Referenced by stages.asm_scheduler.findRegister().
__flushVariableFromSPAD()
bool stages.asm_scheduler.__flushVariableFromSPAD (instr, int dest_hbm_addr, Variable variable, Simulation simulation) private
Flushes a variable from the SPAD to HBM.
Parameters: instr: The instruction triggering the flush. dest_hbm_addr (int): The destination address in HBM. variable (Variable): The variable to be flushed. simulation (Simulation): The current simulation context.
Returns: bool: True if the flush was scheduled successfully, False otherwise.
Raises: AssertionError: If the destination HBM address is invalid.
Definition at line 1833 of file asm_scheduler.py.
Referenced by stages.asm_scheduler.findSPADAddress().
_createXStore()
object stages.asm_scheduler._createXStore (int instr_id, int dest_spad_addr, Variable evict_variable, Variable new_variable, str comment, Simulation simulation) private
Creates an XStore instruction to move a variable into SPAD.
Parameters: instr_id (int): The instruction ID. dest_spad_addr (int): The destination SPAD address. evict_variable (Variable): The variable to evict. new_variable (Variable): The variable to be allocated in register after eviction, or None to keep register free. comment (str): A comment for the instruction. simulation (Simulation): The current simulation context.
Returns: object: The created XStore instruction.
Raises: AssertionError: If the evict variable's register is None or if the SPAD address is invalid.
Definition at line 1873 of file asm_scheduler.py.
References xinst.XStore.
Referenced by stages.asm_scheduler.__flushVariableFromRegisterFile(), and stages.asm_scheduler.Simulation.flushOutputVariableFromRegister().
findRegister()
object stages.asm_scheduler.findRegister (instr, int bank_idx, Simulation simulation, str override_replacement_policy = None, Variable dest_var = None)
Finds an available register for an instruction.
Parameters: instr: The instruction needing a register. bank_idx (int): The index of the register bank. simulation (Simulation): The current simulation context. override_replacement_policy (str): The replacement policy to override, if any. dest_var (Variable): The variable to be allocated in register after eviction, or None to keep register free.
Returns: tuple: A tuple containing the ready value (int) and the register or XInstruction.
Raises: RuntimeError: If no SPAD address is available or if HBM is full.
Definition at line 2067 of file asm_scheduler.py.
References stages.asm_scheduler.__flushVariableFromRegisterFile(), and stages.asm_scheduler.findSPADAddress().
Referenced by stages.asm_scheduler.prepareInstruction().
findSPADAddress()
int stages.asm_scheduler.findSPADAddress (instr, Simulation simulation)
Finds an available SPAD address for an instruction.
Parameters: instr: The instruction needing SPAD. simulation (Simulation): The current simulation context.
Returns: int: The SPAD address, or -1 if no address is available.
Raises: RuntimeError: If no SPAD address is available or if HBM is full.
Definition at line 1970 of file asm_scheduler.py.
References stages.asm_scheduler.__flushVariableFromSPAD().
Referenced by stages.asm_scheduler.findRegister(), stages.asm_scheduler.Simulation.flushOutputVariableFromRegister(), and stages.asm_scheduler.loadVariableHBMToSPAD().
hasBankWriteConflict()
bool stages.asm_scheduler.hasBankWriteConflict (instr, Simulation simulation)
Checks for bank write conflicts for a specific instruction.
Parameters: instr: The instruction to check. simulation (Simulation): The current simulation context.
Returns: bool: True if there is a bank write conflict, False otherwise.
Definition at line 2252 of file asm_scheduler.py.
References stages.asm_scheduler.hasBankWriteConflictGeneral().
Referenced by stages.asm_scheduler.Simulation.findNextInstructionToSchedule(), and stages.asm_scheduler.prepareInstruction().
hasBankWriteConflictGeneral()
bool stages.asm_scheduler.hasBankWriteConflictGeneral (CycleType ready_cycle, int latency, banks, Simulation simulation)
Checks for bank write conflicts in general.
Parameters: ready_cycle (CycleType): The cycle when the instruction is ready. latency (int): The latency of the instruction. banks: An iterable of bank indices. simulation (Simulation): The current simulation context.
Returns: bool: True if there is a bank write conflict, False otherwise.
Definition at line 2223 of file asm_scheduler.py.
Referenced by stages.asm_scheduler.hasBankWriteConflict().
loadVariableHBMToSPAD()
bool stages.asm_scheduler.loadVariableHBMToSPAD (instr, Variable variable, Simulation simulation)
Loads a variable from HBM to SPAD.
Parameters: instr: The instruction needing the variable. variable (Variable): The variable to be loaded. simulation (Simulation): The current simulation context.
Returns: bool: True if the variable was loaded successfully, False otherwise.
Raises: RuntimeError: If the variable is not found in HBM or if HBM is full.
Definition at line 2167 of file asm_scheduler.py.
References stages.asm_scheduler.findSPADAddress().
Referenced by stages.asm_scheduler.prepareInstruction().
prepareInstruction()
int stages.asm_scheduler.prepareInstruction (original_xinstr, Simulation simulation)
Prepares an instruction for scheduling.
Parameters: original_xinstr: The original instruction to prepare. simulation (Simulation): The current simulation context.
Returns: tuple: A tuple containing the ready value (int) and the instruction or None.
Raises: RuntimeError: If a variable is not in the suggested bank.
Definition at line 2278 of file asm_scheduler.py.
References stages.asm_scheduler.__canScheduleInBundle(), stages.asm_scheduler.findRegister(), stages.asm_scheduler.hasBankWriteConflict(), stages.asm_scheduler.loadVariableHBMToSPAD(), xinst.Move, and stages.asm_scheduler.scheduleXNOP().
Referenced by stages.asm_scheduler.scheduleASMISAInstructions().
scheduleASMISAInstructions()
(list, list, list, int) stages.asm_scheduler.scheduleASMISAInstructions (nx.DiGraph dependency_graph, int max_bundle_size, MemoryModel mem_model, replacement_policy, bool progress_verbose = False)
Schedules ASM-ISA instructions based on a dependency graph of XInsts to minimize idle cycles.
Parameters: dependency_graph (nx.DiGraph): The dependency directed acyclic graph of XInsts. max_bundle_size (int): Maximum number of instructions in a bundle. mem_model (MemoryModel): The memory model used in the simulation. replacement_policy: The policy used for memory replacement. progress_verbose (bool): Whether to print progress information.
Returns: tuple: A tuple containing lists of xinst, cinst, minst, and the total idle cycles.
Definition at line 2450 of file asm_scheduler.py.
References stages.asm_scheduler.__canScheduleInBundle(), inject_bundles.int, stages.asm_scheduler.prepareInstruction(), and stages.asm_scheduler.scheduleXNOP().
Referenced by main.asmisa_assembly(), and he_as.asmisaAssemble().
scheduleXNOP()
bool stages.asm_scheduler.scheduleXNOP (instr, int idle_cycles, Simulation simulation, bool force_nop = False)
Schedules a NOP instruction if necessary.
Parameters: instr: The instruction that requires the NOP. idle_cycles (int): The number of idle cycles to schedule. simulation (Simulation): The current simulation context. force_nop (bool): Whether to force the scheduling of a NOP.
Returns: bool: True if the NOP was scheduled, False otherwise.
Raises: ValueError: If idle_cycles is not greater than 0.
Definition at line 1929 of file asm_scheduler.py.
References xinst.Nop.
Referenced by stages.asm_scheduler.prepareInstruction(), and stages.asm_scheduler.scheduleASMISAInstructions().
Variable Documentation
auto_allocate
bool stages.asm_scheduler.auto_allocate = True
Definition at line 36 of file asm_scheduler.py.
Constants
stages.asm_scheduler.Constants = constants.Constants
Definition at line 17 of file asm_scheduler.py.