Encrypted Computing SDK: xtiming_check Namespace Reference
xtiming_check Namespace Reference
Functions
def makeUniquePath (str path)
Normalizes and expand a given file path.
int computeXBundleLatency (list xinstr_bundle)
Computes the latency of a bundle of XInstructions.
list computeXBundleLatencies (list xinstrs)
Computes latencies for all bundles of XInstructions.
list computeCBundleLatencies (cinstr_lines)
Computes latencies for all bundles of CInstructions.
def main (str input_dir, str input_prefix=None)
Main function to check timing for register access and synchronization.
Variables
int NUM_BUNDLE_INSTRUCTIONS = 64
module_dir = os.path.dirname(__file__)
module_name = os.path.basename(__file__)
parser = argparse.ArgumentParser()
nargs
default
dest
help
args = parser.parse_args()
isa_spec_file
Function Documentation
computeCBundleLatencies()
list xtiming_check.computeCBundleLatencies (cinstr_lines)
Computes latencies for all bundles of CInstructions.
Parameters: cinstr_lines: An iterable of CInstruction lines.
Returns: list: A list of latencies for each bundle.
Definition at line 100 of file xtiming_check.py.
References inject_bundles.int.
Referenced by main().
computeXBundleLatencies()
list xtiming_check.computeXBundleLatencies (list xinstrs)
Computes latencies for all bundles of XInstructions.
Parameters: xinstrs (list): A list of XInstructions.
Returns: list: A list of latencies for each bundle.
Definition at line 72 of file xtiming_check.py.
References computeXBundleLatency().
Referenced by main().
computeXBundleLatency()
int xtiming_check.computeXBundleLatency (list xinstr_bundle)
Computes the latency of a bundle of XInstructions.
Parameters: xinstr_bundle (list): A list of XInstructions in a bundle.
Returns: int: The computed latency of the bundle.
Raises: RuntimeError: If the bundle size is invalid.
Definition at line 38 of file xtiming_check.py.
Referenced by computeXBundleLatencies().
main()
def xtiming_check.main (str input_dir, str input_prefix = None)
Main function to check timing for register access and synchronization.
Parameters: input_dir (str): Directory containing input files. input_prefix (str): Prefix for input files.
Definition at line 145 of file xtiming_check.py.
References computeCBundleLatencies(), computeXBundleLatencies(), and makeUniquePath().
makeUniquePath()
def xtiming_check.makeUniquePath (str path)
Normalizes and expand a given file path.
Parameters: path (str): The file path to normalize and expand.
Returns: str: The normalized and expanded file path.
Definition at line 23 of file xtiming_check.py.
Referenced by main().
Variable Documentation
args
xtiming_check.args = parser.parse_args()
Definition at line 362 of file xtiming_check.py.
default
xtiming_check.default
Definition at line 360 of file xtiming_check.py.
dest
xtiming_check.dest
Definition at line 360 of file xtiming_check.py.
help
xtiming_check.help
Definition at line 361 of file xtiming_check.py.
isa_spec_file
xtiming_check.isa_spec_file
Definition at line 364 of file xtiming_check.py.
module_dir
xtiming_check.module_dir = os.path.dirname(__file__)
Definition at line 353 of file xtiming_check.py.
module_name
xtiming_check.module_name = os.path.basename(__file__)
Definition at line 354 of file xtiming_check.py.
nargs
xtiming_check.nargs
Definition at line 359 of file xtiming_check.py.
NUM_BUNDLE_INSTRUCTIONS
int xtiming_check.NUM_BUNDLE_INSTRUCTIONS = 64
Definition at line 12 of file xtiming_check.py.
parser
xtiming_check.parser = argparse.ArgumentParser()
Definition at line 357 of file xtiming_check.py.