Encrypted Computing SDK: kerngen.pisa_generators.ntt Namespace Reference
kerngen.pisa_generators.ntt Namespace Reference
Classes
class NTT
Class representing the NTT.
class INTT
Class representing the INTT.
Functions
def generate_unit_index (int size, pisa_op.NTT|pisa_op.INTT op)
Helper to return unit indices for ntt/intt.
list[PIsaOp] butterflies_ops (pisa_op.NTT|pisa_op.INTT op, KernelContext context, Polys output, Polys outtmp, Polys input0, *bool init_input=False, int unit_size=8192)
Helper to return butterflies pisa operations for NTT/INTT.
Function Documentation
butterflies_ops()
list[PIsaOp] kerngen.pisa_generators.ntt.butterflies_ops (pisa_op.NTT | pisa_op.INTT op, KernelContext context, Polys output, Polys outtmp, Polys input0, *bool init_input = False, int unit_size = 8192)
Helper to return butterflies pisa operations for NTT/INTT.
Definition at line 27 of file ntt.py.
References kerngen.pisa_generators.ntt.generate_unit_index(), and inject_bundles.int.
Referenced by kerngen.pisa_generators.ntt.NTT.to_pisa(), and kerngen.pisa_generators.ntt.INTT.to_pisa().
generate_unit_index()
def kerngen.pisa_generators.ntt.generate_unit_index (int size, pisa_op.NTT | pisa_op.INTT op)
Helper to return unit indices for ntt/intt.
Definition at line 17 of file ntt.py.
References inject_bundles.int.
Referenced by kerngen.pisa_generators.ntt.butterflies_ops().