Encrypted Computing SDK: he_prep Namespace Reference
he_prep Namespace Reference
Functions
def __savePISAListing (out_stream, list instr_listing)
Stores the instructions to a stream in P-ISA format.
def main (str output_file_name, str input_file_name, bool b_verbose)
Preprocesses the P-ISA kernel and saves the output to a specified file.
def parse_args ()
Parses command-line arguments for the preprocessing script.
Variables
module_dir = os.path.dirname(__file__)
module_name = os.path.basename(__file__)
def args = parse_args()
isa_spec_file
mem_spec_file
output_file_name
input_file_name
b_verbose
Function Documentation
__savePISAListing()
def he_prep.__savePISAListing (out_stream, list instr_listing) private
Stores the instructions to a stream in P-ISA format.
This function iterates over a list of instructions and prints each instruction in P-ISA format to the specified output stream.
Args: out_stream: The output stream to which the instructions are printed. instr_listing (list): A list of instructions to be printed in P-ISA format.
Returns: None
Definition at line 46 of file he_prep.py.
Referenced by main().
main()
def he_prep.main (str output_file_name, str input_file_name, bool b_verbose)
Preprocesses the P-ISA kernel and saves the output to a specified file.
This function reads an input kernel file, preprocesses it to transform instructions into ASM-ISA format, assigns register banks to variables, and saves the processed instructions to an output file.
Args: output_file_name (str): The name of the output file where processed instructions are saved. input_file_name (str): The name of the input file containing the P-ISA kernel. b_verbose (bool): Flag indicating whether verbose output is enabled.
Returns: None
Definition at line 67 of file he_prep.py.
References __savePISAListing().
Referenced by test_he_prep.test_main_assigns_and_saves(), test_he_prep.test_main_invalid_input_file(), test_he_prep.test_main_invalid_output_file(), test_he_prep.test_main_no_input_file(), test_he_prep.test_main_no_instructions(), and test_he_prep.test_main_no_output_file().
parse_args()
def he_prep.parse_args ()
Parses command-line arguments for the preprocessing script.
This function sets up the argument parser and defines the expected arguments for the script. It returns a Namespace object containing the parsed arguments.
Returns: argparse.Namespace: Parsed command-line arguments.
Definition at line 124 of file he_prep.py.
Referenced by test_he_prep.test_parse_args().
Variable Documentation
args
def he_prep.args = parse_args()
Definition at line 144 of file he_prep.py.
b_verbose
he_prep.b_verbose
Definition at line 159 of file he_prep.py.
input_file_name
he_prep.input_file_name
Definition at line 158 of file he_prep.py.
isa_spec_file
he_prep.isa_spec_file
Definition at line 146 of file he_prep.py.
mem_spec_file
he_prep.mem_spec_file
Definition at line 147 of file he_prep.py.
module_dir
he_prep.module_dir = os.path.dirname(__file__)
Definition at line 141 of file he_prep.py.
module_name
he_prep.module_name = os.path.basename(__file__)
Definition at line 142 of file he_prep.py.
output_file_name
he_prep.output_file_name
Definition at line 157 of file he_prep.py.