Encrypted Computing SDK: instructions Namespace Reference
instructions Namespace Reference
Namespaces
cinst
instruction
minst
xinst
Functions
list tokenizeFromLine (str line)
Tokenizes a line of text and extracts any comment present.
Function Documentation
tokenizeFromLine()
list instructions.tokenizeFromLine (str line)
Tokenizes a line of text and extracts any comment present.
This function processes a line of text, removing line breaks and splitting the line into tokens based on commas. It also identifies and extracts comments, which are denoted by the pound symbol #.
Args: line (str): Line of text to tokenize.
Returns: tuple: A tuple containing the tokens and the comment. The tokens are a tuple of strings, and comment is a string. The comment is an empty string if no comment is found in the line.
Definition at line 16 of file __init__.py.
Referenced by memory_model.mem_info.MemInfo.from_iter(), linker.instructions.fromStrLine(), xinst.xinstruction.XInstruction.tokenizeFromASMISALine(), and instructions.xinst.xinstruction.XInstruction.tokenizeFromPISALine().