Encrypted Computing SDK: stages.preprocessor Namespace Reference
stages.preprocessor Namespace Reference
Functions
(nx.Graph, set, set) __dependencyGraphForVars (list insts_list)
Given the listing of instructions, this method returns the dependency graph for the variables in the listing and the sets of destination and source variables.
int injectVariableCopy (MemoryModel mem_model, list insts_list, int instruction_idx, str var_name)
Injects a copy of a variable into the instruction list at the specified index.
def reduceVarDepsByVar (MemoryModel mem_model, list insts_list, str var_name)
Reduces variable dependencies by injecting copies of the specified variable.
str assignRegisterBanksToVars (MemoryModel mem_model, list insts_list, bool use_bank0, verbose=False)
Assigns register banks to variables using vertex coloring graph algorithm.
list preprocessPISAKernelListing (MemoryModel mem_model, line_iter, bool progress_verbose=False)
Parses a P-ISA kernel listing, given as an iterator for strings, where each is a line representing a P-ISA instruction.
Function Documentation
__dependencyGraphForVars()
(nx.Graph, set, set) stages.preprocessor.__dependencyGraphForVars (list insts_list) private
Given the listing of instructions, this method returns the dependency graph for the variables in the listing and the sets of destination and source variables.
Parameters: insts_list (list): List of corresponding pre-processed P-ISA instructions containing the variables to process.
Returns: tuple: A tuple containing:
nx.Graph: Dependency graph for the variables in the listing. Nodes: variable names. Edges: dependencies among variables. Dependencies:
All variables being read from at the same time in any one instruction depend on each other because it is forbidden to read more than once from the same register bank in the same instruction.
All variables being written to at the same time in any one instruction depend on each other because it is forbidden to write more than once to the same register bank in one instruction.
set: Set of all variables (name) that are destinations in the input insts_list.
set: Set of all variables (name) that are sources in the input insts_list.
Definition at line 35 of file preprocessor.py.
Referenced by stages.preprocessor.assignRegisterBanksToVars().
assignRegisterBanksToVars()
str stages.preprocessor.assignRegisterBanksToVars (MemoryModel mem_model, list insts_list, bool use_bank0, verbose = False)
Assigns register banks to variables using vertex coloring graph algorithm.
The variables contained in the MemoryModel object will be modified to reflect their suggested bank.
Parameters: mem_model (MemoryModel): The MemoryModel object, where all variables are kept. Variables detected that are not already in the MemoryModel collection of variables will be added automatically. The variables contained in the MemoryModel object will be modified to reflect their suggested bank. insts_list (list): List of corresponding pre-processed P-ISA instructions containing the variables to process. use_bank0 (bool): All variables are written into registers in bank 0 from SPAD, while no XInst should be writing its results in bank 0 to avoid write-write conflicts. If True, variables that can remain in bank 0 will be kept there (variables that are never written to). If False, bank 0 will not be assigned to any variable. Resulting ASM instructions should add corresponding move instructions to move variables from bank 0 to correct bank. verbose (bool, optional): If True, prints verbose output. Defaults to False.
Raises: ValueError: Thrown for these cases:
Invalid input values for parameters.
Variables in listing cannot be successfully assigned to banks (the number of banks is insufficient to accommodate the listing given the rules). This should not happen, as long as rules are respected, and all instructions have, at most, 3 inputs, and at most, 3 outputs.
Returns: str: The unique dummy variable name that was not used by the collection of variables in the instruction listing.
Definition at line 186 of file preprocessor.py.
References stages.preprocessor.__dependencyGraphForVars(), and stages.preprocessor.reduceVarDepsByVar().
injectVariableCopy()
int stages.preprocessor.injectVariableCopy (MemoryModel mem_model, list insts_list, int instruction_idx, str var_name)
Injects a copy of a variable into the instruction list at the specified index.
Parameters: mem_model (MemoryModel): The memory model containing the variables. insts_list (list): The list of instructions. instruction_idx (int): The index at which to inject the copy. var_name (str): The name of the variable to copy.
Returns: int: Index for the instruction in the list after injection.
Raises: IndexError: If the instruction index is out of range.
Definition at line 85 of file preprocessor.py.
Referenced by stages.preprocessor.reduceVarDepsByVar().
preprocessPISAKernelListing()
list stages.preprocessor.preprocessPISAKernelListing (MemoryModel mem_model, line_iter, bool progress_verbose = False)
Parses a P-ISA kernel listing, given as an iterator for strings, where each is a line representing a P-ISA instruction.
Generates twiddle factors and bit shuffling for original P-ISA xntt instructions.
Variables in mem_model associated with the output will have assigned banks automatically.
Parameters: mem_model (MemoryModel): The MemoryModel object, where all variables are kept. Variables parsed from the input string will be automatically added to the memory model if they do not already exist. The represented object may be modified if addition is needed. line_iter (iterator): Iterator of strings where each is a line of the P-ISA kernel instruction listing. progress_verbose (bool, optional): Specifies whether to output progress every hundred lines processed to stdout. Defaults to False.
Returns: list: A list of BaseInstructions where each object represents the a parsed instruction. Some P-ISA instructions (such as ntts) are converted into a group of XInst that implement the original P-ISA instruction.
Variables in mem_model collection of variables will be modified to reflect assigned bank in suggested_bank attribute.
Definition at line 252 of file preprocessor.py.
reduceVarDepsByVar()
def stages.preprocessor.reduceVarDepsByVar (MemoryModel mem_model, list insts_list, str var_name)
Reduces variable dependencies by injecting copies of the specified variable.
Parameters: mem_model (MemoryModel): The memory model containing the variables. insts_list (list): The list of instructions. var_name (str): The name of the variable to reduce dependencies for.
Definition at line 119 of file preprocessor.py.
References stages.preprocessor.injectVariableCopy().
Referenced by stages.preprocessor.assignRegisterBanksToVars().