Encrypted Computing SDK: main Namespace Reference
main Namespace Reference
Functions
def parse_args ()
Parses command-line arguments for the preprocessing script.
def main_readmem (args)
Reads and processes memory information from a file.
int asmisa_preprocessing (str input_filename, str output_filename, bool b_use_bank_0, b_verbose=True)
Preprocess P-ISA kernel and save the intermediate result.
tuple asmisa_assembly (str output_xinst_filename, str output_cinst_filename, str output_minst_filename, str output_mem_filename, str input_filename, str mem_filename, int max_bundle_size, int hbm_capcity_words, int spad_capacity_words, int num_register_banks=constants.MemoryModel.NUM_REGISTER_BANKS, range register_range=None, b_verbose=True)
Assembles ASM-ISA instructions from preprocessed P-ISA kernel.
def main_asmisa (args)
Main function to run ASM-ISA assembly process.
def main_pisa (args)
Main function to run P-ISA scheduling process.
Variables
module_dir = os.path.dirname(__file__)
module_name = os.path.basename(__file__)
def args = parse_args()
repo_dir = os.path.join(module_dir,"..")
isa_spec_file
Function Documentation
asmisa_assembly()
tuple main.asmisa_assembly (str output_xinst_filename, str output_cinst_filename, str output_minst_filename, str output_mem_filename, str input_filename, str mem_filename, int max_bundle_size, int hbm_capcity_words, int spad_capacity_words, int num_register_banks = constants.MemoryModel.NUM_REGISTER_BANKS, range register_range = None, b_verbose = True)
Assembles ASM-ISA instructions from preprocessed P-ISA kernel.
Parameters: output_xinst_filename (str): The output file for XInst instructions. output_cinst_filename (str): The output file for CInst instructions. output_minst_filename (str): The output file for MInst instructions. output_mem_filename (str): The output file for memory information. input_filename (str): The input file containing the preprocessed P-ISA kernel. mem_filename (str): The file containing memory information. max_bundle_size (int): Maximum number of instructions in a bundle. hbm_capcity_words (int): Capacity of HBM in words. spad_capacity_words (int): Capacity of SPAD in words. num_register_banks (int): Number of register banks. register_range (range): Range of registers. b_verbose (bool): Whether to print verbose output.
Returns: tuple: A tuple containing the number of XInsts, NOPs, idle cycles, dependency timing, and scheduling timing.
Definition at line 137 of file main.py.
References stages.asm_scheduler.scheduleASMISAInstructions().
Referenced by main_asmisa().
asmisa_preprocessing()
int main.asmisa_preprocessing (str input_filename, str output_filename, bool b_use_bank_0, b_verbose = True)
Preprocess P-ISA kernel and save the intermediate result.
Parameters: input_filename (str): The input file containing the P-ISA kernel. output_filename (str): The output file to save the intermediate result. b_use_bank_0 (bool): Whether to use bank 0. b_verbose (bool): Whether to print verbose output.
Returns: int: The time taken for preprocessing in seconds.
Definition at line 84 of file main.py.
Referenced by main_asmisa().
main_asmisa()
def main.main_asmisa (args)
Main function to run ASM-ISA assembly process.
Definition at line 239 of file main.py.
References asmisa_assembly(), and asmisa_preprocessing().
main_pisa()
def main.main_pisa (args)
Main function to run P-ISA scheduling process.
Definition at line 310 of file main.py.
References stages.scheduler.schedulePISAInstructions().
main_readmem()
def main.main_readmem (args)
Reads and processes memory information from a file.
Definition at line 43 of file main.py.
parse_args()
def main.parse_args ()
Parses command-line arguments for the preprocessing script.
This function sets up the argument parser and defines the expected arguments for the script. It returns a Namespace object containing the parsed arguments.
Returns: argparse.Namespace: Parsed command-line arguments.
Definition at line 26 of file main.py.
Variable Documentation
args
def main.args = parse_args()
Definition at line 419 of file main.py.
isa_spec_file
main.isa_spec_file
Definition at line 422 of file main.py.
module_dir
main.module_dir = os.path.dirname(__file__)
Definition at line 414 of file main.py.
module_name
main.module_name = os.path.basename(__file__)
Definition at line 415 of file main.py.
repo_dir
main.repo_dir = os.path.join(module_dir,"..")
Definition at line 421 of file main.py.