Encrypted Computing SDK: deadlock_test Namespace Reference
deadlock_test Namespace Reference
Functions
def makeUniquePath (str path)
Normalizes and expand a given file path.
list loadInstructions (istream)
Loads instructions from an input iterator.
tuple findDeadlock (list minsts, list cinsts)
Searches the CInstQ and MInstQ to find the first deadlock.
def main (str input_dir, str input_prefix=None)
Main function to check for deadlocks in instruction queues.
Variables
module_name = os.path.basename(__file__)
parser = argparse.ArgumentParser()
nargs
args = parser.parse_args()
Function Documentation
findDeadlock()
tuple deadlock_test.findDeadlock (list minsts, list cinsts)
Searches the CInstQ and MInstQ to find the first deadlock.
Parameters: minsts (list): List of MInst instructions. cinsts (list): List of CInst instructions.
Returns: tuple: A tuple of indices where a deadlock was found, or None if no deadlock was found.
Definition at line 61 of file deadlock_test.py.
References inject_bundles.int.
Referenced by main().
loadInstructions()
list deadlock_test.loadInstructions (istream)
Loads instructions from an input iterator.
Parameters: istream: An iterator where each item is a string line considered to contain an instruction.
Returns: list: A list of tuples. Each tuple contains a list of tokens from the comma-separated instruction and the comment.
Definition at line 28 of file deadlock_test.py.
Referenced by main().
main()
def deadlock_test.main (str input_dir, str input_prefix = None)
Main function to check for deadlocks in instruction queues.
Parameters: input_dir (str): The directory containing instruction files. input_prefix (str): The prefix for instruction files.
Definition at line 117 of file deadlock_test.py.
References findDeadlock(), loadInstructions(), and makeUniquePath().
makeUniquePath()
def deadlock_test.makeUniquePath (str path)
Normalizes and expand a given file path.
Parameters: path (str): The file path to normalize and expand.
Returns: str: The normalized and expanded file path.
Definition at line 16 of file deadlock_test.py.
Referenced by main().
Variable Documentation
args
deadlock_test.args = parser.parse_args()
Definition at line 155 of file deadlock_test.py.
Referenced by pisa::poly::PolyOperation.create(), pisa::poly::library.createPolyOperation(), and parseCommandLineArguments().
module_name
deadlock_test.module_name = os.path.basename(__file__)
Definition at line 148 of file deadlock_test.py.
nargs
deadlock_test.nargs
Definition at line 154 of file deadlock_test.py.
parser
deadlock_test.parser = argparse.ArgumentParser()
Definition at line 152 of file deadlock_test.py.