Encrypted Computing SDK: test_he_prep Namespace Reference
test_he_prep Namespace Reference
Functions
def test_main_assigns_and_saves (monkeypatch, tmp_path)
Test that the main function assigns register banks, processes instructions, and saves the output.
def test_main_no_input_file ()
Test that main raises an error when no input file is provided.
def test_main_no_output_file ()
Test that main raises an error when no output file is provided.
def test_main_no_instructions (monkeypatch)
Test that main handles the case where no instructions are processed.
def test_main_invalid_input_file (tmp_path)
Test that main raises an error when the input file does not exist.
def test_main_invalid_output_file (tmp_path)
Test that main raises an error when the output file cannot be created.
def test_parse_args ()
Test that parse_args returns the expected arguments.
Function Documentation
test_main_assigns_and_saves()
def test_he_prep.test_main_assigns_and_saves (monkeypatch, tmp_path)
Test that the main function assigns register banks, processes instructions, and saves the output.
This test uses monkeypatching to mock dependencies and verifies that the output file contains the expected instruction after processing a dummy input file.
Definition at line 22 of file test_he_prep.py.
References he_prep.main().
test_main_invalid_input_file()
def test_he_prep.test_main_invalid_input_file (tmp_path)
Test that main raises an error when the input file does not exist.
Definition at line 96 of file test_he_prep.py.
References he_prep.main().
test_main_invalid_output_file()
def test_he_prep.test_main_invalid_output_file (tmp_path)
Test that main raises an error when the output file cannot be created.
This test checks that the function handles file permission errors gracefully.
Definition at line 110 of file test_he_prep.py.
References he_prep.main().
test_main_no_input_file()
def test_he_prep.test_main_no_input_file ()
Test that main raises an error when no input file is provided.
Definition at line 47 of file test_he_prep.py.
References he_prep.main().
test_main_no_instructions()
def test_he_prep.test_main_no_instructions (monkeypatch)
Test that main handles the case where no instructions are processed.
This test checks that the function can handle an empty instruction list without errors.
Definition at line 69 of file test_he_prep.py.
References he_prep.main().
test_main_no_output_file()
def test_he_prep.test_main_no_output_file ()
Test that main raises an error when no output file is provided.
Definition at line 57 of file test_he_prep.py.
References he_prep.main().
test_parse_args()
def test_he_prep.test_parse_args ()
Test that parse_args returns the expected arguments.
Definition at line 128 of file test_he_prep.py.
References he_prep.parse_args().