Encrypted Computing SDK: order_test Namespace Reference
order_test Namespace Reference
Functions
def parse_args ()
Parses command-line arguments for the preprocessing script.
tuple convertRegNameToTuple (reg_name)
Converts a register name to a tuple representation.
Variables
module_name = os.path.basename(__file__)
def args = parse_args()
def input_file = args.input_file
dictionary register_map = {}
string my_rx = "r[0-9]+b[0-3]"
int prev_pisa_inst = 0
int instr_counter = 0
instr_regs = set()
s_split = s_line.split("#")
pisa_instr_num = int(s_split[1])
match = re.search(my_rx, s)
reg_name = s[match.start():match.end()]
tuple reg = convertRegNameToTuple(reg_name)
list sorted_keys = [x for x in register_map]
error_map = set()
dictionary reg_lst = register_map[reg]
dictionary inverted_map = {}
int prev_in = 0
Function Documentation
convertRegNameToTuple()
tuple order_test.convertRegNameToTuple (reg_name)
Converts a register name to a tuple representation.
Parameters: reg_name (str): The register name in the format 'r<reg>b<bank>'.
Returns: tuple: A tuple containing the bank and register as integers.
Definition at line 38 of file order_test.py.
References inject_bundles.int.
parse_args()
def order_test.parse_args ()
Parses command-line arguments for the preprocessing script.
This function sets up the argument parser and defines the expected arguments for the script. It returns a Namespace object containing the parsed arguments.
Returns: argparse.Namespace: Parsed command-line arguments.
Definition at line 16 of file order_test.py.
Variable Documentation
args
def order_test.args = parse_args()
Definition at line 46 of file order_test.py.
error_map
order_test.error_map = set()
Definition at line 80 of file order_test.py.
input_file
def order_test.input_file = args.input_file
Definition at line 47 of file order_test.py.
instr_counter
int order_test.instr_counter = 0
Definition at line 60 of file order_test.py.
instr_regs
order_test.instr_regs = set()
Definition at line 63 of file order_test.py.
inverted_map
dictionary order_test.inverted_map = {}
Definition at line 86 of file order_test.py.
match
order_test.match = re.search(my_rx, s)
Definition at line 68 of file order_test.py.
Referenced by PISAGraphOptimizer.applyDuplicateInputVariableSeparation().
module_name
order_test.module_name = os.path.basename(__file__)
Definition at line 44 of file order_test.py.
my_rx
string order_test.my_rx = "r[0-9]+b[0-3]"
Definition at line 58 of file order_test.py.
pisa_instr_num
order_test.pisa_instr_num = int(s_split[1])
Definition at line 66 of file order_test.py.
prev_in
dictionary order_test.prev_in = 0
Definition at line 87 of file order_test.py.
prev_pisa_inst
int order_test.prev_pisa_inst = 0
Definition at line 59 of file order_test.py.
reg
tuple order_test.reg = convertRegNameToTuple(reg_name)
Definition at line 73 of file order_test.py.
reg_lst
dictionary order_test.reg_lst = register_map[reg]
Definition at line 85 of file order_test.py.
reg_name
string order_test.reg_name = s[match.start():match.end()]
Definition at line 70 of file order_test.py.
Referenced by pisa::PISAFunctionalModel< T >.getMatching3ParamRegisterNames(), pisa::kernel::PISAKernel.registerNameRoot(), registerNameRoot(), and pisa::Operand.splitLocation().
register_map
dictionary order_test.register_map = {}
Definition at line 56 of file order_test.py.
Referenced by pisa::ProgramMapper< T >.generatePisaProgramFromHEProgram(), generateRegisterMap(), pisa::ProgramMapper< T >.mapKernelInputOutputToRegisterMap(), and pisa::ProgramMapper< T >.mapProgramTraceOperationsIntoRegisterMap().
s_split
order_test.s_split = s_line.split("#")
Definition at line 64 of file order_test.py.
sorted_keys
list order_test.sorted_keys = [x for x in register_map]
Definition at line 78 of file order_test.py.