Encrypted Computing SDK: instructions.xinst.parse_xntt Namespace Reference
instructions.xinst.parse_xntt Namespace Reference
Functions
Namespace parseXNTTKernelLine (str line, str op_name, str tw_separator)
Parses an xntt instruction from a P-ISA kernel instruction string.
(type, Namespace) __generateRMoveParsedOp (Namespace kntt_parsed_op)
Generates a namespace compatible with xrshuffle XInst constructor.
Namespace __generateTWNTTParsedOp (Namespace xntt_parsed_op)
Generates a namespace compatible with twxntt XInst constructor.
list generateXNTT (MemoryModel mem_model, Namespace xntt_parsed_op, int new_id=0)
Parses an xntt instruction from a P-ISA kernel instruction string.
Variables
int __xntt_id
Function Documentation
__generateRMoveParsedOp()
(type, Namespace) instructions.xinst.parse_xntt.__generateRMoveParsedOp (Namespace kntt_parsed_op) private
Generates a namespace compatible with xrshuffle XInst constructor.
Parameters: kntt_parsed_op (Namespace): Parsed xntt object (Namespace).
Returns: tuple: A tuple containing the xrshuffle type and a Namespace with the parsed operation.
Definition at line 94 of file parse_xntt.py.
Referenced by instructions.xinst.parse_xntt.generateXNTT().
__generateTWNTTParsedOp()
Namespace instructions.xinst.parse_xntt.__generateTWNTTParsedOp (Namespace xntt_parsed_op) private
Generates a namespace compatible with twxntt XInst constructor.
Parameters: xntt_parsed_op (Namespace): Parsed kernel xntt object (Namespace).
Returns: tuple: A tuple containing the twxntt type, a Namespace with the parsed operation, and a tuple with the twiddle variable name and suggested bank. The twxntt type is None if a twxntt is not needed for the specified xntt.
Definition at line 133 of file parse_xntt.py.
References inject_bundles.int.
Referenced by instructions.xinst.parse_xntt.generateXNTT().
generateXNTT()
list instructions.xinst.parse_xntt.generateXNTT (MemoryModel mem_model, Namespace xntt_parsed_op, int new_id = 0)
Parses an xntt instruction from a P-ISA kernel instruction string.
Parameters: mem_model (MemoryModel): The MemoryModel object, where all variables are kept. Variables parsed from the input string will be automatically added to the memory model if they do not already exist. The represented object may be modified if addition is needed.
xntt_parsed_op (Namespace): Namespace of parsed xntt from P-ISA.
new_id (int, optional): A new ID for the instruction. Defaults to 0.
Returns: list: A list of xinstruction.XInstruction representing the instructions needed to compute the parsed xntt.
Definition at line 220 of file parse_xntt.py.
References instructions.xinst.parse_xntt.__generateRMoveParsedOp(), and instructions.xinst.parse_xntt.__generateTWNTTParsedOp().
parseXNTTKernelLine()
Namespace instructions.xinst.parse_xntt.parseXNTTKernelLine (str line, str op_name, str tw_separator)
Parses an xntt instruction from a P-ISA kernel instruction string.
Parameters: line (str): The line containing the instruction to parse. Instruction format: N, op_name, dst0, dst1, src0, src1, twiddle, res # comment Comment is optional.
op_name (str): The operation name that should be contained in the line.
tw_separator (str): The separator used in the twiddle information.
Returns: Namespace: A namespace with the following attributes: N (int): Ring size = Log_2(PMD) op_name (str): Operation name dst (list of tuple): List of destinations of the form (variable_name, suggested_bank). src (list of tuple): List of sources of the form (variable_name, suggested_bank). res (int): Residual for the operation. stage (int): Stage number of the current NTT instruction. block (int): Index of current word in the 2-words (16KB) polynomial. comment (str): String with the comment attached to the line (empty string if no comment).
None: If an xntt could not be parsed from the input.
Definition at line 39 of file parse_xntt.py.
References inject_bundles.int.
Variable Documentation
__xntt_id
instructions.xinst.parse_xntt.__xntt_id private
Definition at line 12 of file parse_xntt.py.