Encrypted Computing SDK: test_kerngen Namespace Reference
test_kerngen Namespace Reference
Classes
class Op
Enum class of valid high opnames and corresponding low ops.
Functions
def execute_process (list[str] cmd, data_in=None)
Helper function for executing processes.
def test_op (kerngen_path, gen_op_data)
Test kerngen outputs correct data based on input for various operations.
def test_missing_context (kerngen_path)
Test kerngen raises an exception when context is not the first line of input.
def test_multiple_contexts (kerngen_path)
Test kerngen raises an exception when more than one context is given.
def test_context_options_without_key (kerngen_path)
Test kerngen raises an exception when more than one context is given.
def test_context_unsupported_options_variable (kerngen_path)
Test kerngen raises an exception when more than one context is given.
def test_context_option_invalid_values (kerngen_path, invalid)
Test kerngen raises an exception if value is out of range for correct key.
def test_unrecognised_opname (kerngen_path)
Test kerngen raises an exception when receiving an unrecognised opname.
def test_invalid_scheme (kerngen_path)
Test kerngen raises an exception when receiving an invalid scheme.
def test_invalid_poly_order (kerngen_path, invalid_poly)
Poly order should be powers of two >= 2^14 and <= 2^17.
def test_parse_results_missing_context ()
Test ParseResults constructor for missing context.
def test_parse_results_multiple_context ()
Test ParseResults constructor for multiple context.
def fixture_gen_op_data (request)
Given an op name, return both the input and expected output strings.
Path fixture_kerngen_path ()
Returns the absolute path to the kerngen.py script.
Function Documentation
execute_process()
def test_kerngen.execute_process (list[str] cmd, data_in = None)
Helper function for executing processes.
stdout and stderr are always captured. NOTE: subprocess.run will fail silently with a non-zero exit code so always check the returncode
Definition at line 24 of file test_kerngen.py.
Referenced by test_context_option_invalid_values(), test_context_options_without_key(), test_context_unsupported_options_variable(), test_invalid_poly_order(), test_invalid_scheme(), test_missing_context(), test_multiple_contexts(), test_op(), and test_unrecognised_opname().
fixture_gen_op_data()
def test_kerngen.fixture_gen_op_data (request)
Given an op name, return both the input and expected output strings.
Definition at line 186 of file test_kerngen.py.
fixture_kerngen_path()
Path test_kerngen.fixture_kerngen_path ()
Returns the absolute path to the kerngen.py script.
Definition at line 201 of file test_kerngen.py.
test_context_option_invalid_values()
def test_kerngen.test_context_option_invalid_values (kerngen_path, invalid)
Test kerngen raises an exception if value is out of range for correct key.
Definition at line 101 of file test_kerngen.py.
References execute_process().
test_context_options_without_key()
def test_kerngen.test_context_options_without_key (kerngen_path)
Test kerngen raises an exception when more than one context is given.
Definition at line 73 of file test_kerngen.py.
References execute_process().
test_context_unsupported_options_variable()
def test_kerngen.test_context_unsupported_options_variable (kerngen_path)
Test kerngen raises an exception when more than one context is given.
Definition at line 88 of file test_kerngen.py.
References execute_process().
test_invalid_poly_order()
def test_kerngen.test_invalid_poly_order (kerngen_path, invalid_poly)
Poly order should be powers of two >= 2^14 and <= 2^17.
Definition at line 144 of file test_kerngen.py.
References execute_process().
test_invalid_scheme()
def test_kerngen.test_invalid_scheme (kerngen_path)
Test kerngen raises an exception when receiving an invalid scheme.
Definition at line 131 of file test_kerngen.py.
References execute_process().
test_missing_context()
def test_kerngen.test_missing_context (kerngen_path)
Test kerngen raises an exception when context is not the first line of input.
Definition at line 49 of file test_kerngen.py.
References execute_process().
test_multiple_contexts()
def test_kerngen.test_multiple_contexts (kerngen_path)
Test kerngen raises an exception when more than one context is given.
Definition at line 61 of file test_kerngen.py.
References execute_process().
test_op()
def test_kerngen.test_op (kerngen_path, gen_op_data)
Test kerngen outputs correct data based on input for various operations.
Definition at line 36 of file test_kerngen.py.
References execute_process().
test_parse_results_missing_context()
def test_kerngen.test_parse_results_missing_context ()
Test ParseResults constructor for missing context.
Definition at line 159 of file test_kerngen.py.
test_parse_results_multiple_context()
def test_kerngen.test_parse_results_multiple_context ()
Test ParseResults constructor for multiple context.
Definition at line 167 of file test_kerngen.py.
test_unrecognised_opname()
def test_kerngen.test_unrecognised_opname (kerngen_path)
Test kerngen raises an exception when receiving an unrecognised opname.
Definition at line 117 of file test_kerngen.py.
References execute_process().