Encrypted Computing SDK: linker.loader Namespace Reference
linker.loader Namespace Reference
Functions
list loadMInstKernel (line_iter)
Loads MInstruction kernel from an iterator of lines.
list loadMInstKernelFromFile (str filename)
Loads MInstruction kernel from a file.
list loadCInstKernel (line_iter)
Loads CInstruction kernel from an iterator of lines.
list loadCInstKernelFromFile (str filename)
Loads CInstruction kernel from a file.
list loadXInstKernel (line_iter)
Loads XInstruction kernel from an iterator of lines.
list loadXInstKernelFromFile (str filename)
Loads XInstruction kernel from a file.
Function Documentation
loadCInstKernel()
list linker.loader.loadCInstKernel (line_iter)
Loads CInstruction kernel from an iterator of lines.
Parameters: line_iter: An iterator over lines of CInstruction strings.
Returns: list: A list of CInstruction objects.
Raises: RuntimeError: If a line cannot be parsed into a CInstruction.
Definition at line 58 of file loader.py.
Referenced by linker.loader.loadCInstKernelFromFile().
loadCInstKernelFromFile()
list linker.loader.loadCInstKernelFromFile (str filename)
Loads CInstruction kernel from a file.
Parameters: filename (str): The file containing CInstruction strings.
Returns: list: A list of CInstruction objects.
Raises: RuntimeError: If an error occurs while loading the file.
Definition at line 79 of file loader.py.
References linker.loader.loadCInstKernel().
loadMInstKernel()
list linker.loader.loadMInstKernel (line_iter)
Loads MInstruction kernel from an iterator of lines.
Parameters: line_iter: An iterator over lines of MInstruction strings.
Returns: list: A list of MInstruction objects.
Raises: RuntimeError: If a line cannot be parsed into an MInstruction.
Definition at line 18 of file loader.py.
Referenced by linker.loader.loadMInstKernelFromFile().
loadMInstKernelFromFile()
list linker.loader.loadMInstKernelFromFile (str filename)
Loads MInstruction kernel from a file.
Parameters: filename (str): The file containing MInstruction strings.
Returns: list: A list of MInstruction objects.
Raises: RuntimeError: If an error occurs while loading the file.
Definition at line 39 of file loader.py.
References linker.loader.loadMInstKernel().
loadXInstKernel()
list linker.loader.loadXInstKernel (line_iter)
Loads XInstruction kernel from an iterator of lines.
Parameters: line_iter: An iterator over lines of XInstruction strings.
Returns: list: A list of XInstruction objects.
Raises: RuntimeError: If a line cannot be parsed into an XInstruction.
Definition at line 98 of file loader.py.
Referenced by linker.loader.loadXInstKernelFromFile().
loadXInstKernelFromFile()
list linker.loader.loadXInstKernelFromFile (str filename)
Loads XInstruction kernel from a file.
Parameters: filename (str): The file containing XInstruction strings.
Returns: list: A list of XInstruction objects.
Raises: RuntimeError: If an error occurs while loading the file.
Definition at line 119 of file loader.py.
References linker.loader.loadXInstKernel().