Encrypted Computing SDK: memory_model.mem_utilities Namespace Reference
memory_model.mem_utilities Namespace Reference
Functions
def computePriority (variable, replacement_policy)
Computes the priority for reusing the location of a specified variable.
def flushRegisterBank (register_bank, CycleType current_cycle, replacement_policy, live_var_names=None, float pct=0.5)
Cleans up a register bank by removing variables assigned to registers.
def findAvailableLocation (vars_lst, live_var_names, str replacement_policy=None)
Retrieves the index of the next available location in a collection of Variable objects.
Function Documentation
computePriority()
def memory_model.mem_utilities.computePriority (variable, replacement_policy)
Computes the priority for reusing the location of a specified variable.
The priority is determined based on the replacement policy. The smaller the priority value, the higher the priority for reuse. Tuples are used for staged comparisons.
Args: variable (Variable): The variable for which to compute the priority. replacement_policy (str): The policy to use for determining priority. Must be one of Constants.REPLACEMENT_POLICIES.
Returns: tuple: A tuple representing the priority for reusing the variable's location.
Definition at line 20 of file mem_utilities.py.
Referenced by memory_model.mem_utilities.findAvailableLocation(), and memory_model.mem_utilities.flushRegisterBank().
findAvailableLocation()
def memory_model.mem_utilities.findAvailableLocation (vars_lst, live_var_names, str replacement_policy = None)
Retrieves the index of the next available location in a collection of Variable objects.
The function proposes a location to use if all are occupied, based on a replacement policy. Locations with dummy variables (with empty names) are considered live and will not be selected.
Args: vars_lst (iterable): An iterable collection of Variable objects. Can contain Nones. live_var_names (set or list): A collection of variable names that are not available for replacement. replacement_policy (str, optional): The policy to use for determining which variables to replace. Must be one of Constants.REPLACEMENT_POLICIES. Defaults to None.
Raises: ValueError: If the replacement policy is invalid.
Returns: int: The index of the first empty location found in vars_lst, or the index of the suggested location to replace if vars_lst is full and a replacement policy was specified. Returns -1 if no suitable location is found.
Definition at line 111 of file mem_utilities.py.
References memory_model.mem_utilities.computePriority().
flushRegisterBank()
def memory_model.mem_utilities.flushRegisterBank (register_bank, CycleType current_cycle, replacement_policy, live_var_names = None, float pct = 0.5)
Cleans up a register bank by removing variables assigned to registers.
The function attempts to free up to pct * 100% of registers. Only non-dirty registers that do not contain live variables are cleaned up. Dummy variables are considered live.
Args: register_bank (RegisterBank): The register bank to clean up. current_cycle (CycleType): The current cycle to consider for readiness. replacement_policy (str): The policy to use for determining which variables to replace. Must be one of Constants.REPLACEMENT_POLICIES. live_var_names (set or list, optional): A collection of variable names that are not available for replacement. Defaults to None. pct (float, optional): The fraction of the register bank to clean up. Defaults to 0.5.
Definition at line 60 of file mem_utilities.py.
References memory_model.mem_utilities.computePriority().