Encrypted Computing SDK: common.constants Namespace Reference
common.constants Namespace Reference
Classes
class Constants
Contains project level and global constants that won't fit logically into any other category.
class MemInfo
Constants related to memory information, read from the P-ISA kernel memory file.
class MemoryModel
Constants related to memory model.
Functions
int convertBytes2Words (int bytes)
Converts a size in bytes to the equivalent number of words.
int convertWords2Bytes (int words)
Converts a size in words to the equivalent number of bytes.
Function Documentation
convertBytes2Words()
int common.constants.convertBytes2Words (int bytes)
Converts a size in bytes to the equivalent number of words.
Args: bytes (int): The size in bytes to be converted.
Returns: int: The equivalent size in words.
Definition at line 132 of file constants.py.
References inject_bundles.int.
Referenced by common.constants.MemoryModel.CINST_QUEUE_MAX_CAPACITY_WORDS(), common.constants.MemoryModel.HBM.MAX_CAPACITY_WORDS(), common.constants.MemoryModel.SPAD.MAX_CAPACITY_WORDS(), common.constants.MemoryModel.MINST_QUEUE_MAX_CAPACITY_WORDS(), common.constants.MemoryModel.STORE_BUFFER_MAX_CAPACITY_WORDS(), and common.constants.MemoryModel.XINST_QUEUE_MAX_CAPACITY_WORDS().
convertWords2Bytes()
int common.constants.convertWords2Bytes (int words)
Converts a size in words to the equivalent number of bytes.
Args: words (int): The size in words to be converted.
Returns: int: The equivalent size in bytes.
Definition at line 144 of file constants.py.