Encrypted Computing SDK: kerngen.pisa_generators.basic Namespace Reference
kerngen.pisa_generators.basic Namespace Reference
Classes
class CartesianOp
Class representing the high-level cartesian operation.
class Add
Class representing the high-level addition operation.
class Sub
Class representing the high-level subtraction operation.
class Mul
Class representing the high-level multiplication operation.
class Muli
Class representing the high-level multiplication operation.
class Copy
Class representing the high-level copy operation.
class KeyMul
Class representing a key multiplication operation.
class PartialOpOptions
Optional arguments for partial_op helper function.
class PartialOpPolys
Polynomials used in partial ops.
Functions
list[PIsaOp] mixed_to_pisa_ops (*args)
Transform mixed list of op types to PIsaOp only.
list[PIsaOp] _mixed_to_pisa_ops (Iterable[PIsaOp|list[PIsaOp]|HighOp] ops)
Helper to process mixed list of op types to PIsaOp only.
list[InIdxs] convolution_indices (Polys input0, Polys input1)
Helper gives convolution of parts indices.
Tuple[Polys, Polys, Polys] extract_last_part_polys (Polys input0, int rns)
Split and extract the last part of input0 with a change of rns.
Tuple[Polys, Polys] split_last_rns_polys (Polys input0, current_rns)
Split and extract last RNS of input0.
Polys duplicate_polys (Polys input0, str name)
Creates a duplicate of input0 with new name.
Tuple[Immediate, Immediate, Immediate] common_immediates (r2_rns=None, iq_rns=None, iq_suffix="")
Generate commonly used immediates.
def partial_op (KernelContext context, op, PartialOpPolys polys, PartialOpOptions options, int last_q)
"A helper function to perform partial operation, such as add/sub on last half (input1) to all of input0
def add_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Add input0 to input1 (first part)
def sub_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Subtract input1 (first part) with input0 (last RNS)
def muli_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Muli input0/1 w/input0 last RNS.
Variables
InIdxs = list[tuple[int, int]]
Function Documentation
_mixed_to_pisa_ops()
list[PIsaOp] kerngen.pisa_generators.basic._mixed_to_pisa_ops (Iterable[PIsaOp | list[PIsaOp] | HighOp] ops) private
Helper to process mixed list of op types to PIsaOp only.
Definition at line 34 of file basic.py.
Referenced by kerngen.pisa_generators.basic.mixed_to_pisa_ops().
add_last_half()
def kerngen.pisa_generators.basic.add_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Add input0 to input1 (first part)
Definition at line 402 of file basic.py.
References kerngen.pisa_generators.basic.partial_op().
Referenced by kerngen.pisa_generators.rescale.Rescale.to_pisa().
common_immediates()
Tuple[Immediate, Immediate, Immediate] kerngen.pisa_generators.basic.common_immediates (r2_rns = None, iq_rns = None, iq_suffix = "")
Generate commonly used immediates.
Definition at line 337 of file basic.py.
Referenced by kerngen.pisa_generators.mod.Mod.to_pisa(), and kerngen.pisa_generators.rescale.Rescale.to_pisa().
convolution_indices()
list[InIdxs] kerngen.pisa_generators.basic.convolution_indices (Polys input0, Polys input1)
Helper gives convolution of parts indices.
Definition at line 120 of file basic.py.
Referenced by kerngen.pisa_generators.basic.Mul.to_pisa().
duplicate_polys()
Polys kerngen.pisa_generators.basic.duplicate_polys (Polys input0, str name)
Creates a duplicate of input0 with new name.
Definition at line 332 of file basic.py.
Referenced by kerngen.pisa_generators.mod.Mod.to_pisa(), and kerngen.pisa_generators.rescale.Rescale.to_pisa().
extract_last_part_polys()
Tuple[Polys, Polys, Polys] kerngen.pisa_generators.basic.extract_last_part_polys (Polys input0, int rns)
Split and extract the last part of input0 with a change of rns.
Definition at line 303 of file basic.py.
Referenced by kerngen.pisa_generators.relin.Relin.to_pisa(), and kerngen.pisa_generators.rotate.Rotate.to_pisa().
mixed_to_pisa_ops()
list[PIsaOp] kerngen.pisa_generators.basic.mixed_to_pisa_ops (* args)
Transform mixed list of op types to PIsaOp only.
Definition at line 25 of file basic.py.
References kerngen.pisa_generators.basic._mixed_to_pisa_ops().
Referenced by kerngen.kerngraph.main(), kerngen.pisa_generators.decomp.DigitDecompExtend.to_pisa(), kerngen.pisa_generators.mod.ModUp.to_pisa(), kerngen.pisa_generators.ntt.NTT.to_pisa(), kerngen.pisa_generators.ntt.INTT.to_pisa(), kerngen.pisa_generators.relin.Relin.to_pisa(), kerngen.pisa_generators.rescale.Rescale.to_pisa(), kerngen.pisa_generators.rotate.Rotate.to_pisa(), and kerngen.pisa_generators.square.Square.to_pisa().
muli_last_half()
def kerngen.pisa_generators.basic.muli_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Muli input0/1 w/input0 last RNS.
Definition at line 444 of file basic.py.
References kerngen.pisa_generators.basic.partial_op().
partial_op()
def kerngen.pisa_generators.basic.partial_op (KernelContext context, op, PartialOpPolys polys, PartialOpOptions options, int last_q)
"A helper function to perform partial operation, such as add/sub on last half (input1) to all of input0
Definition at line 373 of file basic.py.
Referenced by kerngen.pisa_generators.basic.add_last_half(), kerngen.pisa_generators.basic.muli_last_half(), and kerngen.pisa_generators.basic.sub_last_half().
split_last_rns_polys()
Tuple[Polys, Polys] kerngen.pisa_generators.basic.split_last_rns_polys (Polys input0, current_rns)
Split and extract last RNS of input0.
Definition at line 319 of file basic.py.
Referenced by kerngen.pisa_generators.mod.Mod.to_pisa(), and kerngen.pisa_generators.rescale.Rescale.to_pisa().
sub_last_half()
def kerngen.pisa_generators.basic.sub_last_half (KernelContext context, Polys output, Polys input0, Polys input1, Polys input_remaining_rns, int last_q)
Subtract input1 (first part) with input0 (last RNS)
Definition at line 426 of file basic.py.
References kerngen.pisa_generators.basic.partial_op().
Referenced by kerngen.pisa_generators.rescale.Rescale.to_pisa().
Variable Documentation
InIdxs
kerngen.pisa_generators.basic.InIdxs = list[tuple[int, int]]
Definition at line 116 of file basic.py.