Encrypted Computing SDK: stages.scheduler Namespace Reference
stages.scheduler Namespace Reference
Functions
list __orderKeygenVars (MemoryModel mem_model)
Returns the name of the keygen variables in the order they have to be generated.
tuple __findVarInPrevDeps (nx.DiGraph deps_graph, tuple instr_id, str var_name, bool b_only_sources=False)
Returns the ID for an instruction that uses the specified variable, and is a dependency for input instruction.
def enforceKeygenOrdering (nx.DiGraph deps_graph, MemoryModel mem_model, verbose_ostream=None)
Given the dependency graph for instructions and a complete memory model, injects instructions and dependencies to enforce ordering required for the keygen subsystem.
nx.DiGraph generateInstrDependencyGraph (list insts_listing, verbose_ostream=None)
Given a pre-processed P-ISA instructions listing, generates a dependency graph for the instructions based on their inputs and outputs, and any shared HW resources among instructions.
(list, int, int) schedulePISAInstructions (nx.DiGraph dependency_graph, bool progress_verbose=False)
Given the dependency directed acyclic graph of XInsts, returns a schedule for the corresponding P-ISA instructions, that minimizes idle cycles.
Variables
__instruction
Function Documentation
__findVarInPrevDeps()
tuple stages.scheduler.__findVarInPrevDeps (nx.DiGraph deps_graph, tuple instr_id, str var_name, bool b_only_sources = False) private
Returns the ID for an instruction that uses the specified variable, and is a dependency for input instruction.
Parameters: deps_graph (nx.DiGraph): Completed graph of dependencies among the instructions in the input listing. instr_id (tuple): ID of instruction for which to find dependency. var_name (str): Name of the variable that must be present in dependency. b_only_sources (bool, optional): If True, only source variables are scanned. Otherwise, all variables are checked when determining if var_name is in dependency instruction.
Returns: tuple or None: ID of first instruction found which is direct or indirect dependency of instr_id in the dependency graph. The returned instruction must have var_name as one of its variables. If no instruction is found, returns None.
Definition at line 64 of file scheduler.py.
Referenced by stages.scheduler.enforceKeygenOrdering().
__orderKeygenVars()
list stages.scheduler.__orderKeygenVars (MemoryModel mem_model) private
Returns the name of the keygen variables in the order they have to be generated.
Parameters: mem_model (MemoryModel): Completed memory model corresponding to the specified dependency graph and input mem info. Used to extract the keygen variable information.
Raises: RuntimeError: Detected missing keygen variable in ordering.
Returns: list: A list of lists. Each element of the outer list represents a seed. Each element in the inner list is the name of the keygen variable corresponding to that index ordering for the corresponding seed.
Definition at line 30 of file scheduler.py.
Referenced by stages.scheduler.enforceKeygenOrdering().
enforceKeygenOrdering()
def stages.scheduler.enforceKeygenOrdering (nx.DiGraph deps_graph, MemoryModel mem_model, verbose_ostream = None)
Given the dependency graph for instructions and a complete memory model, injects instructions and dependencies to enforce ordering required for the keygen subsystem.
For all keygen variables of the same seed, copy instructions are injected and all instructions using the same keygen variable as the copy instruction become dependent of said copy. This ensures that the variable is generated before it is used. Furthermore, copy instructions depend on each other based on the ordering of the keygen variables. This ensures correct ordering of key material generation.
Parameters: deps_graph (nx.DiGraph): Completed graph of dependencies among the instructions in the input listing. Will be changed with the injected instructions and dependencies. mem_model (MemoryModel): Completed memory model corresponding to the specified dependency graph and input mem info. Will be changed if new variables are needed during injection. verbose_ostream: Stream where to print verbose output (object with a write method). If None, no verbose output occurs.
Definition at line 112 of file scheduler.py.
References stages.scheduler.__findVarInPrevDeps(), and stages.scheduler.__orderKeygenVars().
generateInstrDependencyGraph()
nx.DiGraph stages.scheduler.generateInstrDependencyGraph (list insts_listing, verbose_ostream = None)
Given a pre-processed P-ISA instructions listing, generates a dependency graph for the instructions based on their inputs and outputs, and any shared HW resources among instructions.
Parameters: insts_listing (list): List of pre-processed P-ISA instructions. verbose_ostream: Stream where to print verbose output (object with a write method). If None, no verbose output occurs.
Raises: nx.NetworkXUnfeasible: Input listing results in a dependency graph that is not a Directed Acyclic Graph.
Returns: nx.DiGraph: A Directed Acyclic Graph representing the dependencies among the instructions in the input listing.
Definition at line 204 of file scheduler.py.
schedulePISAInstructions()
(list, int, int) stages.scheduler.schedulePISAInstructions (nx.DiGraph dependency_graph, bool progress_verbose = False)
Given the dependency directed acyclic graph of XInsts, returns a schedule for the corresponding P-ISA instructions, that minimizes idle cycles.
Parameters: dependency_graph (nx.DiGraph): The dependency graph of XInsts. progress_verbose (bool, optional): If True, prints progress information. Defaults to False.
Returns: tuple: A tuple containing:
list: The scheduled instructions.
int: The total number of idle cycles.
int: The number of NOPs inserted.
Definition at line 337 of file scheduler.py.
Referenced by main.main_pisa().
Variable Documentation
__instruction
stages.scheduler.__instruction private
Definition at line 344 of file scheduler.py.