Encrypted Computing SDK: he_as Namespace Reference
he_as Namespace Reference
Classes
class AssemblerRunConfig
Maintains the configuration data for the run.
Functions
tuple asmisaAssemble (run_config, str output_minst_filename, str output_cinst_filename, str output_xinst_filename, b_verbose=True)
Assembles the P-ISA kernel into ASM-ISA instructions and saves them to specified output files.
def main (AssemblerRunConfig config, bool verbose=False)
Executes the assembly process using the provided configuration.
def parse_args ()
Parses command-line arguments for the assembler script.
Variables
script_dir = os.path.dirname(os.path.realpath(__file__))
string DEFAULT_XINST_FILE_EXT = "xinst"
string DEFAULT_CINST_FILE_EXT = "cinst"
string DEFAULT_MINST_FILE_EXT = "minst"
string DEFAULT_MEM_FILE_EXT = "mem"
module_dir = os.path.dirname(__file__)
module_name = os.path.basename(__file__)
def args = parse_args()
isa_spec_file
mem_spec_file
config = AssemblerRunConfig(**vars(args))
verbose
Function Documentation
asmisaAssemble()
tuple he_as.asmisaAssemble (run_config, str output_minst_filename, str output_cinst_filename, str output_xinst_filename, b_verbose = True)
Assembles the P-ISA kernel into ASM-ISA instructions and saves them to specified output files.
This function reads the input kernel file, interprets variable meta information, generates a dependency graph, schedules ASM-ISA instructions, and saves the results to output files.
Args: run_config: The configuration object containing run parameters. output_minst_filename (str): The filename for saving MINST instructions. output_cinst_filename (str): The filename for saving CINST instructions. output_xinst_filename (str): The filename for saving XINST instructions. b_verbose (bool): Flag indicating whether verbose output is enabled.
Returns: tuple: A tuple containing the number of XInstructions, number of NOPs, number of idle cycles, dependency timing, and scheduling timing.
Definition at line 194 of file he_as.py.
References stages.asm_scheduler.scheduleASMISAInstructions().
Referenced by main().
main()
def he_as.main (AssemblerRunConfig config, bool verbose = False)
Executes the assembly process using the provided configuration.
This function sets up the output directory, initializes output filenames, tests output writability, and performs the assembly process, printing results if verbose output is enabled.
Args: config (AssemblerRunConfig): The configuration object containing run parameters. verbose (bool): Flag indicating whether verbose output is enabled.
Returns: None
Definition at line 305 of file he_as.py.
References asmisaAssemble().
parse_args()
def he_as.parse_args ()
Parses command-line arguments for the assembler script.
This function sets up the argument parser and defines the expected arguments for the script. It returns a Namespace object containing the parsed arguments.
Returns: argparse.Namespace: Parsed command-line arguments.
Definition at line 366 of file he_as.py.
Variable Documentation
args
def he_as.args = parse_args()
Definition at line 407 of file he_as.py.
config
he_as.config = AssemblerRunConfig(**vars(args))
Definition at line 411 of file he_as.py.
Referenced by addInstructionTest.constructTest(), copyInstructionTest.constructTest(), inttInstructionTest.constructTest(), macInstructionTest.constructTest(), maciInstructionTest.constructTest(), mulInstructionTest.constructTest(), muliInstructionTest.constructTest(), nttInstructionTest.constructTest(), RandomStreamInstructionTest.constructTest(), subInstructionTest.constructTest(), AddOperation.constructTest(), AddCorrected.constructTest(), AddPlain.constructTest(), BaseOperation.constructTest(), ChainedAdds.constructTest(), Intt.constructTest(), ModSwitchOperation.constructTest(), MulOperation.constructTest(), MulPlainOperation.constructTest(), MultiplyConstantInplaceOperation.constructTest(), NttOperation.constructTest(), RelinOperation.constructTest(), RescaleOperation.constructTest(), RotateOperation.constructTest(), SquareOperation.constructTest(), WideAdd.constructTest(), pisa::performance::PISAPerformanceModeler.generateAndPrintPerformanceReport(), and pisa::performance::PISAPerformanceModeler.generateInstructionAndMemoryPerformanceGraphReport().
DEFAULT_CINST_FILE_EXT
string he_as.DEFAULT_CINST_FILE_EXT = "cinst"
Definition at line 49 of file he_as.py.
DEFAULT_MEM_FILE_EXT
string he_as.DEFAULT_MEM_FILE_EXT = "mem"
Definition at line 51 of file he_as.py.
DEFAULT_MINST_FILE_EXT
string he_as.DEFAULT_MINST_FILE_EXT = "minst"
Definition at line 50 of file he_as.py.
DEFAULT_XINST_FILE_EXT
string he_as.DEFAULT_XINST_FILE_EXT = "xinst"
Definition at line 48 of file he_as.py.
isa_spec_file
he_as.isa_spec_file
Definition at line 408 of file he_as.py.
mem_spec_file
he_as.mem_spec_file
Definition at line 409 of file he_as.py.
module_dir
he_as.module_dir = os.path.dirname(__file__)
Definition at line 403 of file he_as.py.
module_name
he_as.module_name = os.path.basename(__file__)
Definition at line 404 of file he_as.py.
script_dir
he_as.script_dir = os.path.dirname(os.path.realpath(__file__))
Definition at line 45 of file he_as.py.
verbose
he_as.verbose
Definition at line 422 of file he_as.py.
Referenced by pisa::kernel::PISAKernel.create(), pisa::kernel::PISAKernel.create_legacy(), pisa::kernel::PISAKernel.create_new(), pisa::kernel::PISAKernel.createHECDataFormats(), and pisa::kernel::PISAKernel.updateSymbols().