Encrypted Computing SDK: p-isa_tools/program_mapper/p_isa/pisakernel.cpp File Reference
pisakernel.cpp File Reference
#include <algorithm>
#include <filesystem>
#include <sstream>
#include <common/p_isa/parser/p_isa_parser.h>
#include <program_mapper/p_isa/pisakernel.h>
#include <program_mapper/poly_program/polynomial.h>
Namespaces
pisa
pisa::kernel
Functions
std::string genKernInput (const pisa::poly::PolyOperation &op)
std::filesystem::path createKernelFilepath (const pisa::poly::PolyOperation &op, const pisa::kernel::Cache &kernel_cache)
bool containsString (const std::string &value, const std::string &substring)
Variables
static unsigned int pisa::kernel::global_kernel_id_counter = 0
Function Documentation
containsString()
bool containsString (const std::string & value, const std::string & substring)
Definition at line 457 of file pisakernel.cpp.
Referenced by pisa::kernel::PISAKernel::determineVariableNamingViaGraph().
createKernelFilepath()
std::filesystem::path createKernelFilepath (const pisa::poly::PolyOperation & op, const pisa::kernel::Cache & kernel_cache)
Definition at line 82 of file pisakernel.cpp.
References pisa::kernel::Cache::getDirname(), pisa::poly::PolyOperation::getInputLocations(), pisa::poly::PolyOperation::Name(), pisa::poly::PolyOperation::parentProgram(), and toString().
Referenced by pisa::kernel::PISAKernel::create_new().
genKernInput()
std::string genKernInput (const pisa::poly::PolyOperation & op)
Definition at line 29 of file pisakernel.cpp.
References pisa::poly::PolyOperation::getInputLocations(), pisa::poly::PolyOperation::getInputOperand(), pisa::poly::PolyOperation::getOutputLocations(), pisa::poly::PolyOperation::Name(), pisa::poly::Polynomial::num_of_rns_terms, pisa::poly::PolyOperation::numInputOperands(), pisa::poly::PolyOperation::numOutputOperands(), pisa::poly::PolyOperation::parentProgram(), and toString().
Referenced by pisa::kernel::PISAKernel::create_new().