Encrypted Computing SDK: p-isa_tools/program_mapper/poly_program/polyprogram.cpp File Reference
polyprogram.cpp File Reference
#include "polyprogram.h"
#include <stdexcept>
Namespaces
pisa
pisa::poly
Functions
std::string toString (SCHEME scheme, bool lowercase)
SCHEME fromString (std::string scheme)
Function Documentation
fromString()
SCHEME fromString (std::string scheme)
Definition at line 390 of file polyprogram.cpp.
References BFV, BGV, and CKKS.
Referenced by AddCorrected::constructTest(), PolynomialProgramHelper::parse_FHE_SCHEME(), and pisa::poly::PolyOperation::PolyOperation().
toString()
std::string toString (SCHEME scheme, bool lowercase)
Definition at line 7 of file polyprogram.cpp.
References BFV, BGV, and CKKS.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::createHECDataFormats(), createKernelFilepath(), PolynomialProgramHelper::extract_FHE_SCHEME(), and genKernInput().