Encrypted Computing SDK: p-isa_tools/program_mapper/poly_program/polyprogram.h File Reference
polyprogram.h File Reference
#include <iostream>
#include <map>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>
#include "operations/core.h"
#include "polynomial.h"
Classes
class pisa::poly::PolyProgram
The PolyProgram class holds a collection of Polynomial Operations and context information in which to perform those operations.
struct pisa::poly::Operand
class pisa::poly::PolyOperation
The PolyOperation class represents a polynomial operation involving 1 or more input polynomial objects.
class ProgramTrace
Namespaces
pisa
pisa::poly
Enumerations
enum class SCHEME { BGV , CKKS , BFV }
enum pisa::poly::ValueType {
pisa::poly::UINT32 = 0 , pisa::poly::UINT64 = 1 , pisa::poly::INT32 = 2 , pisa::poly::INT64 = 3 ,
pisa::poly::FLOAT = 4 , pisa::poly::DOUBLE = 5 , pisa::poly::STRING = 6
}
Functions
std::string toString (SCHEME scheme, bool lowercase=false)
SCHEME fromString (std::string scheme)
Variables
static PolyProgram pisa::poly::default_global_poly_program
Enumeration Type Documentation
SCHEME
enum SCHEME strong
Enumerator
BGV
CKKS
BFV
Definition at line 20 of file polyprogram.h.
Function Documentation
fromString()
SCHEME fromString (std::string scheme)
Definition at line 390 of file polyprogram.cpp.
References BFV, BGV, and CKKS.
Referenced by AddCorrected::constructTest(), PolynomialProgramHelper::parse_FHE_SCHEME(), and pisa::poly::PolyOperation::PolyOperation().
toString()
std::string toString (SCHEME scheme, bool lowercase = false)
Definition at line 7 of file polyprogram.cpp.
References BFV, BGV, and CKKS.
Referenced by pisa::kernel::PISAKernel::create_legacy(), pisa::kernel::PISAKernel::createHECDataFormats(), createKernelFilepath(), PolynomialProgramHelper::extract_FHE_SCHEME(), and genKernInput().