Encrypted Computing SDK: p-isa_tools/program_mapper/main.cpp File Reference
main.cpp File Reference
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include "p_isa/pisa_test_generator.h"
#include "program_mapper.h"
#include <common/graph/graph.h>
#include <common/p_isa/p_isa.h>
#include <common/timer/timer.h>
#include <functional_modeler/data_handlers/json_data_handler.h>
#include <program_mapper/p_isa/pisa_graph_optimizer.h>
#include <program_mapper/p_isa/pisakernel.h>
#include <program_mapper/trace_parser/program_trace_helper.h>
#include <argmap.h>
Typedefs
using DATA_TYPE = uint32_t
Functions
pisa::ProgramMapperArguments parseCommandLineArguments (int argc, char **argv)
int main (int argc, char **argv)
Typedef Documentation
DATA_TYPE
using DATA_TYPE = uint32_t
Definition at line 22 of file main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 83 of file main.cpp.
References CSV, pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram(), PolynomialProgramHelper::parse(), parseCommandLineArguments(), PROTOBUFF, pisa::ProgramMapper< T >::setArguments(), and PolynomialProgramHelper::writeTraceToCSV().
parseCommandLineArguments()
pisa::ProgramMapperArguments parseCommandLineArguments (int argc, char ** argv)
Definition at line 25 of file main.cpp.
References deadlock_test::args.