Encrypted Computing SDK: p-isa_tools/program_mapper/utility_functions.h File Reference
utility_functions.h File Reference
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include "p_isa/pisa_test_generator.h"
#include "program_mapper.h"
#include <common/graph/graph.h>
#include <common/p_isa/p_isa.h>
#include <common/timer/timer.h>
#include <functional_modeler/data_handlers/json_data_handler.h>
#include <program_mapper/p_isa/pisa_graph_optimizer.h>
#include <program_mapper/p_isa/pisakernel.h>
#include <program_mapper/trace_parser/program_trace_helper.h>
Typedefs
using DATA_TYPE = uint32_t
Functions
std::vector< std::string > generateMemFile (const graph::Graph< pisa::PISAInstruction > &graph, int max_rns_terms)
std::string registerNameRoot (const std::string &reg_name)
registerNameRoot Attempts to split a register name removing the RNS and block terms.
template<typename T >
std::vector< std::string > nonRepeatingRoots (const T &xputs)
template<typename T >
std::vector< std::string > nonRepeatingRootsNode (const T &xputs)
std::map< std::string, std::string > generateRegisterMap (const JSONDataHandler< DATA_TYPE > &input_parser_v0)
generateRegisterMap Maps all input/output variable name roots in trace to a map structure. Current structure is 1 : 1
void dumpMapToFile (const std::string &file_name, const std::map< std::string, std::string > &map)
template<typename T , typename FN >
void writeToFileBy (const std::string &filename, const std::vector< T > &inputs, FN fn)
Typedef Documentation
DATA_TYPE
using DATA_TYPE = uint32_t
Definition at line 22 of file utility_functions.h.
Function Documentation
dumpMapToFile()
void dumpMapToFile (const std::string & file_name, const std::map< std::string, std::string > & map)
Definition at line 157 of file utility_functions.h.
generateMemFile()
std::vector<std::string> generateMemFile (const graph::Graph< pisa::PISAInstruction > & graph, int max_rns_terms)
Definition at line 25 of file utility_functions.h.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().
generateRegisterMap()
std::map<std::string, std::string> generateRegisterMap (const JSONDataHandler< DATA_TYPE > & input_parser_v0)
generateRegisterMap Maps all input/output variable name roots in trace to a map structure. Current structure is 1 : 1
Parameters
input_parser_v0
Returns
Definition at line 122 of file utility_functions.h.
References JSONDataHandler< T >::getAllInputs(), JSONDataHandler< T >::getAllIntermediatess(), JSONDataHandler< T >::getAllOutputs(), nonRepeatingRoots(), and order_test::register_map.
nonRepeatingRoots()
template<typename T > std::vector<std::string> nonRepeatingRoots (const T & xputs)
Definition at line 86 of file utility_functions.h.
Referenced by generateRegisterMap().
nonRepeatingRootsNode()
template<typename T > std::vector<std::string> nonRepeatingRootsNode (const T & xputs)
Definition at line 102 of file utility_functions.h.
Referenced by pisa::kernel::PISAKernel::determineVariableNamingViaGraph().
registerNameRoot()
std::string registerNameRoot (const std::string & reg_name)
registerNameRoot Attempts to split a register name removing the RNS and block terms.
Todo:
Need to account for outlier cases when naming doesn't match
Parameters
location
Returns
Definition at line 79 of file utility_functions.h.
References order_test::reg_name.
Referenced by pisa::kernel::PISAKernel::nonRepeatingRootsNode().
writeToFileBy()
template<typename T , typename FN > void writeToFileBy (const std::string & filename, const std::vector< T > & inputs, FN fn)
Definition at line 169 of file utility_functions.h.
Referenced by pisa::ProgramMapper< T >::generatePisaProgramFromHEProgram().