Encrypted Computing SDK: PolynomialProgramHelper Struct Reference
PolynomialProgramHelper Struct Reference
#include <program_trace_helper.h>
Public Member Functions
PolynomialProgramHelper ()=default
Static Public Member Functions
static std::shared_ptr< pisa::poly::PolyProgram > parse (const std::string &filename_or_prefix, POLYNOMIAL_PROGRAM_FORMAT format=CSV, bool ignore_header=true)
static std::shared_ptr< pisa::poly::PolyProgram > parseCSV (const std::string &filename, bool ignore_header=true)
static void writeTraceToCSV (const std::shared_ptr< pisa::poly::PolyProgram > trace, std::string file_name)
static std::shared_ptr< pisa::poly::PolyOperation > parseInstruction (const std::vector< std::string > &components, std::shared_ptr< pisa::poly::PolyProgram > program)
static std::vector< std::string > writeToASCIIComponents (const std::shared_ptr< pisa::poly::PolyOperation > operation)
static void parseComponent (const std::string &component, PARAM_TYPE type, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void extractComponent (const std::shared_ptr< pisa::poly::PolyOperation > instr, std::string &component, int component_index)
static void parse_OP_NAME (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_CIPHER_DEGREE (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_INPUT_ARGUMENT (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_OUTPUT_ARGUMENT (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_INPUT_OUTPUT_ARGUMENT (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_POLYMOD_DEG_LOG2 (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_RNS_TERM (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_FHE_SCHEME (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_GALOIS_ELT (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_FACTOR (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_KEY_RNS (const std::string &component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void parse_PARAM (const std::pair< std::string, std::pair< std::string, pisa::poly::ValueType >> component, std::shared_ptr< pisa::poly::PolyOperation > instr)
static void extract_OP_NAME (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_CIPHER_DEGREE (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_INPUT_ARGUMENT (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_OUTPUT_ARGUMENT (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_INPUT_OUTPUT_ARGUMENT (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_POLYMOD_DEG_LOG2 (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_RNS_TERM (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_FHE_SCHEME (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_GALOIS_ELT (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_FACTOR (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_KEY_RNS (std::string &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
static void extract_PARAM (std::pair< std::string, std::pair< std::string, pisa::poly::ValueType >> &component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index)
Static Public Attributes
constexpr static int OP_CODE_LOCATION = 0
Detailed Description
Definition at line 25 of file program_trace_helper.h.
Constructor & Destructor Documentation
PolynomialProgramHelper()
PolynomialProgramHelper::PolynomialProgramHelper () default
Member Function Documentation
extract_CIPHER_DEGREE()
void PolynomialProgramHelper::extract_CIPHER_DEGREE (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 499 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_FACTOR()
void PolynomialProgramHelper::extract_FACTOR (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 566 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_FHE_SCHEME()
void PolynomialProgramHelper::extract_FHE_SCHEME (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 556 of file program_trace_helper.cpp.
References toString().
Referenced by extractComponent().
extract_GALOIS_ELT()
void PolynomialProgramHelper::extract_GALOIS_ELT (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 561 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_INPUT_ARGUMENT()
void PolynomialProgramHelper::extract_INPUT_ARGUMENT (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 504 of file program_trace_helper.cpp.
References pisa::poly::INPUT_ARGUMENT, and pisa::poly::INPUT_OUTPUT_ARGUMENT.
Referenced by extractComponent().
extract_INPUT_OUTPUT_ARGUMENT()
void PolynomialProgramHelper::extract_INPUT_OUTPUT_ARGUMENT (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 532 of file program_trace_helper.cpp.
References pisa::poly::INPUT_OUTPUT_ARGUMENT, and pisa::poly::OUTPUT_ARGUMENT.
Referenced by extractComponent().
extract_KEY_RNS()
void PolynomialProgramHelper::extract_KEY_RNS (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 571 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_OP_NAME()
void PolynomialProgramHelper::extract_OP_NAME (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 494 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_OUTPUT_ARGUMENT()
void PolynomialProgramHelper::extract_OUTPUT_ARGUMENT (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 518 of file program_trace_helper.cpp.
References pisa::poly::INPUT_OUTPUT_ARGUMENT, and pisa::poly::OUTPUT_ARGUMENT.
Referenced by extractComponent().
extract_PARAM()
void PolynomialProgramHelper::extract_PARAM (std::pair< std::string, std::pair< std::string, pisa::poly::ValueType >> & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 576 of file program_trace_helper.cpp.
References pisa::poly::PARAM.
extract_POLYMOD_DEG_LOG2()
void PolynomialProgramHelper::extract_POLYMOD_DEG_LOG2 (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 546 of file program_trace_helper.cpp.
Referenced by extractComponent().
extract_RNS_TERM()
void PolynomialProgramHelper::extract_RNS_TERM (std::string & component, const std::shared_ptr< pisa::poly::PolyOperation > instr, int component_index) static
Definition at line 551 of file program_trace_helper.cpp.
Referenced by extractComponent().
extractComponent()
void PolynomialProgramHelper::extractComponent (const std::shared_ptr< pisa::poly::PolyOperation > instr, std::string & component, int component_index) static
Definition at line 377 of file program_trace_helper.cpp.
References pisa::poly::ALPHA, pisa::poly::CIPHER_DEGREE, pisa::poly::DNUM, extract_CIPHER_DEGREE(), extract_FACTOR(), extract_FHE_SCHEME(), extract_GALOIS_ELT(), extract_INPUT_ARGUMENT(), extract_INPUT_OUTPUT_ARGUMENT(), extract_KEY_RNS(), extract_OP_NAME(), extract_OUTPUT_ARGUMENT(), extract_POLYMOD_DEG_LOG2(), extract_RNS_TERM(), pisa::poly::FACTOR, pisa::poly::FHE_SCHEME, pisa::poly::GALOIS_ELT, pisa::poly::INPUT_ARGUMENT, pisa::poly::INPUT_OUTPUT_ARGUMENT, pisa::poly::KEY_RNS, pisa::OP_NAME, pisa::poly::OUTPUT_ARGUMENT, pisa::poly::PARAM, pisa::POLYMOD_DEG_LOG2, pisa::poly::QSIZE, pisa::poly::RNS_TERM, and inject_bundles::type.
Referenced by writeToASCIIComponents().
parse()
std::shared_ptr< pisa::poly::PolyProgram > PolynomialProgramHelper::parse (const std::string & filename_or_prefix, POLYNOMIAL_PROGRAM_FORMAT format = CSV, bool ignore_header = true) static
Definition at line 68 of file program_trace_helper.cpp.
References CSV, parseCSV(), and PROTOBUFF.
Referenced by main().
parse_CIPHER_DEGREE()
void PolynomialProgramHelper::parse_CIPHER_DEGREE (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 438 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_FACTOR()
void PolynomialProgramHelper::parse_FACTOR (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 479 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_FHE_SCHEME()
void PolynomialProgramHelper::parse_FHE_SCHEME (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 469 of file program_trace_helper.cpp.
References fromString().
Referenced by parseComponent().
parse_GALOIS_ELT()
void PolynomialProgramHelper::parse_GALOIS_ELT (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 474 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_INPUT_ARGUMENT()
void PolynomialProgramHelper::parse_INPUT_ARGUMENT (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 443 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_INPUT_OUTPUT_ARGUMENT()
void PolynomialProgramHelper::parse_INPUT_OUTPUT_ARGUMENT (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 453 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_KEY_RNS()
void PolynomialProgramHelper::parse_KEY_RNS (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 484 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_OP_NAME()
void PolynomialProgramHelper::parse_OP_NAME (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 433 of file program_trace_helper.cpp.
References whiteSpaceRemoved().
Referenced by parseComponent().
parse_OUTPUT_ARGUMENT()
void PolynomialProgramHelper::parse_OUTPUT_ARGUMENT (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 448 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_PARAM()
void PolynomialProgramHelper::parse_PARAM (const std::pair< std::string, std::pair< std::string, pisa::poly::ValueType >> component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 489 of file program_trace_helper.cpp.
parse_POLYMOD_DEG_LOG2()
void PolynomialProgramHelper::parse_POLYMOD_DEG_LOG2 (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 459 of file program_trace_helper.cpp.
Referenced by parseComponent().
parse_RNS_TERM()
void PolynomialProgramHelper::parse_RNS_TERM (const std::string & component, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 464 of file program_trace_helper.cpp.
Referenced by parseComponent().
parseComponent()
void PolynomialProgramHelper::parseComponent (const std::string & component, PARAM_TYPE type, std::shared_ptr< pisa::poly::PolyOperation > instr) static
Definition at line 330 of file program_trace_helper.cpp.
References pisa::poly::ALPHA, pisa::poly::CIPHER_DEGREE, pisa::poly::DNUM, pisa::poly::FACTOR, pisa::poly::FHE_SCHEME, pisa::poly::GALOIS_ELT, pisa::poly::INPUT_ARGUMENT, pisa::poly::INPUT_OUTPUT_ARGUMENT, pisa::poly::KEY_RNS, pisa::OP_NAME, pisa::poly::OUTPUT_ARGUMENT, pisa::poly::PARAM, parse_CIPHER_DEGREE(), parse_FACTOR(), parse_FHE_SCHEME(), parse_GALOIS_ELT(), parse_INPUT_ARGUMENT(), parse_INPUT_OUTPUT_ARGUMENT(), parse_KEY_RNS(), parse_OP_NAME(), parse_OUTPUT_ARGUMENT(), parse_POLYMOD_DEG_LOG2(), parse_RNS_TERM(), pisa::POLYMOD_DEG_LOG2, pisa::poly::QSIZE, pisa::poly::RNS_TERM, and inject_bundles::type.
parseCSV()
std::shared_ptr< pisa::poly::PolyProgram > PolynomialProgramHelper::parseCSV (const std::string & filename, bool ignore_header = true) static
Definition at line 100 of file program_trace_helper.cpp.
References pisa::poly::PolyProgram::create(), isolation_test::file, parseInstruction(), and trim().
Referenced by parse().
parseInstruction()
std::shared_ptr< pisa::poly::PolyOperation > PolynomialProgramHelper::parseInstruction (const std::vector< std::string > & components, std::shared_ptr< pisa::poly::PolyProgram > program) static
Definition at line 258 of file program_trace_helper.cpp.
References pisa::poly::library::createPolyOperation(), and OP_CODE_LOCATION.
Referenced by parseCSV().
writeToASCIIComponents()
std::vector< std::string > PolynomialProgramHelper::writeToASCIIComponents (const std::shared_ptr< pisa::poly::PolyOperation > operation) static
Definition at line 281 of file program_trace_helper.cpp.
References extractComponent().
Referenced by writeTraceToCSV().
writeTraceToCSV()
void PolynomialProgramHelper::writeTraceToCSV (const std::shared_ptr< pisa::poly::PolyProgram > trace, std::string file_name) static
Definition at line 163 of file program_trace_helper.cpp.
References isolation_test::file, and writeToASCIIComponents().
Referenced by main().
Member Data Documentation
OP_CODE_LOCATION
constexpr static int PolynomialProgramHelper::OP_CODE_LOCATION = 0 static constexpr
Definition at line 78 of file program_trace_helper.h.
Referenced by parseInstruction().
The documentation for this struct was generated from the following files:
p-isa_tools/program_mapper/trace_parser/program_trace_helper.h
p-isa_tools/program_mapper/trace_parser/program_trace_helper.cpp