version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Look everywhere for package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
