[default]
#extend-ignore-re = ["helo byd"]

[default.extend-identifiers]


[default.extend-words]
# variation of params
parms = "parms"
bload = "bload"
ser = "ser"
SerType = "SerType"

[files]
extend-exclude = [
    "requirements-dev.txt",
]
