# used for manually linking to protobuf/absl generated files
set(protobuf_SHARED_LIB_NAMES
  protobuf
  protobuf-lite
  absl_log_internal_check_op
  absl_leak_check
  absl_die_if_null
  absl_log_internal_conditions
  absl_log_internal_message
  absl_log_internal_nullguard
  absl_examine_stack
  absl_log_internal_format
  absl_log_internal_proto
  absl_log_internal_log_sink_set
  absl_log_sink
  absl_log_entry
  absl_flags
  absl_flags_internal
  absl_flags_marshalling
  absl_flags_reflection
  absl_flags_config
  absl_flags_program_name
  absl_flags_private_handle_accessor
  absl_flags_commandlineflag
  absl_flags_commandlineflag_internal
  absl_log_initialize
  absl_log_globals
  absl_log_internal_globals
  absl_hash
  absl_city
  absl_low_level_hash
  absl_raw_hash_set
  absl_hashtablez_sampler
  absl_statusor
  absl_status
  absl_cord
  absl_cordz_info
  absl_cord_internal
  absl_cordz_functions
  absl_exponential_biased
  absl_cordz_handle
  absl_crc_cord_state
  absl_crc32c
  absl_crc_internal
  absl_crc_cpu_detect
  absl_bad_optional_access
  absl_str_format_internal
  absl_strerror
  absl_synchronization
  absl_stacktrace
  absl_symbolize
  absl_debugging_internal
  absl_demangle_internal
  absl_graphcycles_internal
  absl_malloc_internal
  absl_time
  absl_civil_time
  absl_time_zone
  absl_bad_variant_access
  absl_strings
  absl_throw_delegate
  absl_int128
  absl_strings_internal
  absl_base
  absl_raw_logging_internal
  absl_log_severity
  absl_spinlock_wait
)

set(protobuf_STATIC_LIB_NAMES
  utf8_validity
)

set(protobuf_LIB_NAMES
  protobuf
  protobuf-lite
  absl_log_internal_check_op
  absl_leak_check
  absl_die_if_null
  absl_log_internal_conditions
  absl_log_internal_message
  absl_log_internal_nullguard
  absl_examine_stack
  absl_log_internal_format
  absl_log_internal_proto
  absl_log_internal_log_sink_set
  absl_log_sink
  absl_log_entry
  absl_flags
  absl_flags_internal
  absl_flags_marshalling
  absl_flags_reflection
  absl_flags_config
  absl_flags_program_name
  absl_flags_private_handle_accessor
  absl_flags_commandlineflag
  absl_flags_commandlineflag_internal
  absl_log_initialize
  absl_log_globals
  absl_log_internal_globals
  absl_hash
  absl_city
  absl_low_level_hash
  absl_raw_hash_set
  absl_hashtablez_sampler
  absl_statusor
  absl_status
  absl_cord
  absl_cordz_info
  absl_cord_internal
  absl_cordz_functions
  absl_exponential_biased
  absl_cordz_handle
  absl_crc_cord_state
  absl_crc32c
  absl_crc_internal
  absl_crc_cpu_detect
  absl_bad_optional_access
  absl_str_format_internal
  absl_strerror
  absl_synchronization
  absl_stacktrace
  absl_symbolize
  absl_debugging_internal
  absl_demangle_internal
  absl_graphcycles_internal
  absl_malloc_internal
  absl_time
  absl_civil_time
  absl_time_zone
  absl_bad_variant_access
  utf8_validity
  absl_strings
  absl_throw_delegate
  absl_int128
  absl_strings_internal
  absl_base
  absl_raw_logging_internal
  absl_log_severity
  absl_spinlock_wait
)
