repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-merge-conflict
        - id: mixed-line-ending
        - id: check-byte-order-marker
    - repo: https://github.com/crate-ci/typos
      rev: v1.20.9 # Updated 2024/04
      hooks:
        - id: typos
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.1 # Updated 2023/07
      hooks:
        - id: insert-license
          name: insert-license-shell
          files: \.(sh|py)$
          args:
          - --license-filepath
          # defaults to: LICENSE.txt
          - HEADER
        - id: insert-license
          name: insert-license-cpp
          files: \.(c|cc|cxx|cpp|h|hpp|hxx|inl|h.in)$
          args:
          - --license-filepath
          # defaults to: LICENSE.txt
          - HEADER
          - --comment-style
          - //                   # defaults to: #
    - repo: local
      hooks:
        - id: clang-format-14
          name: clang-format-14
          entry: clang-format-14
          language: system
          files: \.(c|cc|cxx|cpp|h|hpp|hxx|inl)$
          args: ["-i", "--style=file"]
        - id: cpplint
          name: cpplint
          entry: cpplint
          language: system
          files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
          args:
          - --recursive
