# Copyright (C) 2023 Intel Corporation

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0 # Updated 2023/02
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-merge-conflict
        - id: mixed-line-ending
        - id: check-yaml
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.15
      hooks:
        - id: remove-tabs
          files: \.(py)$
          args: [--whitespaces-count, '4']
