name: Format

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Fetch main branch for diff
        run: git fetch origin main

      - name: Run pre-commit on changed files only
        run: pre-commit run --from-ref origin/main --to-ref HEAD
