name: Format

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install -r assembler_tools/hec-assembler-tools/requirements.txt
        run: pip install -r requirements-dev.txt

      - name: Install Apt Dependencies
        run: sudo apt install -y clang-format-14

      - name: Fetch main branch for diff
        run: git fetch origin main

      - name: Run pre-commit on changed files only
        run: pre-commit run --from-ref origin/main --to-ref HEAD
