name: Format

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install Development Dependencies
        run: pip install -r requirements-dev.txt

      - name: Installing Component-specific Dependencies
        run: pip install -r assembler_tools/hec-assembler-tools/requirements.txt

      - name: Install Apt Dependencies
        run: sudo apt install -y clang-format-14

      - name: Fetch main branch for diff
        run: git fetch origin main

      - name: Run pre-commit on changed files only
        run: pre-commit run --from-ref origin/main --to-ref HEAD
