name: HEC Assembler Tools Tests
on:
  push:
    branches: [main]
    paths:
      - 'assembler_tools/hec-assembler-tools/**'
  pull_request:
    branches: [main]
    paths:
      - 'assembler_tools/hec-assembler-tools/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assembler_tools/hec-assembler-tools
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Check for changes in hec-assembler-tools
        id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            module:
              - '**'

      - name: Run unit tests
        if: steps.changes.outputs.module == 'true'
        run: pytest tests
