name: HEC Assembler Tools Tests
on:
  push:
    branches: [main]
    paths:
      - 'assembler_tools/hec-assembler-tools/**'
  pull_request:
    branches: [main]
    paths:
      - 'assembler_tools/hec-assembler-tools/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assembler_tools/hec-assembler-tools
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Check for changes in hec-assembler-tools
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            module:
              - '**'

      - name: Run unit tests
        if: steps.changes.outputs.module == 'true'
        run: pytest tests
